{ 
    "500px": "",
    "Accessible Icon": "",
    "Accusoft": "",
    "Acquisitions Incorporated": "",
    "Ad": "",
    "Address Book": "",
    "Address Card": "",
    "adjust": "",
    "App.net": "",
    "Adobe": "",
    "Adversal": "",
    "affiliatetheme": "",
    "Air Freshener": "",
    "Airbnb": "",
    "Algolia": "",
    "align-center": "",
    "align-justify": "",
    "align-left": "",
    "align-right": "",
    "Alipay": "",
    "Allergies": "",
    "Amazon": "",
    "Amazon Pay": "",
    "ambulance": "",
    "American Sign Language Interpreting": "",
    "Amilia": "",
    "Anchor": "",
    "Android": "",
    "AngelList": "",
    "Angle Double Down": "",
    "Angle Double Left": "",
    "Angle Double Right": "",
    "Angle Double Up": "",
    "angle-down": "",
    "angle-left": "",
    "angle-right": "",
    "angle-up": "",
    "Angry Face": "",
    "Angry Creative": "",
    "Angular": "",
    "Ankh": "",
    "App Store": "",
    "iOS App Store": "",
    "Apper Systems AB": "",
    "Apple": "",
    "Fruit Apple": "",
    "Apple Pay": "",
    "Archive": "",
    "Archway": "",
    "Alternate Arrow Circle Down": "",
    "Alternate Arrow Circle Left": "",
    "Alternate Arrow Circle Right": "",
    "Alternate Arrow Circle Up": "",
    "Arrow Circle Down": "",
    "Arrow Circle Left": "",
    "Arrow Circle Right": "",
    "Arrow Circle Up": "",
    "arrow-down": "",
    "arrow-left": "",
    "arrow-right": "",
    "arrow-up": "",
    "Alternate Arrows": "",
    "Alternate Arrows Horizontal": "",
    "Alternate Arrows Vertical": "",
    "Artstation": "",
    "Assistive Listening Systems": "",
    "asterisk": "",
    "Asymmetrik, Ltd.": "",
    "At": "",
    "Atlas": "",
    "Atlassian": "",
    "Atom": "",
    "Audible": "",
    "Audio Description": "",
    "Autoprefixer": "",
    "avianex": "",
    "Aviato": "",
    "Award": "",
    "Amazon Web Services (AWS)": "",
    "Baby": "",
    "Baby Carriage": "",
    "Backspace": "",
    "backward": "",
    "Bacon": "",
    "Bahá'í": "",
    "Balance Scale": "",
    "Balance Scale (Left-Weighted)": "",
    "Balance Scale (Right-Weighted)": "",
    "ban": "",
    "Band-Aid": "",
    "Bandcamp": "",
    "barcode": "",
    "Bars": "",
    "Baseball Ball": "",
    "Basketball Ball": "",
    "Bath": "",
    "Battery Empty": "",
    "Battery Full": "",
    "Battery 1/2 Full": "",
    "Battery 1/4 Full": "",
    "Battery 3/4 Full": "",
    "Battle.net": "",
    "Bed": "",
    "beer": "",
    "Behance": "",
    "Behance Square": "",
    "bell": "",
    "Bell Slash": "",
    "Bezier Curve": "",
    "Bible": "",
    "Bicycle": "",
    "Biking": "",
    "BIMobject": "",
    "Binoculars": "",
    "Biohazard": "",
    "Birthday Cake": "",
    "Bitbucket": "",
    "Bitcoin": "",
    "Bity": "",
    "Font Awesome Black Tie": "",
    "BlackBerry": "",
    "Blender": "",
    "Blender Phone": "",
    "Blind": "",
    "Blog": "",
    "Blogger": "",
    "Blogger B": "",
    "Bluetooth": "",
    "bold": "",
    "Lightning Bolt": "",
    "Bomb": "",
    "Bone": "",
    "Bong": "",
    "book": "",
    "Book of the Dead": "",
    "Medical Book": "",
    "Book Open": "",
    "Book Reader": "",
    "bookmark": "",
    "Bootstrap": "",
    "Border All": "",
    "Border None": "",
    "Border Style": "",
    "Bowling Ball": "",
    "Box": "",
    "Box Open": "",
    "Tissue Box": "",
    "Boxes": "",
    "Braille": "",
    "Brain": "",
    "Bread Slice": "",
    "Briefcase": "",
    "Medical Briefcase": "",
    "Broadcast Tower": "",
    "Broom": "",
    "Brush": "",
    "BTC": "",
    "Buffer": "",
    "Bug": "",
    "Building": "",
    "bullhorn": "",
    "Bullseye": "",
    "Burn": "",
    "Büromöbel-Experte GmbH & Co. KG.": "",
    "Bus": "",
    "Bus Alt": "",
    "Business Time": "",
    "Buy n Large": "",
    "BuySellAds": "",
    "Calculator": "",
    "Calendar": "",
    "Alternate Calendar": "",
    "Calendar Check": "",
    "Calendar with Day Focus": "",
    "Calendar Minus": "",
    "Calendar Plus": "",
    "Calendar Times": "",
    "Calendar with Week Focus": "",
    "camera": "",
    "Retro Camera": "",
    "Campground": "",
    "Canadian Maple Leaf": "",
    "Candy Cane": "",
    "Cannabis": "",
    "Capsules": "",
    "Car": "",
    "Alternate Car": "",
    "Car Battery": "",
    "Car Crash": "",
    "Car Side": "",
    "Caravan": "",
    "Caret Down": "",
    "Caret Left": "",
    "Caret Right": "",
    "Caret Square Down": "",
    "Caret Square Left": "",
    "Caret Square Right": "",
    "Caret Square Up": "",
    "Caret Up": "",
    "Carrot": "",
    "Shopping Cart Arrow Down": "",
    "Add to Shopping Cart": "",
    "Cash Register": "",
    "Cat": "",
    "Amazon Pay Credit Card": "",
    "American Express Credit Card": "",
    "Apple Pay Credit Card": "",
    "Diner's Club Credit Card": "",
    "Discover Credit Card": "",
    "JCB Credit Card": "",
    "MasterCard Credit Card": "",
    "Paypal Credit Card": "",
    "Stripe Credit Card": "",
    "Visa Credit Card": "",
    "Centercode": "",
    "Centos": "",
    "certificate": "",
    "Chair": "",
    "Chalkboard": "",
    "Chalkboard Teacher": "",
    "Charging Station": "",
    "Area Chart": "",
    "Bar Chart": "",
    "Line Chart": "",
    "Pie Chart": "",
    "Check": "",
    "Check Circle": "",
    "Double Check": "",
    "Check Square": "",
    "Cheese": "",
    "Chess": "",
    "Chess Bishop": "",
    "Chess Board": "",
    "Chess King": "",
    "Chess Knight": "",
    "Chess Pawn": "",
    "Chess Queen": "",
    "Chess Rook": "",
    "Chevron Circle Down": "",
    "Chevron Circle Left": "",
    "Chevron Circle Right": "",
    "Chevron Circle Up": "",
    "chevron-down": "",
    "chevron-left": "",
    "chevron-right": "",
    "chevron-up": "",
    "Child": "",
    "Chrome": "",
    "Chromecast": "",
    "Church": "",
    "Circle": "",
    "Circle Notched": "",
    "City": "",
    "Medical Clinic": "",
    "Clipboard": "",
    "Clipboard with Check": "",
    "Clipboard List": "",
    "Clock": "",
    "Clone": "",
    "Closed Captioning": "",
    "Cloud": "",
    "Alternate Cloud Download": "",
    "Cloud with (a chance of) Meatball": "",
    "Cloud with Moon": "",
    "Cloud with Moon and Rain": "",
    "Cloud with Rain": "",
    "Cloud with Heavy Showers": "",
    "Cloud with Sun": "",
    "Cloud with Sun and Rain": "",
    "Alternate Cloud Upload": "",
    "cloudscale.ch": "",
    "Cloudsmith": "",
    "cloudversify": "",
    "Cocktail": "",
    "Code": "",
    "Code Branch": "",
    "Codepen": "",
    "Codie Pie": "",
    "Coffee": "",
    "cog": "",
    "cogs": "",
    "Coins": "",
    "Columns": "",
    "comment": "",
    "Alternate Comment": "",
    "Comment Dollar": "",
    "Comment Dots": "",
    "Alternate Medical Chat": "",
    "Comment Slash": "",
    "comments": "",
    "Comments Dollar": "",
    "Compact Disc": "",
    "Compass": "",
    "Compress": "",
    "Alternate Compress": "",
    "Alternate Compress Arrows": "",
    "Concierge Bell": "",
    "Confluence": "",
    "Connect Develop": "",
    "Contao": "",
    "Cookie": "",
    "Cookie Bite": "",
    "Copy": "",
    "Copyright": "",
    "Cotton Bureau": "",
    "Couch": "",
    "cPanel": "",
    "Creative Commons": "",
    "Creative Commons Attribution": "",
    "Creative Commons Noncommercial": "",
    "Creative Commons Noncommercial (Euro Sign)": "",
    "Creative Commons Noncommercial (Yen Sign)": "",
    "Creative Commons No Derivative Works": "",
    "Creative Commons Public Domain": "",
    "Alternate Creative Commons Public Domain": "",
    "Creative Commons Remix": "",
    "Creative Commons Share Alike": "",
    "Creative Commons Sampling": "",
    "Creative Commons Sampling +": "",
    "Creative Commons Share": "",
    "Creative Commons CC0": "",
    "Credit Card": "",
    "Critical Role": "",
    "crop": "",
    "Alternate Crop": "",
    "Cross": "",
    "Crosshairs": "",
    "Crow": "",
    "Crown": "",
    "Crutch": "",
    "CSS 3 Logo": "",
    "Alternate CSS3 Logo": "",
    "Cube": "",
    "Cubes": "",
    "Cut": "",
    "Cuttlefish": "",
    "Dungeons & Dragons": "",
    "D&D Beyond": "",
    "dailymotion": "",
    "DashCube": "",
    "Database": "",
    "Deaf": "",
    "Delicious": "",
    "Democrat": "",
    "deploy.dog": "",
    "Deskpro": "",
    "Desktop": "",
    "DEV": "",
    "deviantART": "",
    "Dharmachakra": "",
    "DHL": "",
    "Diagnoses": "",
    "Diaspora": "",
    "Dice": "",
    "Dice D20": "",
    "Dice D6": "",
    "Dice Five": "",
    "Dice Four": "",
    "Dice One": "",
    "Dice Six": "",
    "Dice Three": "",
    "Dice Two": "",
    "Digg Logo": "",
    "Digital Ocean": "",
    "Digital Tachograph": "",
    "Directions": "",
    "Discord": "",
    "Discourse": "",
    "Disease": "",
    "Divide": "",
    "Dizzy Face": "",
    "DNA": "",
    "DocHub": "",
    "Docker": "",
    "Dog": "",
    "Dollar Sign": "",
    "Dolly": "",
    "Dolly Flatbed": "",
    "Donate": "",
    "Door Closed": "",
    "Door Open": "",
    "Dot Circle": "",
    "Dove": "",
    "Download": "",
    "Draft2digital": "",
    "Drafting Compass": "",
    "Dragon": "",
    "Draw Polygon": "",
    "Dribbble": "",
    "Dribbble Square": "",
    "Dropbox": "",
    "Drum": "",
    "Drum Steelpan": "",
    "Drumstick with Bite Taken Out": "",
    "Drupal Logo": "",
    "Dumbbell": "",
    "Dumpster": "",
    "Dumpster Fire": "",
    "Dungeon": "",
    "Dyalog": "",
    "Earlybirds": "",
    "eBay": "",
    "Edge Browser": "",
    "Edit": "",
    "Egg": "",
    "eject": "",
    "Elementor": "",
    "Horizontal Ellipsis": "",
    "Vertical Ellipsis": "",
    "Ello": "",
    "Ember": "",
    "Galactic Empire": "",
    "Envelope": "",
    "Envelope Open": "",
    "Envelope Open-text": "",
    "Envelope Square": "",
    "Envira Gallery": "",
    "Equals": "",
    "eraser": "",
    "Erlang": "",
    "Ethereum": "",
    "Ethernet": "",
    "Etsy": "",
    "Euro Sign": "",
    "Evernote": "",
    "Alternate Exchange": "",
    "exclamation": "",
    "Exclamation Circle": "",
    "Exclamation Triangle": "",
    "Expand": "",
    "Alternate Expand": "",
    "Alternate Expand Arrows": "",
    "ExpeditedSSL": "",
    "Alternate External Link": "",
    "Alternate External Link Square": "",
    "Eye": "",
    "Eye Dropper": "",
    "Eye Slash": "",
    "Facebook": "",
    "Facebook F": "",
    "Facebook Messenger": "",
    "Facebook Square": "",
    "Fan": "",
    "Fantasy Flight-games": "",
    "fast-backward": "",
    "fast-forward": "",
    "Faucet": "",
    "Fax": "",
    "Feather": "",
    "Alternate Feather": "",
    "FedEx": "",
    "Fedora": "",
    "Female": "",
    "fighter-jet": "",
    "Figma": "",
    "File": "",
    "Alternate File": "",
    "Archive File": "",
    "Audio File": "",
    "Code File": "",
    "File Contract": "",
    "File CSV": "",
    "File Download": "",
    "Excel File": "",
    "File Export": "",
    "Image File": "",
    "File Import": "",
    "File Invoice": "",
    "File Invoice with US Dollar": "",
    "Medical File": "",
    "Alternate Medical File": "",
    "PDF File": "",
    "Powerpoint File": "",
    "File Prescription": "",
    "File Signature": "",
    "File Upload": "",
    "Video File": "",
    "Word File": "",
    "Fill": "",
    "Fill Drip": "",
    "Film": "",
    "Filter": "",
    "Fingerprint": "",
    "fire": "",
    "Alternate Fire": "",
    "fire-extinguisher": "",
    "Firefox": "",
    "Firefox Browser": "",
    "First Aid": "",
    "First Order": "",
    "Alternate First Order": "",
    "firstdraft": "",
    "Fish": "",
    "Raised Fist": "",
    "flag": "",
    "flag-checkered": "",
    "United States of America Flag": "",
    "Flask": "",
    "Flickr": "",
    "Flipboard": "",
    "Flushed Face": "",
    "Fly": "",
    "Folder": "",
    "Folder Minus": "",
    "Folder Open": "",
    "Folder Plus": "",
    "font": "",
    "Font Awesome": "",
    "Alternate Font Awesome": "",
    "Font Awesome Flag": "",
    "Font Awesome Full Logo": "",
    "Fonticons": "",
    "Fonticons Fi": "",
    "Football Ball": "",
    "Fort Awesome": "",
    "Alternate Fort Awesome": "",
    "Forumbee": "",
    "forward": "",
    "Foursquare": "",
    "freeCodeCamp": "",
    "FreeBSD": "",
    "Frog": "",
    "Frowning Face": "",
    "Frowning Face With Open Mouth": "",
    "Fulcrum": "",
    "Funnel Dollar": "",
    "Futbol": "",
    "Galactic Republic": "",
    "Galactic Senate": "",
    "Gamepad": "",
    "Gas Pump": "",
    "Gavel": "",
    "Gem": "",
    "Genderless": "",
    "Get Pocket": "",
    "GG Currency": "",
    "GG Currency Circle": "",
    "Ghost": "",
    "gift": "",
    "Gifts": "",
    "Git": "",
    "Git Alt": "",
    "Git Square": "",
    "GitHub": "",
    "Alternate GitHub": "",
    "GitHub Square": "",
    "GitKraken": "",
    "GitLab": "",
    "Gitter": "",
    "Glass Cheers": "",
    "Martini Glass": "",
    "Alternate Glass Martini": "",
    "Glass Whiskey": "",
    "Glasses": "",
    "Glide": "",
    "Glide G": "",
    "Globe": "",
    "Globe with Africa shown": "",
    "Globe with Americas shown": "",
    "Globe with Asia shown": "",
    "Globe with Europe shown": "",
    "Gofore": "",
    "Golf Ball": "",
    "Goodreads": "",
    "Goodreads G": "",
    "Google Logo": "",
    "Google Drive": "",
    "Google Play": "",
    "Google Plus": "",
    "Google Plus G": "",
    "Google Plus Square": "",
    "Google Wallet": "",
    "Gopuram": "",
    "Graduation Cap": "",
    "Gratipay (Gittip)": "",
    "Grav": "",
    "Greater Than": "",
    "Greater Than Equal To": "",
    "Grimacing Face": "",
    "Grinning Face": "",
    "Alternate Grinning Face": "",
    "Grinning Face With Smiling Eyes": "",
    "Grinning Face With Sweat": "",
    "Smiling Face With Heart-Eyes": "",
    "Grinning Squinting Face": "",
    "Rolling on the Floor Laughing": "",
    "Star-Struck": "",
    "Face With Tears of Joy": "",
    "Face With Tongue": "",
    "Squinting Face With Tongue": "",
    "Winking Face With Tongue": "",
    "Grinning Winking Face": "",
    "Grip Horizontal": "",
    "Grip Lines": "",
    "Grip Lines Vertical": "",
    "Grip Vertical": "",
    "Gripfire, Inc.": "",
    "Grunt": "",
    "Guitar": "",
    "Gulp": "",
    "H Square": "",
    "Hacker News": "",
    "Hacker News Square": "",
    "Hackerrank": "",
    "Hamburger": "",
    "Hammer": "",
    "Hamsa": "",
    "Hand Holding": "",
    "Hand Holding Heart": "",
    "Hand Holding Medical Cross": "",
    "Hand Holding US Dollar": "",
    "Hand Holding Water": "",
    "Lizard (Hand)": "",
    "Hand with Middle Finger Raised": "",
    "Paper (Hand)": "",
    "Peace (Hand)": "",
    "Hand Pointing Down": "",
    "Hand Pointing Left": "",
    "Hand Pointing Right": "",
    "Hand Pointing Up": "",
    "Pointer (Hand)": "",
    "Rock (Hand)": "",
    "Scissors (Hand)": "",
    "Hand Sparkles": "",
    "Spock (Hand)": "",
    "Hands": "",
    "Helping Hands": "",
    "Hands Wash": "",
    "Handshake": "",
    "Handshake Alternate Slash": "",
    "Handshake Slash": "",
    "Hanukiah": "",
    "Hard Hat": "",
    "Hashtag": "",
    "Cowboy Hat": "",
    "Cowboy Hat Side": "",
    "Wizard's Hat": "",
    "HDD": "",
    "Head Side Cough": "",
    "Head Side-cough-slash": "",
    "Head Side Mask": "",
    "Head Side Virus": "",
    "heading": "",
    "headphones": "",
    "Alternate Headphones": "",
    "Headset": "",
    "Heart": "",
    "Heart Broken": "",
    "Heartbeat": "",
    "Helicopter": "",
    "Highlighter": "",
    "Hiking": "",
    "Hippo": "",
    "Hips": "",
    "HireAHelper": "",
    "History": "",
    "Hockey Puck": "",
    "Holly Berry": "",
    "home": "",
    "Hooli": "",
    "Hornbill": "",
    "Horse": "",
    "Horse Head": "",
    "hospital": "",
    "Alternate Hospital": "",
    "Hospital Symbol": "",
    "Hospital with User": "",
    "Hot Tub": "",
    "Hot Dog": "",
    "Hotel": "",
    "Hotjar": "",
    "Hourglass": "",
    "Hourglass End": "",
    "Hourglass Half": "",
    "Hourglass Start": "",
    "Damaged House": "",
    "House User": "",
    "Houzz": "",
    "Hryvnia": "",
    "HTML 5 Logo": "",
    "HubSpot": "",
    "I Beam Cursor": "",
    "Ice Cream": "",
    "Icicles": "",
    "Icons": "",
    "Identification Badge": "",
    "Identification Card": "",
    "Alternate Identification Card": "",
    "iDeal": "",
    "Igloo": "",
    "Image": "",
    "Images": "",
    "IMDB": "",
    "inbox": "",
    "Indent": "",
    "Industry": "",
    "Infinity": "",
    "Info": "",
    "Info Circle": "",
    "Instagram": "",
    "Instagram Square": "",
    "Intercom": "",
    "Internet-explorer": "",
    "InVision": "",
    "ioxhost": "",
    "italic": "",
    "itch.io": "",
    "iTunes": "",
    "Itunes Note": "",
    "Java": "",
    "Jedi": "",
    "Jedi Order": "",
    "Jenkis": "",
    "Jira": "",
    "Joget": "",
    "Joint": "",
    "Joomla Logo": "",
    "Journal of the Whills": "",
    "JavaScript (JS)": "",
    "JavaScript (JS) Square": "",
    "jsFiddle": "",
    "Kaaba": "",
    "Kaggle": "",
    "key": "",
    "Keybase": "",
    "Keyboard": "",
    "KeyCDN": "",
    "Khanda": "",
    "Kickstarter": "",
    "Kickstarter K": "",
    "Kissing Face": "",
    "Kissing Face With Smiling Eyes": "",
    "Face Blowing a Kiss": "",
    "Kiwi Bird": "",
    "KORVUE": "",
    "Landmark": "",
    "Language": "",
    "Laptop": "",
    "Laptop Code": "",
    "Laptop House": "",
    "Laptop Medical": "",
    "Laravel": "",
    "last.fm": "",
    "last.fm Square": "",
    "Grinning Face With Big Eyes": "",
    "Laugh Face with Beaming Eyes": "",
    "Laughing Squinting Face": "",
    "Laughing Winking Face": "",
    "Layer Group": "",
    "leaf": "",
    "Leanpub": "",
    "Lemon": "",
    "Less": "",
    "Less Than": "",
    "Less Than Equal To": "",
    "Alternate Level Down": "",
    "Alternate Level Up": "",
    "Life Ring": "",
    "Lightbulb": "",
    "Line": "",
    "Link": "",
    "LinkedIn": "",
    "LinkedIn In": "",
    "Linode": "",
    "Linux": "",
    "Turkish Lira Sign": "",
    "List": "",
    "Alternate List": "",
    "list-ol": "",
    "list-ul": "",
    "location-arrow": "",
    "lock": "",
    "Lock Open": "",
    "Alternate Long Arrow Down": "",
    "Alternate Long Arrow Left": "",
    "Alternate Long Arrow Right": "",
    "Alternate Long Arrow Up": "",
    "Low Vision": "",
    "Luggage Cart": "",
    "Lungs": "",
    "Lungs Virus": "",
    "lyft": "",
    "Magento": "",
    "magic": "",
    "magnet": "",
    "Mail Bulk": "",
    "Mailchimp": "",
    "Male": "",
    "Mandalorian": "",
    "Map": "",
    "Map Marked": "",
    "Alternate Map Marked": "",
    "map-marker": "",
    "Alternate Map Marker": "",
    "Map Pin": "",
    "Map Signs": "",
    "Markdown": "",
    "Marker": "",
    "Mars": "",
    "Mars Double": "",
    "Mars Stroke": "",
    "Mars Stroke Horizontal": "",
    "Mars Stroke Vertical": "",
    "Mask": "",
    "Mastodon": "",
    "MaxCDN": "",
    "Material Design for Bootstrap": "",
    "Medal": "",
    "MedApps": "",
    "Medium": "",
    "Medium M": "",
    "medkit": "",
    "MRT": "",
    "Meetup": "",
    "Megaport": "",
    "Neutral Face": "",
    "Face Without Mouth": "",
    "Face With Rolling Eyes": "",
    "Memory": "",
    "Mendeley": "",
    "Menorah": "",
    "Mercury": "",
    "Meteor": "",
    "Micro.blog": "",
    "Microchip": "",
    "microphone": "",
    "Alternate Microphone": "",
    "Alternate Microphone Slash": "",
    "Microphone Slash": "",
    "Microscope": "",
    "Microsoft": "",
    "minus": "",
    "Minus Circle": "",
    "Minus Square": "",
    "Mitten": "",
    "Mix": "",
    "Mixcloud": "",
    "Mixer": "",
    "Mizuni": "",
    "Mobile Phone": "",
    "Alternate Mobile": "",
    "MODX": "",
    "Monero": "",
    "Money Bill": "",
    "Alternate Money Bill": "",
    "Wavy Money Bill": "",
    "Alternate Wavy Money Bill": "",
    "Money Check": "",
    "Alternate Money Check": "",
    "Monument": "",
    "Moon": "",
    "Mortar Pestle": "",
    "Mosque": "",
    "Motorcycle": "",
    "Mountain": "",
    "Mouse": "",
    "Mouse Pointer": "",
    "Mug Hot": "",
    "Music": "",
    "Napster": "",
    "Neos": "",
    "Wired Network": "",
    "Neuter": "",
    "Newspaper": "",
    "Nimblr": "",
    "Node.js": "",
    "Node.js JS": "",
    "Not Equal": "",
    "Medical Notes": "",
    "npm": "",
    "NS8": "",
    "Nutritionix": "",
    "Object Group": "",
    "Object Ungroup": "",
    "Odnoklassniki": "",
    "Odnoklassniki Square": "",
    "Oil Can": "",
    "Old Republic": "",
    "Om": "",
    "OpenCart": "",
    "OpenID": "",
    "Opera": "",
    "Optin Monster": "",
    "ORCID": "",
    "Open Source Initiative": "",
    "Otter": "",
    "Outdent": "",
    "page4 Corporation": "",
    "Pagelines": "",
    "Pager": "",
    "Paint Brush": "",
    "Paint Roller": "",
    "Palette": "",
    "Palfed": "",
    "Pallet": "",
    "Paper Plane": "",
    "Paperclip": "",
    "Parachute Box": "",
    "paragraph": "",
    "Parking": "",
    "Passport": "",
    "Pastafarianism": "",
    "Paste": "",
    "Patreon": "",
    "pause": "",
    "Pause Circle": "",
    "Paw": "",
    "Paypal": "",
    "Peace": "",
    "Pen": "",
    "Alternate Pen": "",
    "Pen Fancy": "",
    "Pen Nib": "",
    "Pen Square": "",
    "Alternate Pencil": "",
    "Pencil Ruler": "",
    "Penny Arcade": "",
    "People Arrows": "",
    "People Carry": "",
    "Hot Pepper": "",
    "Percent": "",
    "Percentage": "",
    "Periscope": "",
    "Person Entering Booth": "",
    "Phabricator": "",
    "Phoenix Framework": "",
    "Phoenix Squadron": "",
    "Phone": "",
    "Alternate Phone": "",
    "Phone Slash": "",
    "Phone Square": "",
    "Alternate Phone Square": "",
    "Phone Volume": "",
    "Photo Video": "",
    "PHP": "",
    "Pied Piper Logo": "",
    "Alternate Pied Piper Logo (Old)": "",
    "Pied Piper Hat (Old)": "",
    "Pied Piper PP Logo (Old)": "",
    "Pied Piper Square Logo (Old)": "",
    "Piggy Bank": "",
    "Pills": "",
    "Pinterest": "",
    "Pinterest P": "",
    "Pinterest Square": "",
    "Pizza Slice": "",
    "Place of Worship": "",
    "plane": "",
    "Plane Arrival": "",
    "Plane Departure": "",
    "Plane Slash": "",
    "play": "",
    "Play Circle": "",
    "PlayStation": "",
    "Plug": "",
    "plus": "",
    "Plus Circle": "",
    "Plus Square": "",
    "Podcast": "",
    "Poll": "",
    "Poll H": "",
    "Poo": "",
    "Poo Storm": "",
    "Poop": "",
    "Portrait": "",
    "Pound Sign": "",
    "Power Off": "",
    "Pray": "",
    "Praying Hands": "",
    "Prescription": "",
    "Prescription Bottle": "",
    "Alternate Prescription Bottle": "",
    "print": "",
    "Procedures": "",
    "Product Hunt": "",
    "Project Diagram": "",
    "Pump Medical": "",
    "Pump Soap": "",
    "Pushed": "",
    "Puzzle Piece": "",
    "Python": "",
    "QQ": "",
    "qrcode": "",
    "Question": "",
    "Question Circle": "",
    "Quidditch": "",
    "QuinScape": "",
    "Quora": "",
    "quote-left": "",
    "quote-right": "",
    "Quran": "",
    "R Project": "",
    "Radiation": "",
    "Alternate Radiation": "",
    "Rainbow": "",
    "random": "",
    "Raspberry Pi": "",
    "Ravelry": "",
    "React": "",
    "ReactEurope": "",
    "ReadMe": "",
    "Rebel Alliance": "",
    "Receipt": "",
    "Record Vinyl": "",
    "Recycle": "",
    "red river": "",
    "reddit Logo": "",
    "reddit Alien": "",
    "reddit Square": "",
    "Redhat": "",
    "Redo": "",
    "Alternate Redo": "",
    "Registered Trademark": "",
    "Remove Format": "",
    "Renren": "",
    "Reply": "",
    "reply-all": "",
    "replyd": "",
    "Republican": "",
    "Researchgate": "",
    "Resolving": "",
    "Restroom": "",
    "Retweet": "",
    "Rev.io": "",
    "Ribbon": "",
    "Ring": "",
    "road": "",
    "Robot": "",
    "rocket": "",
    "Rocket.Chat": "",
    "Rockrms": "",
    "Route": "",
    "rss": "",
    "RSS Square": "",
    "Ruble Sign": "",
    "Ruler": "",
    "Ruler Combined": "",
    "Ruler Horizontal": "",
    "Ruler Vertical": "",
    "Running": "",
    "Indian Rupee Sign": "",
    "Crying Face": "",
    "Loudly Crying Face": "",
    "Safari": "",
    "Salesforce": "",
    "Sass": "",
    "Satellite": "",
    "Satellite Dish": "",
    "Save": "",
    "SCHLIX": "",
    "School": "",
    "Screwdriver": "",
    "Scribd": "",
    "Scroll": "",
    "Sd Card": "",
    "Search": "",
    "Search Dollar": "",
    "Search Location": "",
    "Search Minus": "",
    "Search Plus": "",
    "Searchengin": "",
    "Seedling": "",
    "Sellcast": "",
    "Sellsy": "",
    "Server": "",
    "Servicestack": "",
    "Shapes": "",
    "Share": "",
    "Alternate Share": "",
    "Alternate Share Square": "",
    "Share Square": "",
    "Shekel Sign": "",
    "Alternate Shield": "",
    "Shield Virus": "",
    "Ship": "",
    "Shipping Fast": "",
    "Shirts in Bulk": "",
    "Shoe Prints": "",
    "Shopify": "",
    "Shopping Bag": "",
    "Shopping Basket": "",
    "shopping-cart": "",
    "Shopware": "",
    "Shower": "",
    "Shuttle Van": "",
    "Sign": "",
    "Alternate Sign In": "",
    "Sign Language": "",
    "Alternate Sign Out": "",
    "signal": "",
    "Signature": "",
    "SIM Card": "",
    "SimplyBuilt": "",
    "SISTRIX": "",
    "Sitemap": "",
    "Sith": "",
    "Skating": "",
    "Sketch": "",
    "Skiing": "",
    "Skiing Nordic": "",
    "Skull": "",
    "Skull & Crossbones": "",
    "skyatlas": "",
    "Skype": "",
    "Slack Logo": "",
    "Slack Hashtag": "",
    "Slash": "",
    "Sleigh": "",
    "Horizontal Sliders": "",
    "Slideshare": "",
    "Smiling Face": "",
    "Beaming Face With Smiling Eyes": "",
    "Winking Face": "",
    "Smog": "",
    "Smoking": "",
    "Smoking Ban": "",
    "SMS": "",
    "Snapchat": "",
    "Snapchat Ghost": "",
    "Snapchat Square": "",
    "Snowboarding": "",
    "Snowflake": "",
    "Snowman": "",
    "Snowplow": "",
    "Soap": "",
    "Socks": "",
    "Solar Panel": "",
    "Sort": "",
    "Sort Alphabetical Down": "",
    "Alternate Sort Alphabetical Down": "",
    "Sort Alphabetical Up": "",
    "Alternate Sort Alphabetical Up": "",
    "Sort Amount Down": "",
    "Alternate Sort Amount Down": "",
    "Sort Amount Up": "",
    "Alternate Sort Amount Up": "",
    "Sort Down (Descending)": "",
    "Sort Numeric Down": "",
    "Alternate Sort Numeric Down": "",
    "Sort Numeric Up": "",
    "Alternate Sort Numeric Up": "",
    "Sort Up (Ascending)": "",
    "SoundCloud": "",
    "Sourcetree": "",
    "Spa": "",
    "Space Shuttle": "",
    "Speakap": "",
    "Speaker Deck": "",
    "Spell Check": "",
    "Spider": "",
    "Spinner": "",
    "Splotch": "",
    "Spotify": "",
    "Spray Can": "",
    "Square": "",
    "Square Full": "",
    "Alternate Square Root": "",
    "Squarespace": "",
    "Stack Exchange": "",
    "Stack Overflow": "",
    "Stackpath": "",
    "Stamp": "",
    "Star": "",
    "Star and Crescent": "",
    "star-half": "",
    "Alternate Star Half": "",
    "Star of David": "",
    "Star of Life": "",
    "StayLinked": "",
    "Steam": "",
    "Steam Square": "",
    "Steam Symbol": "",
    "step-backward": "",
    "step-forward": "",
    "Stethoscope": "",
    "Sticker Mule": "",
    "Sticky Note": "",
    "stop": "",
    "Stop Circle": "",
    "Stopwatch": "",
    "Stopwatch 20": "",
    "Store": "",
    "Alternate Store": "",
    "Alternate Store Slash": "",
    "Store Slash": "",
    "Strava": "",
    "Stream": "",
    "Street View": "",
    "Strikethrough": "",
    "Stripe": "",
    "Stripe S": "",
    "Stroopwafel": "",
    "Studio Vinari": "",
    "StumbleUpon Logo": "",
    "StumbleUpon Circle": "",
    "subscript": "",
    "Subway": "",
    "Suitcase": "",
    "Suitcase Rolling": "",
    "Sun": "",
    "Superpowers": "",
    "superscript": "",
    "Supple": "",
    "Hushed Face": "",
    "Suse": "",
    "Swatchbook": "",
    "Swift": "",
    "Swimmer": "",
    "Swimming Pool": "",
    "Symfony": "",
    "Synagogue": "",
    "Sync": "",
    "Alternate Sync": "",
    "Syringe": "",
    "table": "",
    "Table Tennis": "",
    "tablet": "",
    "Alternate Tablet": "",
    "Tablets": "",
    "Alternate Tachometer": "",
    "tag": "",
    "tags": "",
    "Tape": "",
    "Tasks": "",
    "Taxi": "",
    "TeamSpeak": "",
    "Teeth": "",
    "Teeth Open": "",
    "Telegram": "",
    "Telegram Plane": "",
    "High Temperature": "",
    "Low Temperature": "",
    "Tencent Weibo": "",
    "Tenge": "",
    "Terminal": "",
    "text-height": "",
    "Text Width": "",
    "th": "",
    "th-large": "",
    "th-list": "",
    "The Red Yeti": "",
    "Theater Masks": "",
    "Themeco": "",
    "ThemeIsle": "",
    "Thermometer": "",
    "Thermometer Empty": "",
    "Thermometer Full": "",
    "Thermometer 1/2 Full": "",
    "Thermometer 1/4 Full": "",
    "Thermometer 3/4 Full": "",
    "Think Peaks": "",
    "thumbs-down": "",
    "thumbs-up": "",
    "Thumbtack": "",
    "Alternate Ticket": "",
    "Times": "",
    "Times Circle": "",
    "tint": "",
    "Tint Slash": "",
    "Tired Face": "",
    "Toggle Off": "",
    "Toggle On": "",
    "Toilet": "",
    "Toilet Paper": "",
    "Toilet Paper Slash": "",
    "Toolbox": "",
    "Tools": "",
    "Tooth": "",
    "Torah": "",
    "Torii Gate": "",
    "Tractor": "",
    "Trade Federation": "",
    "Trademark": "",
    "Traffic Light": "",
    "Trailer": "",
    "Train": "",
    "Tram": "",
    "Transgender": "",
    "Alternate Transgender": "",
    "Trash": "",
    "Alternate Trash": "",
    "Trash Restore": "",
    "Alternative Trash Restore": "",
    "Tree": "",
    "Trello": "",
    "TripAdvisor": "",
    "trophy": "",
    "truck": "",
    "Truck Loading": "",
    "Truck Monster": "",
    "Truck Moving": "",
    "Truck Side": "",
    "T-Shirt": "",
    "TTY": "",
    "Tumblr": "",
    "Tumblr Square": "",
    "Television": "",
    "Twitch": "",
    "Twitter": "",
    "Twitter Square": "",
    "Typo3": "",
    "Uber": "",
    "Ubuntu": "",
    "UIkit": "",
    "Umbraco": "",
    "Umbrella": "",
    "Umbrella Beach": "",
    "Underline": "",
    "Undo": "",
    "Alternate Undo": "",
    "Uniregistry": "",
    "Unity 3D": "",
    "Universal Access": "",
    "University": "",
    "unlink": "",
    "unlock": "",
    "Alternate Unlock": "",
    "Untappd": "",
    "Upload": "",
    "UPS": "",
    "USB": "",
    "User": "",
    "Alternate User": "",
    "Alternate User Slash": "",
    "User Astronaut": "",
    "User Check": "",
    "User Circle": "",
    "User Clock": "",
    "User Cog": "",
    "User Edit": "",
    "User Friends": "",
    "User Graduate": "",
    "User Injured": "",
    "User Lock": "",
    "Doctor": "",
    "User Minus": "",
    "User Ninja": "",
    "Nurse": "",
    "User Plus": "",
    "User Secret": "",
    "User Shield": "",
    "User Slash": "",
    "User Tag": "",
    "User Tie": "",
    "Remove User": "",
    "Users": "",
    "Users Cog": "",
    "United States Postal Service": "",
    "us-Sunnah Foundation": "",
    "Utensil Spoon": "",
    "Utensils": "",
    "Vaadin": "",
    "Vector Square": "",
    "Venus": "",
    "Venus Double": "",
    "Venus Mars": "",
    "Viacoin": "",
    "Video": "",
    "Video Square": "",
    "Vial": "",
    "Vials": "",
    "Viber": "",
    "Video Slash": "",
    "Vihara": "",
    "Vimeo": "",
    "Vimeo Square": "",
    "Vine": "",
    "Virus": "",
    "Virus Slash": "",
    "Viruses": "",
    "VK": "",
    "VNV": "",
    "Voicemail": "",
    "Volleyball Ball": "",
    "Volume Down": "",
    "Volume Mute": "",
    "Volume Off": "",
    "Volume Up": "",
    "Vote Yea": "",
    "Cardboard VR": "",
    "Vue.js": "",
    "Walking": "",
    "Wallet": "",
    "Warehouse": "",
    "Water": "",
    "Square Wave": "",
    "Waze": "",
    "Weebly": "",
    "Weibo": "",
    "Weight": "",
    "Hanging Weight": "",
    "Weixin (WeChat)": "",
    "What's App": "",
    "What's App Square": "",
    "Wheelchair": "",
    "WHMCS": "",
    "WiFi": "",
    "Wikipedia W": "",
    "Wind": "",
    "Window Close": "",
    "Window Maximize": "",
    "Window Minimize": "",
    "Window Restore": "",
    "Windows": "",
    "Wine Bottle": "",
    "Wine Glass": "",
    "Alternate Wine Glas": "",
    "Wix": "",
    "Wizards of the Coast": "",
    "Wolf Pack Battalion": "",
    "Won Sign": "",
    "WordPress Logo": "",
    "Wordpress Simple": "",
    "WPBeginner": "",
    "WPExplorer": "",
    "WPForms": "",
    "wpressr": "",
    "Wrench": "",
    "X-Ray": "",
    "Xbox": "",
    "Xing": "",
    "Xing Square": "",
    "Y Combinator": "",
    "Yahoo Logo": "",
    "Yammer": "",
    "Yandex": "",
    "Yandex International": "",
    "Yarn": "",
    "Yelp": "",
    "Yen Sign": "",
    "Yin Yang": "",
    "Yoast": "",
    "YouTube": "",
    "YouTube Square": "",
    "Zhihu": "" 
}