{ "500px": [],
 "accessible-icon": ["accessibility", "handicap", "person", "wheelchair", "wheelchair-alt"],
 "accusoft": [],
 "acquisitions-incorporated": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "game", "gaming", "tabletop"],
 "ad": ["advertisement", "media", "newspaper", "promotion", "publicity"],
 "address-book": ["contact", "directory", "index", "little black book", "rolodex"],
 "address-card": ["about", "contact", "id", "identification", "postcard", "profile"],
 "adjust": ["contrast", "dark", "light", "saturation"],
 "adn": [],
 "adobe": ["acrobat", "app", "design", "illustrator", "indesign", "photoshop"],
 "adversal": [],
 "affiliatetheme": [],
 "air-freshener": ["car", "deodorize", "fresh", "pine", "scent"],
 "airbnb": [],
 "algolia": [],
 "align-center": ["format", "middle", "paragraph", "text"],
 "align-justify": ["format", "paragraph", "text"],
 "align-left": ["format", "paragraph", "text"],
 "align-right": ["format", "paragraph", "text"],
 "alipay": [],
 "allergies": ["allergy", "freckles", "hand", "hives", "pox", "skin", "spots"],
 "amazon": [],
 "amazon-pay": [],
 "ambulance": ["covid-19", "emergency", "emt", "er", "help", "hospital", "support", "vehicle"],
 "american-sign-language-interpreting": ["asl", "deaf", "finger", "hand", "interpret", "speak"],
 "amilia": [],
 "anchor": ["berth", "boat", "dock", "embed", "link", "maritime", "moor", "secure"],
 "android": ["robot"],
 "angellist": [],
 "angle-double-down": ["arrows", "caret", "download", "expand"],
 "angle-double-left": ["arrows", "back", "caret", "laquo", "previous", "quote"],
 "angle-double-right": ["arrows", "caret", "forward", "more", "next", "quote", "raquo"],
 "angle-double-up": ["arrows", "caret", "collapse", "upload"],
 "angle-down": ["arrow", "caret", "download", "expand"],
 "angle-left": ["arrow", "back", "caret", "less", "previous"],
 "angle-right": ["arrow", "care", "forward", "more", "next"],
 "angle-up": ["arrow", "caret", "collapse", "upload"],
 "angry": ["disapprove", "emoticon", "face", "mad", "upset"],
 "angrycreative": [],
 "angular": [],
 "ankh": ["amulet", "copper", "coptic christianity", "copts", "crux ansata", "egypt", "venus"],
 "app-store": [],
 "app-store-ios": [],
 "apper": [],
 "apple": ["fruit", "ios", "mac", "operating system", "os", "osx"],
 "apple-alt": ["fall", "fruit", "fuji", "macintosh", "orchard", "seasonal", "vegan"],
 "apple-pay": [],
 "archive": ["box", "package", "save", "storage"],
 "archway": ["arc", "monument", "road", "street", "tunnel"],
 "arrow-alt-circle-down": ["arrow-circle-o-down", "download"],
 "arrow-alt-circle-left": ["arrow-circle-o-left", "back", "previous"],
 "arrow-alt-circle-right": ["arrow-circle-o-right", "forward", "next"],
 "arrow-alt-circle-up": ["arrow-circle-o-up"],
 "arrow-circle-down": ["download"],
 "arrow-circle-left": ["back", "previous"],
 "arrow-circle-right": ["forward", "next"],
 "arrow-circle-up": ["upload"],
 "arrow-down": ["download"],
 "arrow-left": ["back", "previous"],
 "arrow-right": ["forward", "next"],
 "arrow-up": ["forward", "upload"],
 "arrows-alt": ["arrow", "arrows", "bigger", "enlarge", "expand", "fullscreen", "move", "position", "reorder", "resize"],
 "arrows-alt-h": ["arrows-h", "expand", "horizontal", "landscape", "resize", "wide"],
 "arrows-alt-v": ["arrows-v", "expand", "portrait", "resize", "tall", "vertical"],
 "artstation": [],
 "assistive-listening-systems": ["amplify", "audio", "deaf", "ear", "headset", "hearing", "sound"],
 "asterisk": ["annotation", "details", "reference", "star"],
 "asymmetrik": [],
 "at": ["address", "author", "e-mail", "email", "handle"],
 "atlas": ["book", "directions", "geography", "globe", "map", "travel", "wayfinding"],
 "atlassian": [],
 "atom": ["atheism", "chemistry", "electron", "ion", "isotope", "neutron", "nuclear", "proton", "science"],
 "audible": [],
 "audio-description": ["blind", "narration", "video", "visual"],
 "autoprefixer": [],
 "avianex": [],
 "aviato": [],
 "award": ["honor", "praise", "prize", "recognition", "ribbon", "trophy"],
 "aws": [],
 "baby": ["child", "diaper", "doll", "human", "infant", "kid", "offspring", "person", "sprout"],
 "baby-carriage": ["buggy", "carrier", "infant", "push", "stroller", "transportation", "walk", "wheels"],
 "backspace": ["command", "delete", "erase", "keyboard", "undo"],
 "backward": ["previous", "rewind"],
 "bacon": ["blt", "breakfast", "ham", "lard", "meat", "pancetta", "pork", "rasher"],
 "bacteria": ["antibiotic", "antibody", "covid-19", "health", "organism", "sick"],
 "bacterium": ["antibiotic", "antibody", "covid-19", "health", "organism", "sick"],
 "bahai": ["bahai", "bahá'í", "star"],
 "balance-scale": ["balanced", "justice", "legal", "measure", "weight"],
 "balance-scale-left": ["justice", "legal", "measure", "unbalanced", "weight"],
 "balance-scale-right": ["justice", "legal", "measure", "unbalanced", "weight"],
 "ban": ["abort", "ban", "block", "cancel", "delete", "hide", "prohibit", "remove", "stop", "trash"],
 "band-aid": ["bandage", "boo boo", "first aid", "ouch"],
 "bandcamp": [],
 "barcode": ["info", "laser", "price", "scan", "upc"],
 "bars": ["checklist", "drag", "hamburger", "list", "menu", "nav", "navigation", "ol", "reorder", "settings", "todo", "ul"],
 "baseball-ball": ["foul", "hardball", "league", "leather", "mlb", "softball", "sport"],
 "basketball-ball": ["dribble", "dunk", "hoop", "nba"],
 "bath": ["clean", "shower", "tub", "wash"],
 "battery-empty": ["charge", "dead", "power", "status"],
 "battery-full": ["charge", "power", "status"],
 "battery-half": ["charge", "power", "status"],
 "battery-quarter": ["charge", "low", "power", "status"],
 "battery-three-quarters": ["charge", "power", "status"],
 "battle-net": [],
 "bed": ["lodging", "mattress", "rest", "sleep", "travel"],
 "beer": ["alcohol", "ale", "bar", "beverage", "brewery", "drink", "lager", "liquor", "mug", "stein"],
 "behance": [],
 "behance-square": [],
 "bell": ["alarm", "alert", "chime", "notification", "reminder"],
 "bell-slash": ["alert", "cancel", "disabled", "notification", "off", "reminder"],
 "bezier-curve": ["curves", "illustrator", "lines", "path", "vector"],
 "bible": ["book", "catholicism", "christianity", "god", "holy"],
 "bicycle": ["bike", "gears", "pedal", "transportation", "vehicle"],
 "biking": ["bicycle", "bike", "cycle", "cycling", "ride", "wheel"],
 "bimobject": [],
 "binoculars": ["glasses", "magnify", "scenic", "spyglass", "view"],
 "biohazard": ["covid-19", "danger", "dangerous", "hazmat", "medical", "radioactive", "toxic", "waste", "zombie"],
 "birthday-cake": ["anniversary", "bakery", "candles", "celebration", "dessert", "frosting", "holiday", "party", "pastry"],
 "bitbucket": ["atlassian", "bitbucket-square", "git"],
 "bitcoin": [],
 "bity": [],
 "black-tie": [],
 "blackberry": [],
 "blender": ["cocktail", "milkshake", "mixer", "puree", "smoothie"],
 "blender-phone": ["appliance", "cocktail", "communication", "fantasy", "milkshake", "mixer", "puree", "silly", "smoothie"],
 "blind": ["cane", "disability", "person", "sight"],
 "blog": ["journal", "log", "online", "personal", "post", "web 2.0", "wordpress", "writing"],
 "blogger": [],
 "blogger-b": [],
 "bluetooth": [],
 "bluetooth-b": [],
 "bold": ["emphasis", "format", "text"],
 "bolt": ["electricity", "lightning", "weather", "zap"],
 "bomb": ["error", "explode", "fuse", "grenade", "warning"],
 "bone": ["calcium", "dog", "skeletal", "skeleton", "tibia"],
 "bong": ["aparatus", "cannabis", "marijuana", "pipe", "smoke", "smoking"],
 "book": ["diary", "documentation", "journal", "library", "read"],
 "book-dead": ["Dungeons & Dragons", "crossbones", "d&d", "dark arts", "death", "dnd", "documentation", "evil", "fantasy", "halloween", "holiday", "necronomicon", "read", "skull", "spell"],
 "book-medical": ["diary", "documentation", "health", "history", "journal", "library", "read", "record"],
 "book-open": ["flyer", "library", "notebook", "open book", "pamphlet", "reading"],
 "book-reader": ["flyer", "library", "notebook", "open book", "pamphlet", "reading"],
 "bookmark": ["favorite", "marker", "read", "remember", "save"],
 "bootstrap": [],
 "border-all": ["cell", "grid", "outline", "stroke", "table"],
 "border-none": ["cell", "grid", "outline", "stroke", "table"],
 "border-style": [],
 "bowling-ball": ["alley", "candlepin", "gutter", "lane", "strike", "tenpin"],
 "box": ["archive", "container", "package", "storage"],
 "box-open": ["archive", "container", "package", "storage", "unpack"],
 "box-tissue": ["cough", "covid-19", "kleenex", "mucus", "nose", "sneeze", "snot"],
 "boxes": ["archives", "inventory", "storage", "warehouse"],
 "braille": ["alphabet", "blind", "dots", "raised", "vision"],
 "brain": ["cerebellum", "gray matter", "intellect", "medulla oblongata", "mind", "noodle", "wit"],
 "bread-slice": ["bake", "bakery", "baking", "dough", "flour", "gluten", "grain", "sandwich", "sourdough", "toast", "wheat", "yeast"],
 "briefcase": ["bag", "business", "luggage", "office", "work"],
 "briefcase-medical": ["doctor", "emt", "first aid", "health"],
 "broadcast-tower": ["airwaves", "antenna", "radio", "reception", "waves"],
 "broom": ["clean", "firebolt", "fly", "halloween", "nimbus 2000", "quidditch", "sweep", "witch"],
 "brush": ["art", "bristles", "color", "handle", "paint"],
 "btc": [],
 "buffer": [],
 "bug": ["beetle", "error", "insect", "report"],
 "building": ["apartment", "business", "city", "company", "office", "work"],
 "bullhorn": ["announcement", "broadcast", "louder", "megaphone", "share"],
 "bullseye": ["archery", "goal", "objective", "target"],
 "burn": ["caliente", "energy", "fire", "flame", "gas", "heat", "hot"],
 "buromobelexperte": [],
 "bus": ["public transportation", "transportation", "travel", "vehicle"],
 "bus-alt": ["mta", "public transportation", "transportation", "travel", "vehicle"],
 "business-time": ["alarm", "briefcase", "business socks", "clock", "flight of the conchords", "reminder", "wednesday"],
 "buy-n-large": [],
 "buysellads": [],
 "calculator": ["abacus", "addition", "arithmetic", "counting", "math", "multiplication", "subtraction"],
 "calendar": ["calendar-o", "date", "event", "schedule", "time", "when"],
 "calendar-alt": ["calendar", "date", "event", "schedule", "time", "when"],
 "calendar-check": ["accept", "agree", "appointment", "confirm", "correct", "date", "done", "event", "ok", "schedule", "select", "success", "tick", "time", "todo", "when"],
 "calendar-day": ["date", "detail", "event", "focus", "schedule", "single day", "time", "today", "when"],
 "calendar-minus": ["calendar", "date", "delete", "event", "negative", "remove", "schedule", "time", "when"],
 "calendar-plus": ["add", "calendar", "create", "date", "event", "new", "positive", "schedule", "time", "when"],
 "calendar-times": ["archive", "calendar", "date", "delete", "event", "remove", "schedule", "time", "when", "x"],
 "calendar-week": ["date", "detail", "event", "focus", "schedule", "single week", "time", "today", "when"],
 "camera": ["image", "lens", "photo", "picture", "record", "shutter", "video"],
 "camera-retro": ["image", "lens", "photo", "picture", "record", "shutter", "video"],
 "campground": ["camping", "fall", "outdoors", "teepee", "tent", "tipi"],
 "canadian-maple-leaf": ["canada", "flag", "flora", "nature", "plant"],
 "candy-cane": ["candy", "christmas", "holiday", "mint", "peppermint", "striped", "xmas"],
 "cannabis": ["bud", "chronic", "drugs", "endica", "endo", "ganja", "marijuana", "mary jane", "pot", "reefer", "sativa", "spliff", "weed", "whacky-tabacky"],
 "capsules": ["drugs", "medicine", "pills", "prescription"],
 "car": ["auto", "automobile", "sedan", "transportation", "travel", "vehicle"],
 "car-alt": ["auto", "automobile", "sedan", "transportation", "travel", "vehicle"],
 "car-battery": ["auto", "electric", "mechanic", "power"],
 "car-crash": ["accident", "auto", "automobile", "insurance", "sedan", "transportation", "vehicle", "wreck"],
 "car-side": ["auto", "automobile", "sedan", "transportation", "travel", "vehicle"],
 "caravan": ["camper", "motor home", "rv", "trailer", "travel"],
 "caret-down": ["arrow", "dropdown", "expand", "menu", "more", "triangle"],
 "caret-left": ["arrow", "back", "previous", "triangle"],
 "caret-right": ["arrow", "forward", "next", "triangle"],
 "caret-square-down": ["arrow", "caret-square-o-down", "dropdown", "expand", "menu", "more", "triangle"],
 "caret-square-left": ["arrow", "back", "caret-square-o-left", "previous", "triangle"],
 "caret-square-right": ["arrow", "caret-square-o-right", "forward", "next", "triangle"],
 "caret-square-up": ["arrow", "caret-square-o-up", "collapse", "triangle", "upload"],
 "caret-up": ["arrow", "collapse", "triangle"],
 "carrot": ["bugs bunny", "orange", "vegan", "vegetable"],
 "cart-arrow-down": ["download", "save", "shopping"],
 "cart-plus": ["add", "create", "new", "positive", "shopping"],
 "cash-register": ["buy", "cha-ching", "change", "checkout", "commerce", "leaerboard", "machine", "pay", "payment", "purchase", "store"],
 "cat": ["feline", "halloween", "holiday", "kitten", "kitty", "meow", "pet"],
 "cc-amazon-pay": [],
 "cc-amex": ["amex"],
 "cc-apple-pay": [],
 "cc-diners-club": [],
 "cc-discover": [],
 "cc-jcb": [],
 "cc-mastercard": [],
 "cc-paypal": [],
 "cc-stripe": [],
 "cc-visa": [],
 "centercode": [],
 "centos": ["linux", "operating system", "os"],
 "certificate": ["badge", "star", "verified"],
 "chair": ["furniture", "seat", "sit"],
 "chalkboard": ["blackboard", "learning", "school", "teaching", "whiteboard", "writing"],
 "chalkboard-teacher": ["blackboard", "instructor", "learning", "professor", "school", "whiteboard", "writing"],
 "charging-station": ["electric", "ev", "tesla", "vehicle"],
 "chart-area": ["analytics", "area", "chart", "graph"],
 "chart-bar": ["analytics", "bar", "chart", "graph"],
 "chart-line": ["activity", "analytics", "chart", "dashboard", "gain", "graph", "increase", "line"],
 "chart-pie": ["analytics", "chart", "diagram", "graph", "pie"],
 "check": ["accept", "agree", "checkmark", "confirm", "correct", "done", "notice", "notification", "notify", "ok", "select", "success", "tick", "todo", "yes"],
 "check-circle": ["accept", "agree", "confirm", "correct", "done", "ok", "select", "success", "tick", "todo", "yes"],
 "check-double": ["accept", "agree", "checkmark", "confirm", "correct", "done", "notice", "notification", "notify", "ok", "select", "success", "tick", "todo"],
 "check-square": ["accept", "agree", "checkmark", "confirm", "correct", "done", "ok", "select", "success", "tick", "todo", "yes"],
 "cheese": ["cheddar", "curd", "gouda", "melt", "parmesan", "sandwich", "swiss", "wedge"],
 "chess": ["board", "castle", "checkmate", "game", "king", "rook", "strategy", "tournament"],
 "chess-bishop": ["board", "checkmate", "game", "strategy"],
 "chess-board": ["board", "checkmate", "game", "strategy"],
 "chess-king": ["board", "checkmate", "game", "strategy"],
 "chess-knight": ["board", "checkmate", "game", "horse", "strategy"],
 "chess-pawn": ["board", "checkmate", "game", "strategy"],
 "chess-queen": ["board", "checkmate", "game", "strategy"],
 "chess-rook": ["board", "castle", "checkmate", "game", "strategy"],
 "chevron-circle-down": ["arrow", "download", "dropdown", "menu", "more"],
 "chevron-circle-left": ["arrow", "back", "previous"],
 "chevron-circle-right": ["arrow", "forward", "next"],
 "chevron-circle-up": ["arrow", "collapse", "upload"],
 "chevron-down": ["arrow", "download", "expand"],
 "chevron-left": ["arrow", "back", "bracket", "previous"],
 "chevron-right": ["arrow", "bracket", "forward", "next"],
 "chevron-up": ["arrow", "collapse", "upload"],
 "child": ["boy", "girl", "kid", "toddler", "young"],
 "chrome": ["browser"],
 "chromecast": [],
 "church": ["building", "cathedral", "chapel", "community", "religion"],
 "circle": ["circle-thin", "diameter", "dot", "ellipse", "notification", "round"],
 "circle-notch": ["circle-o-notch", "diameter", "dot", "ellipse", "round", "spinner"],
 "city": ["buildings", "busy", "skyscrapers", "urban", "windows"],
 "clinic-medical": ["covid-19", "doctor", "general practitioner", "hospital", "infirmary", "medicine", "office", "outpatient"],
 "clipboard": ["copy", "notes", "paste", "record"],
 "clipboard-check": ["accept", "agree", "confirm", "done", "ok", "select", "success", "tick", "todo", "yes"],
 "clipboard-list": ["checklist", "completed", "done", "finished", "intinerary", "ol", "schedule", "tick", "todo", "ul"],
 "clock": ["date", "late", "schedule", "time", "timer", "timestamp", "watch"],
 "clone": ["arrange", "copy", "duplicate", "paste"],
 "closed-captioning": ["cc", "deaf", "hearing", "subtitle", "subtitling", "text", "video"],
 "cloud": ["atmosphere", "fog", "overcast", "save", "upload", "weather"],
 "cloud-download-alt": ["download", "export", "save"],
 "cloud-meatball": ["FLDSMDFR", "food", "spaghetti", "storm"],
 "cloud-moon": ["crescent", "evening", "lunar", "night", "partly cloudy", "sky"],
 "cloud-moon-rain": ["crescent", "evening", "lunar", "night", "partly cloudy", "precipitation", "rain", "sky", "storm"],
 "cloud-rain": ["precipitation", "rain", "sky", "storm"],
 "cloud-showers-heavy": ["precipitation", "rain", "sky", "storm"],
 "cloud-sun": ["clear", "day", "daytime", "fall", "outdoors", "overcast", "partly cloudy"],
 "cloud-sun-rain": ["day", "overcast", "precipitation", "storm", "summer", "sunshower"],
 "cloud-upload-alt": ["cloud-upload", "import", "save", "upload"],
 "cloudscale": [],
 "cloudsmith": [],
 "cloudversify": [],
 "cocktail": ["alcohol", "beverage", "drink", "gin", "glass", "margarita", "martini", "vodka"],
 "code": ["brackets", "code", "development", "html"],
 "code-branch": ["branch", "code-fork", "fork", "git", "github", "rebase", "svn", "vcs", "version"],
 "codepen": [],
 "codiepie": [],
 "coffee": ["beverage", "breakfast", "cafe", "drink", "fall", "morning", "mug", "seasonal", "tea"],
 "cog": ["gear", "mechanical", "settings", "sprocket", "wheel"],
 "cogs": ["gears", "mechanical", "settings", "sprocket", "wheel"],
 "coins": ["currency", "dime", "financial", "gold", "money", "penny"],
 "columns": ["browser", "dashboard", "organize", "panes", "split"],
 "comment": ["bubble", "chat", "commenting", "conversation", "feedback", "message", "note", "notification", "sms", "speech", "texting"],
 "comment-alt": ["bubble", "chat", "commenting", "conversation", "feedback", "message", "note", "notification", "sms", "speech", "texting"],
 "comment-dollar": ["bubble", "chat", "commenting", "conversation", "feedback", "message", "money", "note", "notification", "pay", "sms", "speech", "spend", "texting", "transfer"],
 "comment-dots": ["bubble", "chat", "commenting", "conversation", "feedback", "message", "more", "note", "notification", "reply", "sms", "speech", "texting"],
 "comment-medical": ["advice", "bubble", "chat", "commenting", "conversation", "diagnose", "feedback", "message", "note", "notification", "prescription", "sms", "speech", "texting"],
 "comment-slash": ["bubble", "cancel", "chat", "commenting", "conversation", "feedback", "message", "mute", "note", "notification", "quiet", "sms", "speech", "texting"],
 "comments": ["bubble", "chat", "commenting", "conversation", "feedback", "message", "note", "notification", "sms", "speech", "texting"],
 "comments-dollar": ["bubble", "chat", "commenting", "conversation", "feedback", "message", "money", "note", "notification", "pay", "sms", "speech", "spend", "texting", "transfer"],
 "compact-disc": ["album", "bluray", "cd", "disc", "dvd", "media", "movie", "music", "record", "video", "vinyl"],
 "compass": ["directions", "directory", "location", "menu", "navigation", "safari", "travel"],
 "compress": ["collapse", "fullscreen", "minimize", "move", "resize", "shrink", "smaller"],
 "compress-alt": ["collapse", "fullscreen", "minimize", "move", "resize", "shrink", "smaller"],
 "compress-arrows-alt": ["collapse", "fullscreen", "minimize", "move", "resize", "shrink", "smaller"],
 "concierge-bell": ["attention", "hotel", "receptionist", "service", "support"],
 "confluence": ["atlassian"],
 "connectdevelop": [],
 "contao": [],
 "cookie": ["baked good", "chips", "chocolate", "eat", "snack", "sweet", "treat"],
 "cookie-bite": ["baked good", "bitten", "chips", "chocolate", "eat", "snack", "sweet", "treat"],
 "copy": ["clone", "duplicate", "file", "files-o", "paper", "paste"],
 "copyright": ["brand", "mark", "register", "trademark"],
 "cotton-bureau": ["clothing", "t-shirts", "tshirts"],
 "couch": ["chair", "cushion", "furniture", "relax", "sofa"],
 "cpanel": [],
 "creative-commons": [],
 "creative-commons-by": [],
 "creative-commons-nc": [],
 "creative-commons-nc-eu": [],
 "creative-commons-nc-jp": [],
 "creative-commons-nd": [],
 "creative-commons-pd": [],
 "creative-commons-pd-alt": [],
 "creative-commons-remix": [],
 "creative-commons-sa": [],
 "creative-commons-sampling": [],
 "creative-commons-sampling-plus": [],
 "creative-commons-share": [],
 "creative-commons-zero": [],
 "credit-card": ["buy", "checkout", "credit-card-alt", "debit", "money", "payment", "purchase"],
 "critical-role": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "game", "gaming", "tabletop"],
 "crop": ["design", "frame", "mask", "resize", "shrink"],
 "crop-alt": ["design", "frame", "mask", "resize", "shrink"],
 "cross": ["catholicism", "christianity", "church", "jesus"],
 "crosshairs": ["aim", "bullseye", "gpd", "picker", "position"],
 "crow": ["bird", "bullfrog", "fauna", "halloween", "holiday", "toad"],
 "crown": ["award", "favorite", "king", "queen", "royal", "tiara"],
 "crutch": ["cane", "injury", "mobility", "wheelchair"],
 "css3": ["code"],
 "css3-alt": [],
 "cube": ["3d", "block", "dice", "package", "square", "tesseract"],
 "cubes": ["3d", "block", "dice", "package", "pyramid", "square", "stack", "tesseract"],
 "cut": ["clip", "scissors", "snip"],
 "cuttlefish": [],
 "d-and-d": [],
 "d-and-d-beyond": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "gaming", "tabletop"],
 "dailymotion": [],
 "dashcube": [],
 "database": ["computer", "development", "directory", "memory", "storage"],
 "deaf": ["ear", "hearing", "sign language"],
 "deezer": [],
 "delicious": [],
 "democrat": ["american", "democratic party", "donkey", "election", "left", "left-wing", "liberal", "politics", "usa"],
 "deploydog": [],
 "deskpro": [],
 "desktop": ["computer", "cpu", "demo", "desktop", "device", "imac", "machine", "monitor", "pc", "screen"],
 "dev": [],
 "deviantart": [],
 "dharmachakra": ["buddhism", "buddhist", "wheel of dharma"],
 "dhl": ["Dalsey", "Hillblom and Lynn", "german", "package", "shipping"],
 "diagnoses": ["analyze", "detect", "diagnosis", "examine", "medicine"],
 "diaspora": [],
 "dice": ["chance", "gambling", "game", "roll"],
 "dice-d20": ["Dungeons & Dragons", "chance", "d&d", "dnd", "fantasy", "gambling", "game", "roll"],
 "dice-d6": ["Dungeons & Dragons", "chance", "d&d", "dnd", "fantasy", "gambling", "game", "roll"],
 "dice-five": ["chance", "gambling", "game", "roll"],
 "dice-four": ["chance", "gambling", "game", "roll"],
 "dice-one": ["chance", "gambling", "game", "roll"],
 "dice-six": ["chance", "gambling", "game", "roll"],
 "dice-three": ["chance", "gambling", "game", "roll"],
 "dice-two": ["chance", "gambling", "game", "roll"],
 "digg": [],
 "digital-ocean": [],
 "digital-tachograph": ["data", "distance", "speed", "tachometer"],
 "directions": ["map", "navigation", "sign", "turn"],
 "discord": [],
 "discourse": [],
 "disease": ["bacteria", "cancer", "covid-19", "illness", "infection", "sickness", "virus"],
 "divide": ["arithmetic", "calculus", "division", "math"],
 "dizzy": ["dazed", "dead", "disapprove", "emoticon", "face"],
 "dna": ["double helix", "genetic", "helix", "molecule", "protein"],
 "dochub": [],
 "docker": [],
 "dog": ["animal", "canine", "fauna", "mammal", "pet", "pooch", "puppy", "woof"],
 "dollar-sign": ["$", "cost", "dollar-sign", "money", "price", "usd"],
 "dolly": ["carry", "shipping", "transport"],
 "dolly-flatbed": ["carry", "inventory", "shipping", "transport"],
 "donate": ["contribute", "generosity", "gift", "give"],
 "door-closed": ["enter", "exit", "locked"],
 "door-open": ["enter", "exit", "welcome"],
 "dot-circle": ["bullseye", "notification", "target"],
 "dove": ["bird", "fauna", "flying", "peace", "war"],
 "download": ["export", "hard drive", "save", "transfer"],
 "draft2digital": [],
 "drafting-compass": ["design", "map", "mechanical drawing", "plot", "plotting"],
 "dragon": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "fire", "lizard", "serpent"],
 "draw-polygon": ["anchors", "lines", "object", "render", "shape"],
 "dribbble": [],
 "dribbble-square": [],
 "dropbox": [],
 "drum": ["instrument", "music", "percussion", "snare", "sound"],
 "drum-steelpan": ["calypso", "instrument", "music", "percussion", "reggae", "snare", "sound", "steel", "tropical"],
 "drumstick-bite": ["bone", "chicken", "leg", "meat", "poultry", "turkey"],
 "drupal": [],
 "dumbbell": ["exercise", "gym", "strength", "weight", "weight-lifting"],
 "dumpster": ["alley", "bin", "commercial", "trash", "waste"],
 "dumpster-fire": ["alley", "bin", "commercial", "danger", "dangerous", "euphemism", "flame", "heat", "hot", "trash", "waste"],
 "dungeon": ["Dungeons & Dragons", "building", "d&d", "dnd", "door", "entrance", "fantasy", "gate"],
 "dyalog": [],
 "earlybirds": [],
 "ebay": [],
 "edge": ["browser", "ie"],
 "edge-legacy": [],
 "edit": ["edit", "pen", "pencil", "update", "write"],
 "egg": ["breakfast", "chicken", "easter", "shell", "yolk"],
 "eject": ["abort", "cancel", "cd", "discharge"],
 "elementor": [],
 "ellipsis-h": ["dots", "drag", "kebab", "list", "menu", "nav", "navigation", "ol", "reorder", "settings", "ul"],
 "ellipsis-v": ["dots", "drag", "kebab", "list", "menu", "nav", "navigation", "ol", "reorder", "settings", "ul"],
 "ello": [],
 "ember": [],
 "empire": [],
 "envelope": ["e-mail", "email", "letter", "mail", "message", "notification", "support"],
 "envelope-open": ["e-mail", "email", "letter", "mail", "message", "notification", "support"],
 "envelope-open-text": ["e-mail", "email", "letter", "mail", "message", "notification", "support"],
 "envelope-square": ["e-mail", "email", "letter", "mail", "message", "notification", "support"],
 "envira": ["leaf"],
 "equals": ["arithmetic", "even", "match", "math"],
 "eraser": ["art", "delete", "remove", "rubber"],
 "erlang": [],
 "ethereum": [],
 "ethernet": ["cable", "cat 5", "cat 6", "connection", "hardware", "internet", "network", "wired"],
 "etsy": [],
 "euro-sign": ["currency", "dollar", "exchange", "money"],
 "evernote": [],
 "exchange-alt": ["arrow", "arrows", "exchange", "reciprocate", "return", "swap", "transfer"],
 "exclamation": ["alert", "danger", "error", "important", "notice", "notification", "notify", "problem", "warning"],
 "exclamation-circle": ["alert", "danger", "error", "important", "notice", "notification", "notify", "problem", "warning"],
 "exclamation-triangle": ["alert", "danger", "error", "important", "notice", "notification", "notify", "problem", "warning"],
 "expand": ["bigger", "enlarge", "fullscreen", "resize"],
 "expand-alt": ["arrows", "bigger", "enlarge", "fullscreen", "resize"],
 "expand-arrows-alt": ["bigger", "enlarge", "fullscreen", "move", "resize"],
 "expeditedssl": [],
 "external-link-alt": ["external-link", "new", "open", "share"],
 "external-link-square-alt": ["external-link-square", "new", "open", "share"],
 "eye": ["look", "optic", "see", "seen", "show", "sight", "views", "visible"],
 "eye-dropper": ["beaker", "clone", "color", "copy", "eyedropper", "pipette"],
 "eye-slash": ["blind", "hide", "show", "toggle", "unseen", "views", "visible", "visiblity"],
 "facebook": ["facebook-official", "social network"],
 "facebook-f": ["facebook"],
 "facebook-messenger": [],
 "facebook-square": ["social network"],
 "fan": ["ac", "air conditioning", "blade", "blower", "cool", "hot"],
 "fantasy-flight-games": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "game", "gaming", "tabletop"],
 "fast-backward": ["beginning", "first", "previous", "rewind", "start"],
 "fast-forward": ["end", "last", "next"],
 "faucet": ["covid-19", "drip", "house", "hygiene", "kitchen", "sink", "water"],
 "fax": ["business", "communicate", "copy", "facsimile", "send"],
 "feather": ["bird", "light", "plucked", "quill", "write"],
 "feather-alt": ["bird", "light", "plucked", "quill", "write"],
 "fedex": ["Federal Express", "package", "shipping"],
 "fedora": ["linux", "operating system", "os"],
 "female": ["human", "person", "profile", "user", "woman"],
 "fighter-jet": ["airplane", "fast", "fly", "goose", "maverick", "plane", "quick", "top gun", "transportation", "travel"],
 "figma": ["app", "design", "interface"],
 "file": ["document", "new", "page", "pdf", "resume"],
 "file-alt": ["document", "file-text", "invoice", "new", "page", "pdf"],
 "file-archive": [".zip", "bundle", "compress", "compression", "download", "zip"],
 "file-audio": ["document", "mp3", "music", "page", "play", "sound"],
 "file-code": ["css", "development", "document", "html"],
 "file-contract": ["agreement", "binding", "document", "legal", "signature"],
 "file-csv": ["document", "excel", "numbers", "spreadsheets", "table"],
 "file-download": ["document", "export", "save"],
 "file-excel": ["csv", "document", "numbers", "spreadsheets", "table"],
 "file-export": ["download", "save"],
 "file-image": ["document", "image", "jpg", "photo", "png"],
 "file-import": ["copy", "document", "send", "upload"],
 "file-invoice": ["account", "bill", "charge", "document", "payment", "receipt"],
 "file-invoice-dollar": ["$", "account", "bill", "charge", "document", "dollar-sign", "money", "payment", "receipt", "usd"],
 "file-medical": ["document", "health", "history", "prescription", "record"],
 "file-medical-alt": ["document", "health", "history", "prescription", "record"],
 "file-pdf": ["acrobat", "document", "preview", "save"],
 "file-powerpoint": ["display", "document", "keynote", "presentation"],
 "file-prescription": ["document", "drugs", "medical", "medicine", "rx"],
 "file-signature": ["John Hancock", "contract", "document", "name"],
 "file-upload": ["document", "import", "page", "save"],
 "file-video": ["document", "m4v", "movie", "mp4", "play"],
 "file-word": ["document", "edit", "page", "text", "writing"],
 "fill": ["bucket", "color", "paint", "paint bucket"],
 "fill-drip": ["bucket", "color", "drop", "paint", "paint bucket", "spill"],
 "film": ["cinema", "movie", "strip", "video"],
 "filter": ["funnel", "options", "separate", "sort"],
 "fingerprint": ["human", "id", "identification", "lock", "smudge", "touch", "unique", "unlock"],
 "fire": ["burn", "caliente", "flame", "heat", "hot", "popular"],
 "fire-alt": ["burn", "caliente", "flame", "heat", "hot", "popular"],
 "fire-extinguisher": ["burn", "caliente", "fire fighter", "flame", "heat", "hot", "rescue"],
 "firefox": ["browser"],
 "firefox-browser": ["browser"],
 "first-aid": ["emergency", "emt", "health", "medical", "rescue"],
 "first-order": [],
 "first-order-alt": [],
 "firstdraft": [],
 "fish": ["fauna", "gold", "seafood", "swimming"],
 "fist-raised": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "hand", "ki", "monk", "resist", "strength", "unarmed combat"],
 "flag": ["country", "notice", "notification", "notify", "pole", "report", "symbol"],
 "flag-checkered": ["notice", "notification", "notify", "pole", "racing", "report", "symbol"],
 "flag-usa": ["betsy ross", "country", "old glory", "stars", "stripes", "symbol"],
 "flask": ["beaker", "experimental", "labs", "science"],
 "flickr": [],
 "flipboard": [],
 "flushed": ["embarrassed", "emoticon", "face"],
 "fly": [],
 "folder": ["archive", "directory", "document", "file"],
 "folder-minus": ["archive", "delete", "directory", "document", "file", "negative", "remove"],
 "folder-open": ["archive", "directory", "document", "empty", "file", "new"],
 "folder-plus": ["add", "archive", "create", "directory", "document", "file", "new", "positive"],
 "font": ["alphabet", "glyph", "text", "type", "typeface"],
 "font-awesome": ["meanpath"],
 "font-awesome-alt": [],
 "font-awesome-flag": [],
 "font-awesome-logo-full": [],
 "fonticons": [],
 "fonticons-fi": [],
 "football-ball": ["ball", "fall", "nfl", "pigskin", "seasonal"],
 "fort-awesome": ["castle"],
 "fort-awesome-alt": ["castle"],
 "forumbee": [],
 "forward": ["forward", "next", "skip"],
 "foursquare": [],
 "free-code-camp": [],
 "freebsd": [],
 "frog": ["amphibian", "bullfrog", "fauna", "hop", "kermit", "kiss", "prince", "ribbit", "toad", "wart"],
 "frown": ["disapprove", "emoticon", "face", "rating", "sad"],
 "frown-open": ["disapprove", "emoticon", "face", "rating", "sad"],
 "fulcrum": [],
 "funnel-dollar": ["filter", "money", "options", "separate", "sort"],
 "futbol": ["ball", "football", "mls", "soccer"],
 "galactic-republic": ["politics", "star wars"],
 "galactic-senate": ["star wars"],
 "gamepad": ["arcade", "controller", "d-pad", "joystick", "video", "video game"],
 "gas-pump": ["car", "fuel", "gasoline", "petrol"],
 "gavel": ["hammer", "judge", "law", "lawyer", "opinion"],
 "gem": ["diamond", "jewelry", "sapphire", "stone", "treasure"],
 "genderless": ["androgynous", "asexual", "sexless"],
 "get-pocket": [],
 "gg": [],
 "gg-circle": [],
 "ghost": ["apparition", "blinky", "clyde", "floating", "halloween", "holiday", "inky", "pinky", "spirit"],
 "gift": ["christmas", "generosity", "giving", "holiday", "party", "present", "wrapped", "xmas"],
 "gifts": ["christmas", "generosity", "giving", "holiday", "party", "present", "wrapped", "xmas"],
 "git": [],
 "git-alt": [],
 "git-square": [],
 "github": ["octocat"],
 "github-alt": ["octocat"],
 "github-square": ["octocat"],
 "gitkraken": [],
 "gitlab": ["Axosoft"],
 "gitter": [],
 "glass-cheers": ["alcohol", "bar", "beverage", "celebration", "champagne", "clink", "drink", "holiday", "new year's eve", "party", "toast"],
 "glass-martini": ["alcohol", "bar", "beverage", "drink", "liquor"],
 "glass-martini-alt": ["alcohol", "bar", "beverage", "drink", "liquor"],
 "glass-whiskey": ["alcohol", "bar", "beverage", "bourbon", "drink", "liquor", "neat", "rye", "scotch", "whisky"],
 "glasses": ["hipster", "nerd", "reading", "sight", "spectacles", "vision"],
 "glide": [],
 "glide-g": [],
 "globe": ["all", "coordinates", "country", "earth", "global", "gps", "language", "localize", "location", "map", "online", "place", "planet", "translate", "travel", "world"],
 "globe-africa": ["all", "country", "earth", "global", "gps", "language", "localize", "location", "map", "online", "place", "planet", "translate", "travel", "world"],
 "globe-americas": ["all", "country", "earth", "global", "gps", "language", "localize", "location", "map", "online", "place", "planet", "translate", "travel", "world"],
 "globe-asia": ["all", "country", "earth", "global", "gps", "language", "localize", "location", "map", "online", "place", "planet", "translate", "travel", "world"],
 "globe-europe": ["all", "country", "earth", "global", "gps", "language", "localize", "location", "map", "online", "place", "planet", "translate", "travel", "world"],
 "gofore": [],
 "golf-ball": ["caddy", "eagle", "putt", "tee"],
 "goodreads": [],
 "goodreads-g": [],
 "google": [],
 "google-drive": [],
 "google-pay": [],
 "google-play": [],
 "google-plus": ["google-plus-circle", "google-plus-official"],
 "google-plus-g": ["google-plus", "social network"],
 "google-plus-square": ["social network"],
 "google-wallet": [],
 "gopuram": ["building", "entrance", "hinduism", "temple", "tower"],
 "graduation-cap": ["ceremony", "college", "graduate", "learning", "school", "student"],
 "gratipay": ["favorite", "heart", "like", "love"],
 "grav": [],
 "greater-than": ["arithmetic", "compare", "math"],
 "greater-than-equal": ["arithmetic", "compare", "math"],
 "grimace": ["cringe", "emoticon", "face", "teeth"],
 "grin": ["emoticon", "face", "laugh", "smile"],
 "grin-alt": ["emoticon", "face", "laugh", "smile"],
 "grin-beam": ["emoticon", "face", "laugh", "smile"],
 "grin-beam-sweat": ["embarass", "emoticon", "face", "smile"],
 "grin-hearts": ["emoticon", "face", "love", "smile"],
 "grin-squint": ["emoticon", "face", "laugh", "smile"],
 "grin-squint-tears": ["emoticon", "face", "happy", "smile"],
 "grin-stars": ["emoticon", "face", "star-struck"],
 "grin-tears": ["LOL", "emoticon", "face"],
 "grin-tongue": ["LOL", "emoticon", "face"],
 "grin-tongue-squint": ["LOL", "emoticon", "face"],
 "grin-tongue-wink": ["LOL", "emoticon", "face"],
 "grin-wink": ["emoticon", "face", "flirt", "laugh", "smile"],
 "grip-horizontal": ["affordance", "drag", "drop", "grab", "handle"],
 "grip-lines": ["affordance", "drag", "drop", "grab", "handle"],
 "grip-lines-vertical": ["affordance", "drag", "drop", "grab", "handle"],
 "grip-vertical": ["affordance", "drag", "drop", "grab", "handle"],
 "gripfire": [],
 "grunt": [],
 "guitar": ["acoustic", "instrument", "music", "rock", "rock and roll", "song", "strings"],
 "gulp": [],
 "h-square": ["directions", "emergency", "hospital", "hotel", "map"],
 "hacker-news": [],
 "hacker-news-square": [],
 "hackerrank": [],
 "hamburger": ["bacon", "beef", "burger", "burger king", "cheeseburger", "fast food", "grill", "ground beef", "mcdonalds", "sandwich"],
 "hammer": ["admin", "fix", "repair", "settings", "tool"],
 "hamsa": ["amulet", "christianity", "islam", "jewish", "judaism", "muslim", "protection"],
 "hand-holding": ["carry", "lift"],
 "hand-holding-heart": ["carry", "charity", "gift", "lift", "package"],
 "hand-holding-medical": ["care", "covid-19", "donate", "help"],
 "hand-holding-usd": ["$", "carry", "dollar sign", "donation", "giving", "lift", "money", "price"],
 "hand-holding-water": ["carry", "covid-19", "drought", "grow", "lift"],
 "hand-lizard": ["game", "roshambo"],
 "hand-middle-finger": ["flip the bird", "gesture", "hate", "rude"],
 "hand-paper": ["game", "halt", "roshambo", "stop"],
 "hand-peace": ["rest", "truce"],
 "hand-point-down": ["finger", "hand-o-down", "point"],
 "hand-point-left": ["back", "finger", "hand-o-left", "left", "point", "previous"],
 "hand-point-right": ["finger", "forward", "hand-o-right", "next", "point", "right"],
 "hand-point-up": ["finger", "hand-o-up", "point"],
 "hand-pointer": ["arrow", "cursor", "select"],
 "hand-rock": ["fist", "game", "roshambo"],
 "hand-scissors": ["cut", "game", "roshambo"],
 "hand-sparkles": ["clean", "covid-19", "hygiene", "magic", "soap", "wash"],
 "hand-spock": ["live long", "prosper", "salute", "star trek", "vulcan"],
 "hands": ["carry", "hold", "lift"],
 "hands-helping": ["aid", "assistance", "handshake", "partnership", "volunteering"],
 "hands-wash": ["covid-19", "hygiene", "soap", "wash"],
 "handshake": ["agreement", "greeting", "meeting", "partnership"],
 "handshake-alt-slash": ["broken", "covid-19", "social distance"],
 "handshake-slash": ["broken", "covid-19", "social distance"],
 "hanukiah": ["candle", "hanukkah", "jewish", "judaism", "light"],
 "hard-hat": ["construction", "hardhat", "helmet", "safety"],
 "hashtag": ["Twitter", "instagram", "pound", "social media", "tag"],
 "hat-cowboy": ["buckaroo", "horse", "jackeroo", "john b.", "old west", "pardner", "ranch", "rancher", "rodeo", "western", "wrangler"],
 "hat-cowboy-side": ["buckaroo", "horse", "jackeroo", "john b.", "old west", "pardner", "ranch", "rancher", "rodeo", "western", "wrangler"],
 "hat-wizard": ["Dungeons & Dragons", "accessory", "buckle", "clothing", "d&d", "dnd", "fantasy", "halloween", "head", "holiday", "mage", "magic", "pointy", "witch"],
 "hdd": ["cpu", "hard drive", "harddrive", "machine", "save", "storage"],
 "head-side-cough": ["cough", "covid-19", "germs", "lungs", "respiratory", "sick"],
 "head-side-cough-slash": ["cough", "covid-19", "germs", "lungs", "respiratory", "sick"],
 "head-side-mask": ["breath", "covid-19", "filter", "respirator", "virus"],
 "head-side-virus": ["cold", "covid-19", "flu", "sick"],
 "heading": ["format", "header", "text", "title"],
 "headphones": ["audio", "listen", "music", "sound", "speaker"],
 "headphones-alt": ["audio", "listen", "music", "sound", "speaker"],
 "headset": ["audio", "gamer", "gaming", "listen", "live chat", "microphone", "shot caller", "sound", "support", "telemarketer"],
 "heart": ["favorite", "like", "love", "relationship", "valentine"],
 "heart-broken": ["breakup", "crushed", "dislike", "dumped", "grief", "love", "lovesick", "relationship", "sad"],
 "heartbeat": ["ekg", "electrocardiogram", "health", "lifeline", "vital signs"],
 "helicopter": ["airwolf", "apache", "chopper", "flight", "fly", "travel"],
 "highlighter": ["edit", "marker", "sharpie", "update", "write"],
 "hiking": ["activity", "backpack", "fall", "fitness", "outdoors", "person", "seasonal", "walking"],
 "hippo": ["animal", "fauna", "hippopotamus", "hungry", "mammal"],
 "hips": [],
 "hire-a-helper": [],
 "history": ["Rewind", "clock", "reverse", "time", "time machine"],
 "hockey-puck": ["ice", "nhl", "sport"],
 "holly-berry": ["catwoman", "christmas", "decoration", "flora", "halle", "holiday", "ororo munroe", "plant", "storm", "xmas"],
 "home": ["abode", "building", "house", "main"],
 "hooli": [],
 "hornbill": [],
 "horse": ["equus", "fauna", "mammmal", "mare", "neigh", "pony"],
 "horse-head": ["equus", "fauna", "mammmal", "mare", "neigh", "pony"],
 "hospital": ["building", "covid-19", "emergency room", "medical center"],
 "hospital-alt": ["building", "covid-19", "emergency room", "medical center"],
 "hospital-symbol": ["clinic", "covid-19", "emergency", "map"],
 "hospital-user": ["covid-19", "doctor", "network", "patient", "primary care"],
 "hot-tub": ["bath", "jacuzzi", "massage", "sauna", "spa"],
 "hotdog": ["bun", "chili", "frankfurt", "frankfurter", "kosher", "polish", "sandwich", "sausage", "vienna", "weiner"],
 "hotel": ["building", "inn", "lodging", "motel", "resort", "travel"],
 "hotjar": [],
 "hourglass": ["hour", "minute", "sand", "stopwatch", "time"],
 "hourglass-end": ["hour", "minute", "sand", "stopwatch", "time"],
 "hourglass-half": ["hour", "minute", "sand", "stopwatch", "time"],
 "hourglass-start": ["hour", "minute", "sand", "stopwatch", "time"],
 "house-damage": ["building", "devastation", "disaster", "home", "insurance"],
 "house-user": ["covid-19", "home", "isolation", "quarantine"],
 "houzz": [],
 "hryvnia": ["currency", "money", "ukraine", "ukrainian"],
 "html5": [],
 "hubspot": [],
 "i-cursor": ["editing", "i-beam", "type", "writing"],
 "ice-cream": ["chocolate", "cone", "dessert", "frozen", "scoop", "sorbet", "vanilla", "yogurt"],
 "icicles": ["cold", "frozen", "hanging", "ice", "seasonal", "sharp"],
 "icons": ["bolt", "emoji", "heart", "image", "music", "photo", "symbols"],
 "id-badge": ["address", "contact", "identification", "license", "profile"],
 "id-card": ["contact", "demographics", "document", "identification", "issued", "profile"],
 "id-card-alt": ["contact", "demographics", "document", "identification", "issued", "profile"],
 "ideal": [],
 "igloo": ["dome", "dwelling", "eskimo", "home", "house", "ice", "snow"],
 "image": ["album", "landscape", "photo", "picture"],
 "images": ["album", "landscape", "photo", "picture"],
 "imdb": [],
 "inbox": ["archive", "desk", "email", "mail", "message"],
 "indent": ["align", "justify", "paragraph", "tab"],
 "industry": ["building", "factory", "industrial", "manufacturing", "mill", "warehouse"],
 "infinity": ["eternity", "forever", "math"],
 "info": ["details", "help", "information", "more", "support"],
 "info-circle": ["details", "help", "information", "more", "support"],
 "instagram": [],
 "instagram-square": [],
 "intercom": ["app", "customer", "messenger"],
 "internet-explorer": ["browser", "ie"],
 "invision": ["app", "design", "interface"],
 "ioxhost": [],
 "italic": ["edit", "emphasis", "font", "format", "text", "type"],
 "itch-io": [],
 "itunes": [],
 "itunes-note": [],
 "java": [],
 "jedi": ["crest", "force", "sith", "skywalker", "star wars", "yoda"],
 "jedi-order": ["star wars"],
 "jenkins": [],
 "jira": ["atlassian"],
 "joget": [],
 "joint": ["blunt", "cannabis", "doobie", "drugs", "marijuana", "roach", "smoke", "smoking", "spliff"],
 "joomla": [],
 "journal-whills": ["book", "force", "jedi", "sith", "star wars", "yoda"],
 "js": [],
 "js-square": [],
 "jsfiddle": [],
 "kaaba": ["building", "cube", "islam", "muslim"],
 "kaggle": [],
 "key": ["lock", "password", "private", "secret", "unlock"],
 "keybase": [],
 "keyboard": ["accessory", "edit", "input", "text", "type", "write"],
 "keycdn": [],
 "khanda": ["chakkar", "sikh", "sikhism", "sword"],
 "kickstarter": [],
 "kickstarter-k": [],
 "kiss": ["beso", "emoticon", "face", "love", "smooch"],
 "kiss-beam": ["beso", "emoticon", "face", "love", "smooch"],
 "kiss-wink-heart": ["beso", "emoticon", "face", "love", "smooch"],
 "kiwi-bird": ["bird", "fauna", "new zealand"],
 "korvue": [],
 "landmark": ["building", "historic", "memorable", "monument", "politics"],
 "language": ["dialect", "idiom", "localize", "speech", "translate", "vernacular"],
 "laptop": ["computer", "cpu", "dell", "demo", "device", "mac", "macbook", "machine", "pc"],
 "laptop-code": ["computer", "cpu", "dell", "demo", "develop", "device", "mac", "macbook", "machine", "pc"],
 "laptop-house": ["computer", "covid-19", "device", "office", "remote", "work from home"],
 "laptop-medical": ["computer", "device", "ehr", "electronic health records", "history"],
 "laravel": [],
 "lastfm": [],
 "lastfm-square": [],
 "laugh": ["LOL", "emoticon", "face", "laugh", "smile"],
 "laugh-beam": ["LOL", "emoticon", "face", "happy", "smile"],
 "laugh-squint": ["LOL", "emoticon", "face", "happy", "smile"],
 "laugh-wink": ["LOL", "emoticon", "face", "happy", "smile"],
 "layer-group": ["arrange", "develop", "layers", "map", "stack"],
 "leaf": ["eco", "flora", "nature", "plant", "vegan"],
 "leanpub": [],
 "lemon": ["citrus", "lemonade", "lime", "tart"],
 "less": [],
 "less-than": ["arithmetic", "compare", "math"],
 "less-than-equal": ["arithmetic", "compare", "math"],
 "level-down-alt": ["arrow", "level-down"],
 "level-up-alt": ["arrow", "level-up"],
 "life-ring": ["coast guard", "help", "overboard", "save", "support"],
 "lightbulb": ["energy", "idea", "inspiration", "light"],
 "line": [],
 "link": ["attach", "attachment", "chain", "connect"],
 "linkedin": ["linkedin-square"],
 "linkedin-in": ["linkedin"],
 "linode": [],
 "linux": ["tux"],
 "lira-sign": ["currency", "money", "try", "turkish"],
 "list": ["checklist", "completed", "done", "finished", "ol", "todo", "ul"],
 "list-alt": ["checklist", "completed", "done", "finished", "ol", "todo", "ul"],
 "list-ol": ["checklist", "completed", "done", "finished", "numbers", "ol", "todo", "ul"],
 "list-ul": ["checklist", "completed", "done", "finished", "ol", "todo", "ul"],
 "location-arrow": ["address", "compass", "coordinate", "direction", "gps", "map", "navigation", "place"],
 "lock": ["admin", "lock", "open", "password", "private", "protect", "security"],
 "lock-open": ["admin", "lock", "open", "password", "private", "protect", "security"],
 "long-arrow-alt-down": ["download", "long-arrow-down"],
 "long-arrow-alt-left": ["back", "long-arrow-left", "previous"],
 "long-arrow-alt-right": ["forward", "long-arrow-right", "next"],
 "long-arrow-alt-up": ["long-arrow-up", "upload"],
 "low-vision": ["blind", "eye", "sight"],
 "luggage-cart": ["bag", "baggage", "suitcase", "travel"],
 "lungs": ["air", "breath", "covid-19", "organ", "respiratory"],
 "lungs-virus": ["breath", "covid-19", "respiratory", "sick"],
 "lyft": [],
 "magento": [],
 "magic": ["autocomplete", "automatic", "mage", "magic", "spell", "wand", "witch", "wizard"],
 "magnet": ["Attract", "lodestone", "tool"],
 "mail-bulk": ["archive", "envelope", "letter", "post office", "postal", "postcard", "send", "stamp", "usps"],
 "mailchimp": [],
 "male": ["human", "man", "person", "profile", "user"],
 "mandalorian": [],
 "map": ["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
 "map-marked": ["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
 "map-marked-alt": ["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
 "map-marker": ["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
 "map-marker-alt": ["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
 "map-pin": ["address", "agree", "coordinates", "destination", "gps", "localize", "location", "map", "marker", "navigation", "pin", "place", "position", "travel"],
 "map-signs": ["directions", "directory", "map", "signage", "wayfinding"],
 "markdown": [],
 "marker": ["design", "edit", "sharpie", "update", "write"],
 "mars": ["male"],
 "mars-double": [],
 "mars-stroke": [],
 "mars-stroke-h": [],
 "mars-stroke-v": [],
 "mask": ["carnivale", "costume", "disguise", "halloween", "secret", "super hero"],
 "mastodon": [],
 "maxcdn": [],
 "mdb": [],
 "medal": ["award", "ribbon", "star", "trophy"],
 "medapps": [],
 "medium": [],
 "medium-m": [],
 "medkit": ["first aid", "firstaid", "health", "help", "support"],
 "medrt": [],
 "meetup": [],
 "megaport": [],
 "meh": ["emoticon", "face", "neutral", "rating"],
 "meh-blank": ["emoticon", "face", "neutral", "rating"],
 "meh-rolling-eyes": ["emoticon", "face", "neutral", "rating"],
 "memory": ["DIMM", "RAM", "hardware", "storage", "technology"],
 "mendeley": [],
 "menorah": ["candle", "hanukkah", "jewish", "judaism", "light"],
 "mercury": ["transgender"],
 "meteor": ["armageddon", "asteroid", "comet", "shooting star", "space"],
 "microblog": [],
 "microchip": ["cpu", "hardware", "processor", "technology"],
 "microphone": ["audio", "podcast", "record", "sing", "sound", "voice"],
 "microphone-alt": ["audio", "podcast", "record", "sing", "sound", "voice"],
 "microphone-alt-slash": ["audio", "disable", "mute", "podcast", "record", "sing", "sound", "voice"],
 "microphone-slash": ["audio", "disable", "mute", "podcast", "record", "sing", "sound", "voice"],
 "microscope": ["covid-19", "electron", "lens", "optics", "science", "shrink"],
 "microsoft": [],
 "minus": ["collapse", "delete", "hide", "minify", "negative", "remove", "trash"],
 "minus-circle": ["delete", "hide", "negative", "remove", "shape", "trash"],
 "minus-square": ["collapse", "delete", "hide", "minify", "negative", "remove", "shape", "trash"],
 "mitten": ["clothing", "cold", "glove", "hands", "knitted", "seasonal", "warmth"],
 "mix": [],
 "mixcloud": [],
 "mixer": [],
 "mizuni": [],
 "mobile": ["apple", "call", "cell phone", "cellphone", "device", "iphone", "number", "screen", "telephone"],
 "mobile-alt": ["apple", "call", "cell phone", "cellphone", "device", "iphone", "number", "screen", "telephone"],
 "modx": [],
 "monero": [],
 "money-bill": ["buy", "cash", "checkout", "money", "payment", "price", "purchase"],
 "money-bill-alt": ["buy", "cash", "checkout", "money", "payment", "price", "purchase"],
 "money-bill-wave": ["buy", "cash", "checkout", "money", "payment", "price", "purchase"],
 "money-bill-wave-alt": ["buy", "cash", "checkout", "money", "payment", "price", "purchase"],
 "money-check": ["bank check", "buy", "checkout", "cheque", "money", "payment", "price", "purchase"],
 "money-check-alt": ["bank check", "buy", "checkout", "cheque", "money", "payment", "price", "purchase"],
 "monument": ["building", "historic", "landmark", "memorable"],
 "moon": ["contrast", "crescent", "dark", "lunar", "night"],
 "mortar-pestle": ["crush", "culinary", "grind", "medical", "mix", "pharmacy", "prescription", "spices"],
 "mosque": ["building", "islam", "landmark", "muslim"],
 "motorcycle": ["bike", "machine", "transportation", "vehicle"],
 "mountain": ["glacier", "hiking", "hill", "landscape", "travel", "view"],
 "mouse": ["click", "computer", "cursor", "input", "peripheral"],
 "mouse-pointer": ["arrow", "cursor", "select"],
 "mug-hot": ["caliente", "cocoa", "coffee", "cup", "drink", "holiday", "hot chocolate", "steam", "tea", "warmth"],
 "music": ["lyrics", "melody", "note", "sing", "sound"],
 "napster": [],
 "neos": [],
 "network-wired": ["computer", "connect", "ethernet", "internet", "intranet"],
 "neuter": [],
 "newspaper": ["article", "editorial", "headline", "journal", "journalism", "news", "press"],
 "nimblr": [],
 "node": [],
 "node-js": [],
 "not-equal": ["arithmetic", "compare", "math"],
 "notes-medical": ["clipboard", "doctor", "ehr", "health", "history", "records"],
 "npm": [],
 "ns8": [],
 "nutritionix": [],
 "object-group": ["combine", "copy", "design", "merge", "select"],
 "object-ungroup": ["copy", "design", "merge", "select", "separate"],
 "odnoklassniki": [],
 "odnoklassniki-square": [],
 "oil-can": ["auto", "crude", "gasoline", "grease", "lubricate", "petroleum"],
 "old-republic": ["politics", "star wars"],
 "om": ["buddhism", "hinduism", "jainism", "mantra"],
 "opencart": [],
 "openid": [],
 "opera": [],
 "optin-monster": [],
 "orcid": [],
 "osi": [],
 "otter": ["animal", "badger", "fauna", "fur", "mammal", "marten"],
 "outdent": ["align", "justify", "paragraph", "tab"],
 "page4": [],
 "pagelines": ["eco", "flora", "leaf", "leaves", "nature", "plant", "tree"],
 "pager": ["beeper", "cellphone", "communication"],
 "paint-brush": ["acrylic", "art", "brush", "color", "fill", "paint", "pigment", "watercolor"],
 "paint-roller": ["acrylic", "art", "brush", "color", "fill", "paint", "pigment", "watercolor"],
 "palette": ["acrylic", "art", "brush", "color", "fill", "paint", "pigment", "watercolor"],
 "palfed": [],
 "pallet": ["archive", "box", "inventory", "shipping", "warehouse"],
 "paper-plane": ["air", "float", "fold", "mail", "paper", "send"],
 "paperclip": ["attach", "attachment", "connect", "link"],
 "parachute-box": ["aid", "assistance", "rescue", "supplies"],
 "paragraph": ["edit", "format", "text", "writing"],
 "parking": ["auto", "car", "garage", "meter"],
 "passport": ["document", "id", "identification", "issued", "travel"],
 "pastafarianism": ["agnosticism", "atheism", "flying spaghetti monster", "fsm"],
 "paste": ["clipboard", "copy", "document", "paper"],
 "patreon": [],
 "pause": ["hold", "wait"],
 "pause-circle": ["hold", "wait"],
 "paw": ["animal", "cat", "dog", "pet", "print"],
 "paypal": [],
 "peace": ["serenity", "tranquility", "truce", "war"],
 "pen": ["design", "edit", "update", "write"],
 "pen-alt": ["design", "edit", "update", "write"],
 "pen-fancy": ["design", "edit", "fountain pen", "update", "write"],
 "pen-nib": ["design", "edit", "fountain pen", "update", "write"],
 "pen-square": ["edit", "pencil-square", "update", "write"],
 "pencil-alt": ["design", "edit", "pencil", "update", "write"],
 "pencil-ruler": ["design", "draft", "draw", "pencil"],
 "penny-arcade": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "game", "gaming", "pax", "tabletop"],
 "people-arrows": ["covid-19", "personal space", "social distance", "space", "spread", "users"],
 "people-carry": ["box", "carry", "fragile", "help", "movers", "package"],
 "pepper-hot": ["buffalo wings", "capsicum", "chili", "chilli", "habanero", "jalapeno", "mexican", "spicy", "tabasco", "vegetable"],
 "percent": ["discount", "fraction", "proportion", "rate", "ratio"],
 "percentage": ["discount", "fraction", "proportion", "rate", "ratio"],
 "periscope": [],
 "person-booth": ["changing", "changing room", "election", "human", "person", "vote", "voting"],
 "phabricator": [],
 "phoenix-framework": [],
 "phoenix-squadron": [],
 "phone": ["call", "earphone", "number", "support", "telephone", "voice"],
 "phone-alt": ["call", "earphone", "number", "support", "telephone", "voice"],
 "phone-slash": ["call", "cancel", "earphone", "mute", "number", "support", "telephone", "voice"],
 "phone-square": ["call", "earphone", "number", "support", "telephone", "voice"],
 "phone-square-alt": ["call", "earphone", "number", "support", "telephone", "voice"],
 "phone-volume": ["call", "earphone", "number", "sound", "support", "telephone", "voice", "volume-control-phone"],
 "photo-video": ["av", "film", "image", "library", "media"],
 "php": [],
 "pied-piper": [],
 "pied-piper-alt": [],
 "pied-piper-hat": ["clothing"],
 "pied-piper-pp": [],
 "pied-piper-square": [],
 "piggy-bank": ["bank", "save", "savings"],
 "pills": ["drugs", "medicine", "prescription", "tablets"],
 "pinterest": [],
 "pinterest-p": [],
 "pinterest-square": [],
 "pizza-slice": ["cheese", "chicago", "italian", "mozzarella", "new york", "pepperoni", "pie", "slice", "teenage mutant ninja turtles", "tomato"],
 "place-of-worship": ["building", "church", "holy", "mosque", "synagogue"],
 "plane": ["airplane", "destination", "fly", "location", "mode", "travel", "trip"],
 "plane-arrival": ["airplane", "arriving", "destination", "fly", "land", "landing", "location", "mode", "travel", "trip"],
 "plane-departure": ["airplane", "departing", "destination", "fly", "location", "mode", "take off", "taking off", "travel", "trip"],
 "plane-slash": ["airplane mode", "canceled", "covid-19", "delayed", "grounded", "travel"],
 "play": ["audio", "music", "playing", "sound", "start", "video"],
 "play-circle": ["audio", "music", "playing", "sound", "start", "video"],
 "playstation": [],
 "plug": ["connect", "electric", "online", "power"],
 "plus": ["add", "create", "expand", "new", "positive", "shape"],
 "plus-circle": ["add", "create", "expand", "new", "positive", "shape"],
 "plus-square": ["add", "create", "expand", "new", "positive", "shape"],
 "podcast": ["audio", "broadcast", "music", "sound"],
 "poll": ["results", "survey", "trend", "vote", "voting"],
 "poll-h": ["results", "survey", "trend", "vote", "voting"],
 "poo": ["crap", "poop", "shit", "smile", "turd"],
 "poo-storm": ["bolt", "cloud", "euphemism", "lightning", "mess", "poop", "shit", "turd"],
 "poop": ["crap", "poop", "shit", "smile", "turd"],
 "portrait": ["id", "image", "photo", "picture", "selfie"],
 "pound-sign": ["currency", "gbp", "money"],
 "power-off": ["cancel", "computer", "on", "reboot", "restart"],
 "pray": ["kneel", "preach", "religion", "worship"],
 "praying-hands": ["kneel", "preach", "religion", "worship"],
 "prescription": ["drugs", "medical", "medicine", "pharmacy", "rx"],
 "prescription-bottle": ["drugs", "medical", "medicine", "pharmacy", "rx"],
 "prescription-bottle-alt": ["drugs", "medical", "medicine", "pharmacy", "rx"],
 "print": ["business", "copy", "document", "office", "paper"],
 "procedures": ["EKG", "bed", "electrocardiogram", "health", "hospital", "life", "patient", "vital"],
 "product-hunt": [],
 "project-diagram": ["chart", "graph", "network", "pert"],
 "pump-medical": ["anti-bacterial", "clean", "covid-19", "disinfect", "hygiene", "medical grade", "sanitizer", "soap"],
 "pump-soap": ["anti-bacterial", "clean", "covid-19", "disinfect", "hygiene", "sanitizer", "soap"],
 "pushed": [],
 "puzzle-piece": ["add-on", "addon", "game", "section"],
 "python": [],
 "qq": [],
 "qrcode": ["barcode", "info", "information", "scan"],
 "question": ["help", "information", "support", "unknown"],
 "question-circle": ["help", "information", "support", "unknown"],
 "quidditch": ["ball", "bludger", "broom", "golden snitch", "harry potter", "hogwarts", "quaffle", "sport", "wizard"],
 "quinscape": [],
 "quora": [],
 "quote-left": ["mention", "note", "phrase", "text", "type"],
 "quote-right": ["mention", "note", "phrase", "text", "type"],
 "quran": ["book", "islam", "muslim", "religion"],
 "r-project": [],
 "radiation": ["danger", "dangerous", "deadly", "hazard", "nuclear", "radioactive", "warning"],
 "radiation-alt": ["danger", "dangerous", "deadly", "hazard", "nuclear", "radioactive", "warning"],
 "rainbow": ["gold", "leprechaun", "prism", "rain", "sky"],
 "random": ["arrows", "shuffle", "sort", "swap", "switch", "transfer"],
 "raspberry-pi": [],
 "ravelry": [],
 "react": [],
 "reacteurope": [],
 "readme": [],
 "rebel": [],
 "receipt": ["check", "invoice", "money", "pay", "table"],
 "record-vinyl": ["LP", "album", "analog", "music", "phonograph", "sound"],
 "recycle": ["Waste", "compost", "garbage", "reuse", "trash"],
 "red-river": [],
 "reddit": [],
 "reddit-alien": [],
 "reddit-square": [],
 "redhat": ["linux", "operating system", "os"],
 "redo": ["forward", "refresh", "reload", "repeat"],
 "redo-alt": ["forward", "refresh", "reload", "repeat"],
 "registered": ["copyright", "mark", "trademark"],
 "remove-format": ["cancel", "font", "format", "remove", "style", "text"],
 "renren": [],
 "reply": ["mail", "message", "respond"],
 "reply-all": ["mail", "message", "respond"],
 "replyd": [],
 "republican": ["american", "conservative", "election", "elephant", "politics", "republican party", "right", "right-wing", "usa"],
 "researchgate": [],
 "resolving": [],
 "restroom": ["bathroom", "john", "loo", "potty", "washroom", "waste", "wc"],
 "retweet": ["refresh", "reload", "share", "swap"],
 "rev": [],
 "ribbon": ["badge", "cause", "lapel", "pin"],
 "ring": ["Dungeons & Dragons", "Gollum", "band", "binding", "d&d", "dnd", "engagement", "fantasy", "gold", "jewelry", "marriage", "precious"],
 "road": ["highway", "map", "pavement", "route", "street", "travel"],
 "robot": ["android", "automate", "computer", "cyborg"],
 "rocket": ["aircraft", "app", "jet", "launch", "nasa", "space"],
 "rocketchat": [],
 "rockrms": [],
 "route": ["directions", "navigation", "travel"],
 "rss": ["blog", "feed", "journal", "news", "writing"],
 "rss-square": ["blog", "feed", "journal", "news", "writing"],
 "ruble-sign": ["currency", "money", "rub"],
 "ruler": ["design", "draft", "length", "measure", "planning"],
 "ruler-combined": ["design", "draft", "length", "measure", "planning"],
 "ruler-horizontal": ["design", "draft", "length", "measure", "planning"],
 "ruler-vertical": ["design", "draft", "length", "measure", "planning"],
 "running": ["exercise", "health", "jog", "person", "run", "sport", "sprint"],
 "rupee-sign": ["currency", "indian", "inr", "money"],
 "rust": [],
 "sad-cry": ["emoticon", "face", "tear", "tears"],
 "sad-tear": ["emoticon", "face", "tear", "tears"],
 "safari": ["browser"],
 "salesforce": [],
 "sass": [],
 "satellite": ["communications", "hardware", "orbit", "space"],
 "satellite-dish": ["SETI", "communications", "hardware", "receiver", "saucer", "signal", "space"],
 "save": ["disk", "download", "floppy", "floppy-o"],
 "schlix": [],
 "school": ["building", "education", "learn", "student", "teacher"],
 "screwdriver": ["admin", "fix", "mechanic", "repair", "settings", "tool"],
 "scribd": [],
 "scroll": ["Dungeons & Dragons", "announcement", "d&d", "dnd", "fantasy", "paper", "script"],
 "sd-card": ["image", "memory", "photo", "save"],
 "search": ["bigger", "enlarge", "find", "magnify", "preview", "zoom"],
 "search-dollar": ["bigger", "enlarge", "find", "magnify", "money", "preview", "zoom"],
 "search-location": ["bigger", "enlarge", "find", "magnify", "preview", "zoom"],
 "search-minus": ["minify", "negative", "smaller", "zoom", "zoom out"],
 "search-plus": ["bigger", "enlarge", "magnify", "positive", "zoom", "zoom in"],
 "searchengin": [],
 "seedling": ["flora", "grow", "plant", "vegan"],
 "sellcast": ["eercast"],
 "sellsy": [],
 "server": ["computer", "cpu", "database", "hardware", "network"],
 "servicestack": [],
 "shapes": ["blocks", "build", "circle", "square", "triangle"],
 "share": ["forward", "save", "send", "social"],
 "share-alt": ["forward", "save", "send", "social"],
 "share-alt-square": ["forward", "save", "send", "social"],
 "share-square": ["forward", "save", "send", "social"],
 "shekel-sign": ["currency", "ils", "money"],
 "shield-alt": ["achievement", "award", "block", "defend", "security", "winner"],
 "shield-virus": ["antibodies", "barrier", "covid-19", "health", "protect"],
 "ship": ["boat", "sea", "water"],
 "shipping-fast": ["express", "fedex", "mail", "overnight", "package", "ups"],
 "shirtsinbulk": [],
 "shoe-prints": ["feet", "footprints", "steps", "walk"],
 "shopify": [],
 "shopping-bag": ["buy", "checkout", "grocery", "payment", "purchase"],
 "shopping-basket": ["buy", "checkout", "grocery", "payment", "purchase"],
 "shopping-cart": ["buy", "checkout", "grocery", "payment", "purchase"],
 "shopware": [],
 "shower": ["bath", "clean", "faucet", "water"],
 "shuttle-van": ["airport", "machine", "public-transportation", "transportation", "travel", "vehicle"],
 "sign": ["directions", "real estate", "signage", "wayfinding"],
 "sign-in-alt": ["arrow", "enter", "join", "log in", "login", "sign in", "sign up", "sign-in", "signin", "signup"],
 "sign-language": ["Translate", "asl", "deaf", "hands"],
 "sign-out-alt": ["arrow", "exit", "leave", "log out", "logout", "sign-out"],
 "signal": ["bars", "graph", "online", "reception", "status"],
 "signature": ["John Hancock", "cursive", "name", "writing"],
 "sim-card": ["hard drive", "hardware", "portable", "storage", "technology", "tiny"],
 "simplybuilt": [],
 "sink": ["bathroom", "covid-19", "faucet", "kitchen", "wash"],
 "sistrix": [],
 "sitemap": ["directory", "hierarchy", "ia", "information architecture", "organization"],
 "sith": [],
 "skating": ["activity", "figure skating", "fitness", "ice", "person", "winter"],
 "sketch": ["app", "design", "interface"],
 "skiing": ["activity", "downhill", "fast", "fitness", "olympics", "outdoors", "person", "seasonal", "slalom"],
 "skiing-nordic": ["activity", "cross country", "fitness", "outdoors", "person", "seasonal"],
 "skull": ["bones", "skeleton", "x-ray", "yorick"],
 "skull-crossbones": ["Dungeons & Dragons", "alert", "bones", "d&d", "danger", "dead", "deadly", "death", "dnd", "fantasy", "halloween", "holiday", "jolly-roger", "pirate", "poison", "skeleton", "warning"],
 "skyatlas": [],
 "skype": [],
 "slack": ["anchor", "hash", "hashtag"],
 "slack-hash": ["anchor", "hash", "hashtag"],
 "slash": ["cancel", "close", "mute", "off", "stop", "x"],
 "sleigh": ["christmas", "claus", "fly", "holiday", "santa", "sled", "snow", "xmas"],
 "sliders-h": ["adjust", "settings", "sliders", "toggle"],
 "slideshare": [],
 "smile": ["approve", "emoticon", "face", "happy", "rating", "satisfied"],
 "smile-beam": ["emoticon", "face", "happy", "positive"],
 "smile-wink": ["emoticon", "face", "happy", "hint", "joke"],
 "smog": ["dragon", "fog", "haze", "pollution", "smoke", "weather"],
 "smoking": ["cancer", "cigarette", "nicotine", "smoking status", "tobacco"],
 "smoking-ban": ["ban", "cancel", "no smoking", "non-smoking"],
 "sms": ["chat", "conversation", "message", "mobile", "notification", "phone", "sms", "texting"],
 "snapchat": [],
 "snapchat-ghost": [],
 "snapchat-square": [],
 "snowboarding": ["activity", "fitness", "olympics", "outdoors", "person"],
 "snowflake": ["precipitation", "rain", "winter"],
 "snowman": ["decoration", "frost", "frosty", "holiday"],
 "snowplow": ["clean up", "cold", "road", "storm", "winter"],
 "soap": ["bubbles", "clean", "covid-19", "hygiene", "wash"],
 "socks": ["business socks", "business time", "clothing", "feet", "flight of the conchords", "wednesday"],
 "solar-panel": ["clean", "eco-friendly", "energy", "green", "sun"],
 "sort": ["filter", "order"],
 "sort-alpha-down": ["alphabetical", "arrange", "filter", "order", "sort-alpha-asc"],
 "sort-alpha-down-alt": ["alphabetical", "arrange", "filter", "order", "sort-alpha-asc"],
 "sort-alpha-up": ["alphabetical", "arrange", "filter", "order", "sort-alpha-desc"],
 "sort-alpha-up-alt": ["alphabetical", "arrange", "filter", "order", "sort-alpha-desc"],
 "sort-amount-down": ["arrange", "filter", "number", "order", "sort-amount-asc"],
 "sort-amount-down-alt": ["arrange", "filter", "order", "sort-amount-asc"],
 "sort-amount-up": ["arrange", "filter", "order", "sort-amount-desc"],
 "sort-amount-up-alt": ["arrange", "filter", "order", "sort-amount-desc"],
 "sort-down": ["arrow", "descending", "filter", "order", "sort-desc"],
 "sort-numeric-down": ["arrange", "filter", "numbers", "order", "sort-numeric-asc"],
 "sort-numeric-down-alt": ["arrange", "filter", "numbers", "order", "sort-numeric-asc"],
 "sort-numeric-up": ["arrange", "filter", "numbers", "order", "sort-numeric-desc"],
 "sort-numeric-up-alt": ["arrange", "filter", "numbers", "order", "sort-numeric-desc"],
 "sort-up": ["arrow", "ascending", "filter", "order", "sort-asc"],
 "soundcloud": [],
 "sourcetree": [],
 "spa": ["flora", "massage", "mindfulness", "plant", "wellness"],
 "space-shuttle": ["astronaut", "machine", "nasa", "rocket", "space", "transportation"],
 "speakap": [],
 "speaker-deck": [],
 "spell-check": ["dictionary", "edit", "editor", "grammar", "text"],
 "spider": ["arachnid", "bug", "charlotte", "crawl", "eight", "halloween"],
 "spinner": ["circle", "loading", "progress"],
 "splotch": ["Ink", "blob", "blotch", "glob", "stain"],
 "spotify": [],
 "spray-can": ["Paint", "aerosol", "design", "graffiti", "tag"],
 "square": ["block", "box", "shape"],
 "square-full": ["block", "box", "shape"],
 "square-root-alt": ["arithmetic", "calculus", "division", "math"],
 "squarespace": [],
 "stack-exchange": [],
 "stack-overflow": [],
 "stackpath": [],
 "stamp": ["art", "certificate", "imprint", "rubber", "seal"],
 "star": ["achievement", "award", "favorite", "important", "night", "rating", "score"],
 "star-and-crescent": ["islam", "muslim", "religion"],
 "star-half": ["achievement", "award", "rating", "score", "star-half-empty", "star-half-full"],
 "star-half-alt": ["achievement", "award", "rating", "score", "star-half-empty", "star-half-full"],
 "star-of-david": ["jewish", "judaism", "religion"],
 "star-of-life": ["doctor", "emt", "first aid", "health", "medical"],
 "staylinked": [],
 "steam": [],
 "steam-square": [],
 "steam-symbol": [],
 "step-backward": ["beginning", "first", "previous", "rewind", "start"],
 "step-forward": ["end", "last", "next"],
 "stethoscope": ["covid-19", "diagnosis", "doctor", "general practitioner", "hospital", "infirmary", "medicine", "office", "outpatient"],
 "sticker-mule": [],
 "sticky-note": ["message", "note", "paper", "reminder", "sticker"],
 "stop": ["block", "box", "square"],
 "stop-circle": ["block", "box", "circle", "square"],
 "stopwatch": ["clock", "reminder", "time"],
 "stopwatch-20": ["ABCs", "countdown", "covid-19", "happy birthday", "i will survive", "reminder", "seconds", "time", "timer"],
 "store": ["building", "buy", "purchase", "shopping"],
 "store-alt": ["building", "buy", "purchase", "shopping"],
 "store-alt-slash": ["building", "buy", "closed", "covid-19", "purchase", "shopping"],
 "store-slash": ["building", "buy", "closed", "covid-19", "purchase", "shopping"],
 "strava": [],
 "stream": ["flow", "list", "timeline"],
 "street-view": ["directions", "location", "map", "navigation"],
 "strikethrough": ["cancel", "edit", "font", "format", "text", "type"],
 "stripe": [],
 "stripe-s": [],
 "stroopwafel": ["caramel", "cookie", "dessert", "sweets", "waffle"],
 "studiovinari": [],
 "stumbleupon": [],
 "stumbleupon-circle": [],
 "subscript": ["edit", "font", "format", "text", "type"],
 "subway": ["machine", "railway", "train", "transportation", "vehicle"],
 "suitcase": ["baggage", "luggage", "move", "suitcase", "travel", "trip"],
 "suitcase-rolling": ["baggage", "luggage", "move", "suitcase", "travel", "trip"],
 "sun": ["brighten", "contrast", "day", "lighter", "sol", "solar", "star", "weather"],
 "superpowers": [],
 "superscript": ["edit", "exponential", "font", "format", "text", "type"],
 "supple": [],
 "surprise": ["emoticon", "face", "shocked"],
 "suse": ["linux", "operating system", "os"],
 "swatchbook": ["Pantone", "color", "design", "hue", "palette"],
 "swift": [],
 "swimmer": ["athlete", "head", "man", "olympics", "person", "pool", "water"],
 "swimming-pool": ["ladder", "recreation", "swim", "water"],
 "symfony": [],
 "synagogue": ["building", "jewish", "judaism", "religion", "star of david", "temple"],
 "sync": ["exchange", "refresh", "reload", "rotate", "swap"],
 "sync-alt": ["exchange", "refresh", "reload", "rotate", "swap"],
 "syringe": ["covid-19", "doctor", "immunizations", "medical", "needle"],
 "table": ["data", "excel", "spreadsheet"],
 "table-tennis": ["ball", "paddle", "ping pong"],
 "tablet": ["apple", "device", "ipad", "kindle", "screen"],
 "tablet-alt": ["apple", "device", "ipad", "kindle", "screen"],
 "tablets": ["drugs", "medicine", "pills", "prescription"],
 "tachometer-alt": ["dashboard", "fast", "odometer", "speed", "speedometer"],
 "tag": ["discount", "label", "price", "shopping"],
 "tags": ["discount", "label", "price", "shopping"],
 "tape": ["design", "package", "sticky"],
 "tasks": ["checklist", "downloading", "downloads", "loading", "progress", "project management", "settings", "to do"],
 "taxi": ["cab", "cabbie", "car", "car service", "lyft", "machine", "transportation", "travel", "uber", "vehicle"],
 "teamspeak": [],
 "teeth": ["bite", "dental", "dentist", "gums", "mouth", "smile", "tooth"],
 "teeth-open": ["dental", "dentist", "gums bite", "mouth", "smile", "tooth"],
 "telegram": [],
 "telegram-plane": [],
 "temperature-high": ["cook", "covid-19", "mercury", "summer", "thermometer", "warm"],
 "temperature-low": ["cold", "cool", "covid-19", "mercury", "thermometer", "winter"],
 "tencent-weibo": [],
 "tenge": ["currency", "kazakhstan", "money", "price"],
 "terminal": ["code", "command", "console", "development", "prompt"],
 "text-height": ["edit", "font", "format", "text", "type"],
 "text-width": ["edit", "font", "format", "text", "type"],
 "th": ["blocks", "boxes", "grid", "squares"],
 "th-large": ["blocks", "boxes", "grid", "squares"],
 "th-list": ["checklist", "completed", "done", "finished", "ol", "todo", "ul"],
 "the-red-yeti": [],
 "theater-masks": ["comedy", "perform", "theatre", "tragedy"],
 "themeco": [],
 "themeisle": [],
 "thermometer": ["covid-19", "mercury", "status", "temperature"],
 "thermometer-empty": ["cold", "mercury", "status", "temperature"],
 "thermometer-full": ["fever", "hot", "mercury", "status", "temperature"],
 "thermometer-half": ["mercury", "status", "temperature"],
 "thermometer-quarter": ["mercury", "status", "temperature"],
 "thermometer-three-quarters": ["mercury", "status", "temperature"],
 "think-peaks": [],
 "thumbs-down": ["disagree", "disapprove", "dislike", "hand", "social", "thumbs-o-down"],
 "thumbs-up": ["agree", "approve", "favorite", "hand", "like", "ok", "okay", "social", "success", "thumbs-o-up", "yes", "you got it dude"],
 "thumbtack": ["coordinates", "location", "marker", "pin", "thumb-tack"],
 "ticket-alt": ["movie", "pass", "support", "ticket"],
 "tiktok": [],
 "times": ["close", "cross", "error", "exit", "incorrect", "notice", "notification", "notify", "problem", "wrong", "x"],
 "times-circle": ["close", "cross", "exit", "incorrect", "notice", "notification", "notify", "problem", "wrong", "x"],
 "tint": ["color", "drop", "droplet", "raindrop", "waterdrop"],
 "tint-slash": ["color", "drop", "droplet", "raindrop", "waterdrop"],
 "tired": ["angry", "emoticon", "face", "grumpy", "upset"],
 "toggle-off": ["switch"],
 "toggle-on": ["switch"],
 "toilet": ["bathroom", "flush", "john", "loo", "pee", "plumbing", "poop", "porcelain", "potty", "restroom", "throne", "washroom", "waste", "wc"],
 "toilet-paper": ["bathroom", "covid-19", "halloween", "holiday", "lavatory", "prank", "restroom", "roll"],
 "toilet-paper-slash": ["bathroom", "covid-19", "halloween", "holiday", "lavatory", "leaves", "prank", "restroom", "roll", "trouble", "ut oh"],
 "toolbox": ["admin", "container", "fix", "repair", "settings", "tools"],
 "tools": ["admin", "fix", "repair", "screwdriver", "settings", "tools", "wrench"],
 "tooth": ["bicuspid", "dental", "dentist", "molar", "mouth", "teeth"],
 "torah": ["book", "jewish", "judaism", "religion", "scroll"],
 "torii-gate": ["building", "shintoism"],
 "tractor": ["agriculture", "farm", "vehicle"],
 "trade-federation": [],
 "trademark": ["copyright", "register", "symbol"],
 "traffic-light": ["direction", "road", "signal", "travel"],
 "trailer": ["carry", "haul", "moving", "travel"],
 "train": ["bullet", "commute", "locomotive", "railway", "subway"],
 "tram": ["crossing", "machine", "mountains", "seasonal", "transportation"],
 "transgender": ["intersex"],
 "transgender-alt": ["intersex"],
 "trash": ["delete", "garbage", "hide", "remove"],
 "trash-alt": ["delete", "garbage", "hide", "remove", "trash-o"],
 "trash-restore": ["back", "control z", "oops", "undo"],
 "trash-restore-alt": ["back", "control z", "oops", "undo"],
 "tree": ["bark", "fall", "flora", "forest", "nature", "plant", "seasonal"],
 "trello": ["atlassian"],
 "tripadvisor": [],
 "trophy": ["achievement", "award", "cup", "game", "winner"],
 "truck": ["cargo", "delivery", "shipping", "vehicle"],
 "truck-loading": ["box", "cargo", "delivery", "inventory", "moving", "rental", "vehicle"],
 "truck-monster": ["offroad", "vehicle", "wheel"],
 "truck-moving": ["cargo", "inventory", "rental", "vehicle"],
 "truck-pickup": ["cargo", "vehicle"],
 "tshirt": ["clothing", "fashion", "garment", "shirt"],
 "tty": ["communication", "deaf", "telephone", "teletypewriter", "text"],
 "tumblr": [],
 "tumblr-square": [],
 "tv": ["computer", "display", "monitor", "television"],
 "twitch": [],
 "twitter": ["social network", "tweet"],
 "twitter-square": ["social network", "tweet"],
 "typo3": [],
 "uber": [],
 "ubuntu": ["linux", "operating system", "os"],
 "uikit": [],
 "umbraco": [],
 "umbrella": ["protection", "rain", "storm", "wet"],
 "umbrella-beach": ["protection", "recreation", "sand", "shade", "summer", "sun"],
 "underline": ["edit", "emphasis", "format", "text", "writing"],
 "undo": ["back", "control z", "exchange", "oops", "return", "rotate", "swap"],
 "undo-alt": ["back", "control z", "exchange", "oops", "return", "swap"],
 "uniregistry": [],
 "unity": [],
 "universal-access": ["accessibility", "hearing", "person", "seeing", "visual impairment"],
 "university": ["bank", "building", "college", "higher education - students", "institution"],
 "unlink": ["attachment", "chain", "chain-broken", "remove"],
 "unlock": ["admin", "lock", "password", "private", "protect"],
 "unlock-alt": ["admin", "lock", "password", "private", "protect"],
 "unsplash": [],
 "untappd": [],
 "upload": ["hard drive", "import", "publish"],
 "ups": ["United Parcel Service", "package", "shipping"],
 "usb": [],
 "user": ["account", "avatar", "head", "human", "man", "person", "profile"],
 "user-alt": ["account", "avatar", "head", "human", "man", "person", "profile"],
 "user-alt-slash": ["account", "avatar", "head", "human", "man", "person", "profile"],
 "user-astronaut": ["avatar", "clothing", "cosmonaut", "nasa", "space", "suit"],
 "user-check": ["accept", "check", "person", "verified"],
 "user-circle": ["account", "avatar", "head", "human", "man", "person", "profile"],
 "user-clock": ["alert", "person", "remind", "time"],
 "user-cog": ["admin", "cog", "person", "settings"],
 "user-edit": ["edit", "pen", "pencil", "person", "update", "write"],
 "user-friends": ["group", "people", "person", "team", "users"],
 "user-graduate": ["cap", "clothing", "commencement", "gown", "graduation", "person", "student"],
 "user-injured": ["cast", "injury", "ouch", "patient", "person", "sling"],
 "user-lock": ["admin", "lock", "person", "private", "unlock"],
 "user-md": ["covid-19", "job", "medical", "nurse", "occupation", "physician", "profile", "surgeon"],
 "user-minus": ["delete", "negative", "remove"],
 "user-ninja": ["assassin", "avatar", "dangerous", "deadly", "sneaky"],
 "user-nurse": ["covid-19", "doctor", "midwife", "practitioner", "surgeon"],
 "user-plus": ["add", "avatar", "positive", "sign up", "signup", "team"],
 "user-secret": ["clothing", "coat", "hat", "incognito", "person", "privacy", "spy", "whisper"],
 "user-shield": ["admin", "person", "private", "protect", "safe"],
 "user-slash": ["ban", "delete", "remove"],
 "user-tag": ["avatar", "discount", "label", "person", "role", "special"],
 "user-tie": ["avatar", "business", "clothing", "formal", "professional", "suit"],
 "user-times": ["archive", "delete", "remove", "x"],
 "users": ["friends", "group", "people", "persons", "profiles", "team"],
 "users-cog": ["admin", "cog", "group", "person", "settings", "team"],
 "users-slash": ["disband", "friends", "group", "people", "persons", "profiles", "separate", "team", "ungroup"],
 "usps": ["american", "package", "shipping", "usa"],
 "ussunnah": [],
 "utensil-spoon": ["cutlery", "dining", "scoop", "silverware", "spoon"],
 "utensils": ["cutlery", "dining", "dinner", "eat", "food", "fork", "knife", "restaurant"],
 "vaadin": [],
 "vector-square": ["anchors", "lines", "object", "render", "shape"],
 "venus": ["female"],
 "venus-double": ["female"],
 "venus-mars": ["Gender"],
 "viacoin": [],
 "viadeo": [],
 "viadeo-square": [],
 "vial": ["experiment", "lab", "sample", "science", "test", "test tube"],
 "vials": ["experiment", "lab", "sample", "science", "test", "test tube"],
 "viber": [],
 "video": ["camera", "film", "movie", "record", "video-camera"],
 "video-slash": ["add", "create", "film", "new", "positive", "record", "video"],
 "vihara": ["buddhism", "buddhist", "building", "monastery"],
 "vimeo": [],
 "vimeo-square": [],
 "vimeo-v": ["vimeo"],
 "vine": [],
 "virus": ["bug", "covid-19", "flu", "health", "sick", "viral"],
 "virus-slash": ["bug", "covid-19", "cure", "eliminate", "flu", "health", "sick", "viral"],
 "viruses": ["bugs", "covid-19", "flu", "health", "multiply", "sick", "spread", "viral"],
 "vk": [],
 "vnv": [],
 "voicemail": ["answer", "inbox", "message", "phone"],
 "volleyball-ball": ["beach", "olympics", "sport"],
 "volume-down": ["audio", "lower", "music", "quieter", "sound", "speaker"],
 "volume-mute": ["audio", "music", "quiet", "sound", "speaker"],
 "volume-off": ["audio", "ban", "music", "mute", "quiet", "silent", "sound"],
 "volume-up": ["audio", "higher", "louder", "music", "sound", "speaker"],
 "vote-yea": ["accept", "cast", "election", "politics", "positive", "yes"],
 "vr-cardboard": ["3d", "augment", "google", "reality", "virtual"],
 "vuejs": [],
 "walking": ["exercise", "health", "pedometer", "person", "steps"],
 "wallet": ["billfold", "cash", "currency", "money"],
 "warehouse": ["building", "capacity", "garage", "inventory", "storage"],
 "water": ["lake", "liquid", "ocean", "sea", "swim", "wet"],
 "wave-square": ["frequency", "pulse", "signal"],
 "waze": [],
 "weebly": [],
 "weibo": [],
 "weight": ["health", "measurement", "scale", "weight"],
 "weight-hanging": ["anvil", "heavy", "measurement"],
 "weixin": [],
 "whatsapp": [],
 "whatsapp-square": [],
 "wheelchair": ["accessible", "handicap", "person"],
 "whmcs": [],
 "wifi": ["connection", "hotspot", "internet", "network", "wireless"],
 "wikipedia-w": [],
 "wind": ["air", "blow", "breeze", "fall", "seasonal", "weather"],
 "window-close": ["browser", "cancel", "computer", "development"],
 "window-maximize": ["browser", "computer", "development", "expand"],
 "window-minimize": ["browser", "collapse", "computer", "development"],
 "window-restore": ["browser", "computer", "development"],
 "windows": ["microsoft", "operating system", "os"],
 "wine-bottle": ["alcohol", "beverage", "cabernet", "drink", "glass", "grapes", "merlot", "sauvignon"],
 "wine-glass": ["alcohol", "beverage", "cabernet", "drink", "grapes", "merlot", "sauvignon"],
 "wine-glass-alt": ["alcohol", "beverage", "cabernet", "drink", "grapes", "merlot", "sauvignon"],
 "wix": [],
 "wizards-of-the-coast": ["Dungeons & Dragons", "d&d", "dnd", "fantasy", "game", "gaming", "tabletop"],
 "wolf-pack-battalion": [],
 "won-sign": ["currency", "krw", "money"],
 "wordpress": [],
 "wordpress-simple": [],
 "wpbeginner": [],
 "wpexplorer": [],
 "wpforms": [],
 "wpressr": ["rendact"],
 "wrench": ["construction", "fix", "mechanic", "plumbing", "settings", "spanner", "tool", "update"],
 "x-ray": ["health", "medical", "radiological images", "radiology", "skeleton"],
 "xbox": [],
 "xing": [],
 "xing-square": [],
 "y-combinator": [],
 "yahoo": [],
 "yammer": [],
 "yandex": [],
 "yandex-international": [],
 "yarn": [],
 "yelp": [],
 "yen-sign": ["currency", "jpy", "money"],
 "yin-yang": ["daoism", "opposites", "taoism"],
 "yoast": [],
 "youtube": ["film", "video", "youtube-play", "youtube-square"],
 "youtube-square": [],
 "zhihu": [],
 "wolai": [] }