😀,luchierxiaodelian,daxiao，kaixin，gaoxing，yukuai
😃,zuibazhangkai，luchierxiaodelian,daxiao，kaixin，gaoxing，yukuai
😄,mizheyanjing，luchierxiao,daxiao，kaixin，gaoxing，yukuai
😁,yandaixiaoyi，luchierxiaodelian,daxiao，kaixin，gaoxing，yukuai
😆,jinbishuangyandaxiao,daxiao，kaixin，gaoxing，yukuai
😅,mizheyanjingluchierxiao，etouyouyidihan,daxiao，kaixin，gaoxing，dihan，yukuai
😂,xiaochuyanlei,daxiao，kaixin，gaoxing，xiaoku，kuxiao，xiaolei，yukuai
🤣,xiaodedagun,daxiao，kaixin，gaoxing，xiaoku，kuxiao，xiaolei，yukuai
🙂,weilouxiaoyi,weixiao，jiaxiao，lengxiao
🙃,shangxiadiandaodexiaolian,weixiao，jiaxiao，lengxiao
😉,zhayanxiao,weixiao，dongni，OK
😊,miyanweixiao,kaixin，gaoxing，buhaoyisi，lianhong，yukuai
😇,toudingguanghuandexiaolian,kaixin，gaoxing，guanghuan，tianshi，yukuai
🥰,aixinhuanraodeweixiaolian,kaixin，gaoxing，aixin，yukuai
😍,yanjingweixinxing，weixiaodelian,kaixin，gaoxing，aixin，yukuai
🤩,yanmaoxingxingdexiaolian,kaixin，gaoxing，xingxing，jinxing，yukuai
😘,feiwendebiaoqing,xihuan，ai，qinqin
😗,qinwendelian,xihuan，ai，qinqin
😚,bizheyanjingqinwendelian,xihuan，ai，qinqin
😙,mizheyanjingqinwendelian,xihuan，ai，qinqin
☺️,manshixiaoyi,kaixin，gaoxing，buhaoyisi，lianhong
😌,shiran,dongle
😋,tianzhezuichun，miyanweixiao,kaixin，gaoxing，tiaopi，yukuai
😛,yukuaiditushetou,kaixin，gaoxing，tiaopi，yukuai
😜,tushetouzhayanjing,kaixin，gaoxing，tiaopi，yukuai
🤪,shagualian,tiaopi，tushetou，daxiaoyan
😝,tiaopitushe，shuangyanjinbi,tiaopi，tushetou，biyan
🤑,zuituchaopiaodelian,qian，chaopiao
🤗,yongbaoshoushidehuanlexiaolian,kaixin，gaoxing，yukuai
🤭,shouwuzhuzuifanhongdelian,wuzui，bizui，shousheng
🤫,xushenglian,bizui，xiaosheng，shousheng，anjing
🤔,shensidelian,sikao，siliang，sisuo，kaolv
🤐,zuibalashanglaliandelian,bizui，bushuohua，shousheng，anjing
🤨,meimaoshangtiaodelian,tiaomei
😐,pingjingdebiaoqing,lengjing，daizhi，mianbujiangying
😑,mianwubiaoqing,lengjing，daizhi，mianbujiangying
😶,meiyouzuibadelian,daizhi，fadai
😏,deyidixiao,yangyangzide
😒,bukaixindebiaoqing,bishi
🙄,yanjingzhuandongdelian,fanbaiyan
😬,ziyaliezui,guilian，mianmuzhengning
🤥,sahuanglian,changbizi，pinuocao
😔,ditouyoushangdelian,nanguo，beishang，bukaixin，jiuyaokule
😪,kunjuandelian,kunle，shuizhao
🤤,liukoushuidelian,zuichan
😴,kunjuandelian,kunle，shuizhao
😷,shengbingdebiaoqing,daikouzhao，ganmao，shengbing
🤒,zuihanwendujidelian,shengbing，liangtiwen，fashao
🤕,toushangchanmanbengdaidelian,shoushang，shabu
🤢,outulian,tule，exin
🤮,outulian,tule，exin
🤧,xingbitilian,shengbing，ganmao，xingbiti
🥵,faredelian,shengbing，fashao
🥶,binglengdelian,bingliang，dishao，quanshenfaleng
🥴,weizuidelian,niuqudelian，weixun，zuixunxun，zuile
😵,touyunmuxuan,XX，yunxuan
🤯,naozibaozha,naodaibaozha，zhale
🤠,niuzailian,niuzaimao，daimaozi
🥳,paiduilian,kaixin，gaoxing，yukuai，hongpa
😎,daitaiyangjingdexiaolian,mojing，weixiao，kaixin，yukuai，gaoxing
🤓,daiyanjingdexiaolian,shudaizi，xueba
🧐,daizhedanpianyanjingdelian,xuejiu，daoshi，jiaoshou
😕,kunhuodelian,yihuo
😟,danyoudelian,youlv，danxin
🙁,nanguodelian,shangxin，nanguo，beishang
☹️,nanguodelian,shangxin，nanguo，beishang
😮,zhangzuijingyadelian,o，o，o，chijing
😯,zhangzuijingyadelian,o，o，o，chijing
😲,chijingdelian,jingya，yayi
😳,zhengdashuangyandelian,jingya，yayi，chijing，buganxiangxin，zhenjing，buhaoyisi
🥺,kenqiulian,kelian，yanhanleihua，kuaiyaokule
😦,zuibazhangkaidelian,fadai，daizhi，mianwubiaoqing
😧,kunaodelian,fadai，daizhi，mianwubiaoqing
😨,haipadebiaoqing,etoufaqing
😰,zuibazhangkai，maolenghan,etoufaqing
😥,shiwangdihandelian,shiran，buyue，nanguo，beishang，shangxin
😢,kuqidelian,buyue，nanguo，beishang，shangxin，kulian
😭,dakudelian,buyue，nanguo，beishang，shangxin，kulian
😱,kongjujianjiaodelian,haipa，xiaren，kongbu，etoufaqing
😖,kunhuodelian,buyue，nanguo
😣,rennaidelian,buyue，nanguo
😞,shiwangdelian,buyue，nanguo
😓,chulenghandelian,dihan，chuhan
😩,pijuandelian,zhuakuang，pilao，pifa，laoleiguodu
😫,zhuakuangdebiaoqing,pijuan，pilao，pifa，laoleiguodu
🥱,dahaqiandelian,dahaqi，kunjuan，kunle，xiangshuijiao
😤,bikongpenqideshengqilian,qifen，nuqichongtian
😡,qidefahongdelian,shengqi，qifen，fanu，buyue，nuqichongtian，zhanghonglelian
😠,shengqidelian,qifen，fanu，buyue
🤬,qidefahongdezanghualian,shengqi，qifen，fanu，buyue，nuqichongtian，zhanghonglelian
😈,changjiaodexiaoemozaixiao,
👿,changjiaodexiaoemozaishengqi,
💀,tougu,kulou，tougaigu
☠️,kuloutouhejiaochafangzhidegutou,tougu，tougaigu
💩,pianpian,baba，fenbian，dabian，shi
🤡,xiaochoulian,
👹,guaiwu,yaoguai
👺,yaoguai,guaiwu
👻,youling,guihun，xiaojingling
👽,waixingren,UFO
👾,yixingguaishou,xiangsu，guaiwu
🤖,jiqirenlian,
😺,kaixindemaolian,gaoxing，yukuai，daxiao
😸,luchierxiaodemaolian,gaoxing，yukuai，kaixin，daxiao
😹,xiaozhongdaileidemaolian,daxiao，kaixin，gaoxing，xiaoku，kuxiao，xiaolei，yukuai
😻,yanjingweixinxing，weixiaodemaolian,xihuan，ai
😼,deyidixiaodemaolian,yangyangzide
😽,qinwendemaolian,jiewen，xihuan，ai，qinqin
🙀,kongjujianjiaodemaolian,haipa，xiaren，kongbu
😿,kuqidemaolian,buyue，nanguo，beishang，shangxin，kulian
😾,juezuimaolian,juezui，fenfenbuping
💋,chunyin,qinwen，zuichun，hongchun，kouhongyin
👋,huishoubiaozhi,shoushi，huishou，zaijian，baibai
🤚,shoubei,shoushi，shenshou
🖐,shouzhizhangkaibingjuqideshou,wuzhi，shouzhang，bu
✋,juqideshou,wuzhi，shouzhang，jizhang，bu
🖖,yizhishou，wuzhizaizhongzhihewumingzhizhijianfenkai,shouzhang
👌,OKshoushi,haode，meiwenti
🤏,nieshou,niezhu，yidiudiu，yidian
✌,hepingshoushifuhao,PEACE，jiandao
🤞,shouzhijiaocha,
🤟,ainishoushi,
🤘,yaogunshoushi,
🤙,dadianhuageiwoshoushi,daCall
👈,fanshoushizhixiangzuozhideshou,
👉,fanshoushizhixiangyouzhideshou,
👆,fanshoushizhixiangshangzhideshou,
🖕,fanshouzhongzhixiangshangshenchu,
👇,fanshoushizhixiangxiazhideshou,
☝,shizhixiangshangzhideshou,
👍,damuzhichaoshang,bang，lihai，jiayou
👎,damuzhichaoxia,shuai，
✊,juqidequantou,woquan，shitou
👊,wojindequantou,woquan，chuquan，shitou
🤛,zuoxiangquan,chuquan
🤜,youxiangquan,chuquan
👏,paishou,guzhang
🙌,yangshouhuanhu,jushou
👐,zhangkaideshuangshou,
🤲,shuangshoushouzhangxiangshang,
🤝,woshou,nihao
🙏,shuangshouheshi,qidao，baituo，kenqiu，zhixie，hezhang，ganxie
✍,zhibishuxie,xiezi，suibi，biji
💅,tuzhijiayou,meijia
🤳,zipai,
💪,guqideertouji,qiangzhuang，xiujirou，liliang
🦾,jixieshoubi,jiqishoubi
🦿,jixietui,jiqitui
🦵,tui,meitui
🦶,jiao,jiaodiban
👂,erduo,
🦻,daizhezhutingqideerduo,
👃,bizi,
🧠,danao,
🦷,yachi,zhichi
🦴,gutou,guge
👀,yanjing,shuangyan，kankan
👁,yanjing,yanzhu，tongkong，shiwangmo，hongmo
👅,shetou,tushetou
👄,hongsezuichun,zuiba，shuangchun
👶,yinger,baobao，baobei，youer，nannan，weichengnianren
🧒,ertong,xiaopengyou，weichengnianren
👦,nanhai,xiaopengyou，ertong，weichengnianren
👧,nvhai,xiaopengyou，ertong，weichengnianren
🧑,chengren,chengnianren
👱,jinfaderen,chengren，chengnianren
👨,nanren,chengren，chengnianren，nanzi
🧔,youhuxuderen,youhuzideren，chengren，chengnianren，nanzi，nanren
👨‍🦰,hongfananzi,hongtoufa，chengren，chengnianren，nanren
👨‍🦱,juanfananzi,chengren，chengnianren，nanren
👨‍🦳,baifananzi,chengren，chengnianren，nanren
👨‍🦲,guangtounanzi,chengren，chengnianren，nanren
👩,nvren,nvzi
👩‍🦰,hongfanvzi,nvren，chengren，chengnianren
🧑‍🦰,hongfaderen,
👩‍🦱,juanfanvzi,nvren，chengren，chengnianren
🧑‍🦱,juanfaderen,
👩‍🦳,baifanvzi,nvren，chengren，chengnianren
🧑‍🦳,baifaderen,
👩‍🦲,guangtounvzi,nvren，chengren，chengnianren
🧑‍🦲,guangtouderen,
👱‍♀️,jinfanvzi,nvhai，nvren
👱‍♂️,jinfananzi,chengren，chengnianren，nanren
🧓,laoren,laonianren
👴,laoyeye,laoren
👵,laonainai,laoren
🙍,zhoumeideren,chengren，chengnianren
🙍‍♂️,zhoumeidenanren,nanzi，chengren，chengnianren
🙍‍♀️,zhoumeidenvren,nvzi，chengren，chengnianren
🙎,juezuideren,chengren，chengnianren
🙎‍♂️,juezuidenanren,nanzi，chengren，chengnianren
🙎‍♀️,juezuidenvren,nvzi，chengren，chengnianren
🙅,zuochubushoushideren,chengren，chengnianren
🙅‍♂️,zuochubushoushidenanren,nanzi，chengren，chengnianren
🙅‍♀️,zuochubushoushidenvren,nvzi，chengren，chengnianren
🙆,zuochuOKshoushideren,chengren，chengnianren
🙆‍♂️,zuochuOKshoushidenanren,nanzi，chengren，chengnianren
🙆‍♀️,zuochuOKshoushidenvren,nvzi，chengren，chengnianren
💁,fuwutaigongzuorenyuan,chengren，chengnianren
💁‍♂️,fuwutainangongzuorenyuan,nanzi，chengren，chengnianren
💁‍♀️,fuwutainvgongzuorenyuan,nvzi，chengren，chengnianren
🙋,juqiyizhishouderen,chengren，chengnianren，jushou
🙋‍♂️,juqiyizhishoudenanren,nanzi，chengren，chengnianren，jushou
🙋‍♀️,juqiyizhishoudenvren,nvzi，chengren，chengnianren，jushou
🧏,shicongderen,chengren，chengnianren
🧏‍♂️,shicongdenanren,nanzi，chengren，chengnianren
🧏‍♀️,shicongdenvren,nvzi，chengren，chengnianren
🙇,jugongderen,chengren，chengnianren，fudi，guizhe
🙇‍♂️,jugongdenanren,nanzi，chengren，chengnianren，fudi，guizhe
🙇‍♀️,jugongdenvren,nvzi，chengren，chengnianren，fudi，guizhe
🤦,shouzhangwulianderen,chengren，chengnianren
🤦‍♂️,shouzhangwuliandenanren,nanzi，chengren，chengnianren
🤦‍♀️,shouzhangwuliandenvren,nvzi，chengren，chengnianren
🤷,songjianderen,chengren，chengnianren
🤷‍♂️,songjiandenanren,nanzi，chengren，chengnianren
🤷‍♀️,songjiandenvren,nvzi，chengren，chengnianren
🧑‍⚕️,yihurenyuan,yisheng，hushi，huli
👨‍⚕️,nanyihurenyuan,yisheng，hushi，huli
👩‍⚕️,nvyihurenyuan,yisheng，hushi，huli
🧑‍🎓,xuesheng,biye，xueshi，shuoshi，boshi
👨‍🎓,nanxuesheng,biye，xueshi，shuoshi，boshi
👩‍🎓,nvxuesheng,biye，xueshi，shuoshi，boshi
🧑‍🏫,jiaoshi,laoshi，jiaoshou，jiangshi
👨‍🏫,nanjiaoshi,laoshi，jiaoshou，jiangshi
👩‍🏫,nvjiaoshi,laoshi，jiaoshou，jiangshi
🧑‍⚖️,faguan,shenpanyuan，shenpanzhang
👨‍⚖️,nanfaguan,shenpanyuan，shenpanzhang
👩‍⚖️,nvfaguan,shenpanyuan，shenpanzhang
🧑‍🌾,nongmin,nongfu，zhongdi，zhongtian，zhongcai
👨‍🌾,nannongmin,nongfu，zhongdi，zhongtian，zhongcai
👩‍🌾,nvnongmin,nongfu，zhongdi，zhongtian，zhongcai
🧑‍🍳,chushi,huofu
👨‍🍳,nanchushi,huofu
👩‍🍳,nvchushi,huofu
🧑‍🔧,jigong,gongren
👨‍🔧,nanjigong,gongren
👩‍🔧,nvjigong,gongren
🧑‍🏭,gongchanggongren,
👨‍🏭,nangongchanggongren,
👩‍🏭,nvgongchanggongren,
🧑‍💼,bangongshizhiyuan,bailing
👨‍💼,nanbangongshizhiyuan,bailing
👩‍💼,nvbangongshizhiyuan,bailing
🧑‍🔬,kexuejia,keyanrenyuan，yanjiuyuan
👨‍🔬,nankexuejia,keyanrenyuan，yanjiuyuan
👩‍🔬,nvkexuejia,keyanrenyuan，yanjiuyuan
🧑‍💻,ruanjiangongchengshi,kaifa，ceshi，yanfa，manong，shejishi
👨‍💻,nanruanjiangongchengshi,kaifa，ceshi，yanfa，manong，shejishi
👩‍💻,nvruanjiangongchengshi,kaifa，ceshi，yanfa，manong，shejishi
🧑‍🎤,geshou,yiren
👨‍🎤,nangeshou,yiren
👩‍🎤,nvgeshou,yiren
🧑‍🎨,yishujia,huajia
👨‍🎨,nanyishujia,nanhuajia
👩‍🎨,nvyishujia,nvhuajia
🧑‍✈️,feixingyuan,jizhang
👨‍✈️,nanfeixingyuan,nanjizhang
👩‍✈️,nvfeixingyuan,nvjizhang
🧑‍🚀,yuhangyuan,taikongren
👨‍🚀,nanyuhangyuan,nantaikongren
👩‍🚀,nvyuhangyuan,nvtaikongren
🧑‍🚒,xiaofangyuan,xiaofangduiyuan
👨‍🚒,nanxiaofangyuan,nanxiaofangduiyuan
👩‍🚒,nvxiaofangyuan,nvxiaofangduiyuan
👮,jingcha,jingguan
👮‍♂️,nanjingcha,nanjingguan
👮‍♀️,nvjingcha,nvjingguan
🕵,zhentan,
🕵️‍♂️,nanzhentan,
🕵️‍♀️,nvzhentan,
💂,weibing,weishi
💂‍♂️,nanweibing,nanweishi
💂‍♀️,nvweibing,nvweishi
👷,jianzhugongren,gongren
👷‍♂️,nanjianzhugongren,nangongren
👷‍♀️,nvjianzhugongren,nvgongren
🤴,wangzi,
👸,gongzhu,
👳,baotoujinderen,
👳‍♂️,baotoujindenanren,
👳‍♀️,baotoujindenvren,
👲,daizhezhongguomaodenanren,
🧕,daizhetoujindenvren,
🤵,chuanyanweifudenanren,xinlang，wanlifu
👰,chuanhunshadenvren,xinniang
🤰,yunfu,huaiyundenvren
🤱,buru,weinaidenvren
👼,tianshibaobao,youer，yinger，baobei，nannan，weichengnianren
🎅,shengdanlaoren,
🤶,shengdanfuren,
🦸,chaojiyingxiong,chaoren
🦸‍♂️,nanchaojiyingxiong,nanchaoren
🦸‍♀️,nvchaojiyingxiong,nvchaoren
🦹,chaojidafanpai,
🦹‍♂️,chaojinanfanpai,
🦹‍♀️,chaojinvfanpai,
🧙,mofashi,wushi
🧙‍♂️,nanwu,nanmofashi
🧙‍♀️,nvwu,nvmofashi
🧚,xiaoxianzi,jingling
🧚‍♂️,nanxianzi,jingling
🧚‍♀️,nvxianzi,jingling
🧛,xixuegui,mogui
🧛‍♂️,nanxixuegui,mogui
🧛‍♀️,nvxixuegui,mogui
🧜,renyu,meirenyu
🧜‍♂️,nanrenyu,meirenyu
🧜‍♀️,meirenyu,meirenyu
🧝,jingling,
🧝‍♂️,nvjingling,
🧝‍♀️,nanjingling,
🧞,yaoguai,yaojing
🧞‍♂️,nanyaoguai,nanyaojing
🧞‍♀️,nvyaoguai,nvyaojing
🧟,jiangshi,sangshi
🧟‍♂️,nanjiangshi,nansangshi
🧟‍♀️,nvjiangshi,nvsangshi
💆,zuotoubuanmodiren,
💆‍♂️,zuotoubuanmodinanren,
💆‍♀️,zuotoubuanmodinvren,
💇,lifaderen,
💇‍♂️,lifadenanren,
💇‍♀️,lifadenvren,
🚶,xingren,luren
🚶‍♂️,nanxingren,nanluren
🚶‍♀️,nvxingren,nvluren
🧍,zhanzhederen,zhanlideren
🧍‍♂️,zhanzhedenanren,zhanlidenanren
🧍‍♀️,zhanzhedenvren,zhanlidenvren
🧎,guizhederen,
🧎‍♂️,guizhedenanren,
🧎‍♀️,guizhedenvren,
🧑‍🦯,nazheshouzhangderen,
👨‍🦯,nazheshouzhangdenanren,
👩‍🦯,nazheshouzhangdenvren,
🧑‍🦼,zuozaidiandonglunyishangderen,
👨‍🦼,zuozaidiandonglunyishangdenanren,
👩‍🦼,zuozaidiandonglunyishangdenvren,
🧑‍🦽,zuozaishoudonglunyishangderen,
👨‍🦽,zuozaishoudonglunyishangdenanren,
👩‍🦽,zuozaishoudonglunyishangdenvren,
🏃,paobuzhe,
🏃‍♂️,nanpaobuzhe,
🏃‍♀️,nvpaobuzhe,
💃,tiaowudenvren,nvwuzhe
🕺,tiaowudenanren,nanwuzhe
🕴,fuzaidimianshangdexizhuangnan,piaofu，xizhuang
👯,daizhetuzierduotiaowuderen,tunvlang
👯‍♂️,tiaowudetuzixiansheng,tunvlang
👯‍♀️,tiaowudetunvlang,tunvlang
🧖,zhengsangnaderen,
🧖‍♂️,zhengsangnadenanren,
🧖‍♀️,zhengsangnadenvren,
🧘,lianhuazuoderen,lianhuazuo，pantuizuo，dazuo，yujia，mingxiang
🧘‍♂️,lianhuazuodenanren,lianhuazuo，pantuizuo，dazuo，yujia，mingxiang
🧘‍♀️,lianhuazuodenvren,lianhuazuo，pantuizuo，dazuo，yujia，mingxiang
🧑‍🤝‍🧑,qianshouderen,lashouderen
👭,lianggeqianshoudenvren,lashoudenvren
👫,qianshoudeqinglv,lashoudeqinglv
👬,lianggeqianshoudenanren,lashoudenanren
💏,zuochuqinwendongzuodelianggeren,jiewenderen
👨‍❤️‍💋‍👨,zuochuqinwendongzuodelianggenanren,
👩‍❤️‍💋‍👩,zuochuqinwendongzuodelianggenvren,
👩‍❤️‍💋‍👨,zuochuqinwendongzuodenanrenhenvren,
💑,zhongjianxianshiaixindelianggeren,
👨‍❤️‍👨,zhongjianxianshiaixindelianggenanren,
👩‍❤️‍👩,zhongjianxianshiaixindelianggenvren,
👩‍❤️‍👨,zhongjianxianshiaixindenanrenhenvren,
👪,lianggerenhexiaohai,yijiaren，yijiasankou，sankouzhijia
👨‍👩‍👦,babamamaheerziyijia,yijiaren，yijiasankou，sankouzhijia
👨‍👩‍👧,babamamahenveryijia,yijiaren，yijiasankou，sankouzhijia
👨‍👩‍👧‍👦,babamamaheernvyijia,yijiaren，yijiasikou，sikouzhijia
👨‍👩‍👦‍👦,babamamahelianggeerziyijia,yijiaren，yijiasikou，sikouzhijia
👨‍👩‍👧‍👧,babamamahelianggenveryijia,yijiaren，yijiasikou，sikouzhijia
👨‍👨‍👦,lianggebabaheerziyijia,yijiaren，yijiasankou，sankouzhijia
👨‍👨‍👧,lianggebabahenveryijia,yijiaren，yijiasankou，sankouzhijia
👨‍👨‍👧‍👦,lianggebabaheernvyijia,yijiaren，yijiasikou，sikouzhijia
👨‍👨‍👦‍👦,lianggebabahelianggeerziyijia,yijiaren，yijiasikou，sikouzhijia
👨‍👨‍👧‍👧,lianggebabahelianggenveryijia,yijiaren，yijiasikou，sikouzhijia
👩‍👩‍👦,lianggemamaheerziyijia,yijiaren，yijiasankou，sankouzhijia
👩‍👩‍👧,lianggemamahenveryijia,yijiaren，yijiasankou，sankouzhijia
👩‍👩‍👧‍👦,lianggemamaheernvyijia,yijiaren，yijiasikou，sikouzhijia
👩‍👩‍👦‍👦,lianggemamahelianggeerziyijia,yijiaren，yijiasikou，sikouzhijia
👩‍👩‍👧‍👧,lianggemamahelianggenveryijia,yijiaren，yijiasikou，sikouzhijia
👨‍👦,fuziyijia,yijiaren，yijialiangkou，liangkouzhijia
👨‍👦‍👦,fuqinhelianggeerziyijia,yijiaren，yijiasankou，sankouzhijia
👨‍👧,funvyijia,yijiaren，yijialiangkou，liangkouzhijia
👨‍👧‍👦,fuqinheernvyijia,yijiaren，yijiasankou，sankouzhijia
👨‍👧‍👧,fuqinhelianggenveryijia,yijiaren，yijiasankou，sankouzhijia
👩‍👦,muziyijia,yijiaren，yijialiangkou，liangkouzhijia
👩‍👦‍👦,muqinhelianggeerziyijia,yijiaren，yijiasankou，sankouzhijia
👩‍👧,munvyijia,yijiaren，yijialiangkou，liangkouzhijia
👩‍👧‍👦,muqinheernvyijia,yijiaren，yijiasankou，sankouzhijia
👩‍👧‍👧,muqinhelianggenveryijia,yijiaren，yijiasankou，sankouzhijia
🗣,jianghuazhedetoubujianying,xiaoxiang，renxiang，touxiang
👤,renwujianying,xiaoxiang，renxiang，touxiang
👥,lianggerendejianying,xiaoxiang，renxiang，touxiang
👣,jiaoyin,
🧳,xinglixiang,lvxingxiang，xiangbao、xingli，xiangzi
🌂,yusan,
☂,yusan,
🎃,nanguadenglong,
🧵,xian,
🧶,shaxian,masheng，maoyixian
👓,yanjing,
🕶,taiyangjing,mojing
🥽,humujing,fangfengjing
🥼,shiyanshiwaiyi,baisewaiyi
🦺,anquanbeixin,
👔,chenshanhelingdai,
👕,POLOshan,
👖,niuzaiku,
🧣,weijin,weibo
🧤,shoutao,
🧥,waitao,fengyi
🧦,wazi,
👗,lianyiqun,qunzi
👘,hefu,
🥻,shali,
🩱,liantiyongyi,
🩲,sanjiaoku,neiku
🩳,duanku,pingjiaoku，neiku
👙,bijini,yongyi
👚,nvshichenshan,
🧢,lanseyashemao,
🎓,biyemao,xueshimao，boshimao
👢,gaogenxue,changxue，tongxue
🥾,dengshanxie,tubuxie
💄,kouhong,chuncai，chunyou，chungao
💼,gongwenbao,
👑,wangguan,huangguan
👟,wangqiuxie,yundongxie
👞,pixie,
💍,jiezhi,zuanshijiezhi
👛,qianbao,
👝,hebao,
🩰,baleiwuxie,
🎒,shuangjianbao,beibao，shubao
🩸,xiedi,xueye，liuxue，xie
👠,hongsegaogenxie,
⛑,daibaiseshizideanquanmao,
🥿,pingdixie,danxie
👡,gaogenliangxie,
👒,daihudiejiedemaozi,zheyangmao
🎩,limao,gaomao
👜,shoutibao,shounabao
🙈,feiliwushi,houzi，bukan，kanbujian
🙉,feiliwuting,houzi，buting，tingbujian
🙊,feiliwuyan,houzi，bushuo，shuobuchukou
💥,baozha,
💫,touyunmuxuan,jinxing
💦,shuidi,handi
💨,zhenfeng,
🐵,houlian,houzi
🐒,houzi,
🦍,daxingxing,yinbei
🦧,hongmaoxingxing,
🐶,goulian,
🐕,gou,
🦮,daomangquan,gou
🐕‍🦺,fuwuquan,gou，soujiuquan
🐩,guibinquan,gou
🐺,lang,
🦊,hulilian,
🦝,huanxiong,
🐱,maolian,maomi，miaoxingren
🐈,mao,maomi，miaoxingren
🦁,shizilian,
🐯,laohulian,
🐅,laohu,
🐆,bao,liebao，jinqianbao
🐴,matou,
🐎,ma,
🦄,dujiaoshou,
🦓,banma,
🦌,lu,
🐮,niulian,
🐂,gongniu,huangniu
🐃,shuiniu,
🐄,nainiu,
🐷,zhulian,
🐖,zhu,
🐗,yezhu,
🐽,zhubi,
🐏,gongyang,
🐑,mianyang,
🐐,shanyang,
🐪,luotuo,
🐫,shuangfengtuo,luotuo
🦙,meizhoutuo,yangtuo，caonima
🦒,changjinglu,
🐘,daxiang,
🦏,xiniu,
🦛,hema,
🐭,shulian,
🐁,xiaobaishu,laoshu，haozi
🐀,laoshu,haozi
🐹,cangshulian,
🐰,tulian,
🐇,tuzi,xiaobaitu
🐿,songshu,
🦔,ciwei,
🦇,bianfu,
🐻,xionglian,gouxiong，huixiong
🐨,kaolalian,shudaixiong
🐼,xiongmaolian,guobao
🦥,shulan,
🦦,shuita,
🦨,chouyou,
🦘,daishu,
🦡,huan,
🐾,zhangyin,
🦃,huoji,
🐔,ji,
🐓,gongji,
🐣,fuhuaxiaoji,
🐤,xiaojibaobao,
🐥,zhanzhedexiaoji,
🐦,niao,
🐧,qie,
🕊,gezi,
🦅,ying,baitouying
🦆,yazi,yeya
🦢,tiane,
🦉,maotouying,
🦩,huolieniao,
🦚,kongque,
🦜,yingwu,hupiyingwu
🐸,qingwalian,
🐊,eyu,
🐢,gui,lugui
🦎,xiyi,bihu，shilongzi
🐍,she,
🐲,longtou,
🐉,long,
🦕,konglong,leilong
🦖,bawanglong,
🐳,penshuidejingyu,
🐋,jingyu,
🐬,haitun,
🐟,yu,
🐠,redaiyu,
🐡,hetun,
🦈,shayu,dabaisha，jingsha
🐙,zhangyu,
🐚,haibei,beike，hailuo
🐌,woniu,
🦋,hudie,dalanshandie
🐛,chongzi,maomaochong
🐜,mayi,
🐝,mifeng,
🐞,piaochong,
🦗,xishuai,
🕷,zhizhu,
🕸,zhizhuwang,
🦂,xiezi,
🦟,wenzi,
🦠,bingdu,guanzhuangbingdu
💐,huashu,xianhua，yishuhua
🌸,yinghua,huaduo，yiduohua🌷
💮,baisedehua,huaduo
🏵,meiguihuajie,zhuangshipin
🌹,meiguihua,huaduo
🥀,kuweidemeigui,huaduo
🌺,furong,huaduo
🌻,xiangrikui,huaduo
🌼,huaduo,
🌷,yujinxiang,huaduo
🌱,youmiao,faya，shuya
🌲,changqingshu,
🌳,shu,
🌴,zonglvshu,yezishu
🌵,xianrenzhang,
🌾,daosui,
🌿,caobenzhiwu,yezi
☘,sanyecao,yezi
🍀,siyecao,yezi
🍁,fengye,yezi
🍂,luoye,yezi，kuye
🍃,zaifengzhongpiaoyangdeyezi,luoye
🍄,mogu,junlei
🌰,lizi,
🦀,pangxie,
🦞,longxia,xiaolongxia
🦐,xia,
🦑,youyu,
🌍,xianshiouzhouhefeizhoudediqiuyi,
🌎,xianshimeizhoudediqiuyi,nanmeizhou，beimeizhou
🌏,xianshiyazhouheaozhoudediqiuyi,dayangzhou
🌐,xianshijingweixianxiandediqiuyi,
🌑,xinyue,yueliang，yueqiu
🌒,meiyue,yueliang，yueqiu
🌓,shangxianyue,yueliang，yueqiu
🌔,yingtuyue,yueliang，yueqiu
🌕,manyue,yueliang，yueqiu
🌖,kuituyue,yueliang，yueqiu
🌗,xiaxianyue,yueliang，yueqiu
🌘,canyue,yueliang，yueqiu
🌙,yueya,yueliang，yueqiu
🌚,daimiankongdexinyue🌞,yueliang，yueqiu
🌛,daimiankongdeshangxianyue,yueliang，yueqiu
🌜,daimiankongdexiaxianyue,yueliang，yueqiu
☀,taiyang,
🌝,daimiankongdemanyue,
🌞,daimiankongdetaiyang,
⭐,xingxing,wujiaoxing
🌟,shanyaodexingxing,wujiaoxing
🌠,liuxing,liuxingyu
☁,yunduo,baiyun，duoyun
⛅,yunhoumianditaiyang,duoyun
⛈,daishandiandeyudiandeyun,
🌤,yunduohoumianditaiyang,duoyun
🌥,yuntuanhoumianditaiyang,duoyun
🌦,yuyunhoumianditaiyang,taiyangyu
🌧,daiyudiandeyun,yuyun，xiayu
🌨,daixuehuadeyun,xueyun，xiaxue
🌩,daishandiandeyun,
🌪,longjuanfeng,jufeng，xuanfeng
🌫,wu,wumai
🌬,fengchuifudelian,
🌈,caihong,
☂,yusan,
☔,yusanshangyouyudi,xiayu
⚡,shandian,dalei
❄,xuehua,xiaxue
☃,beixuehuabaoweidexueren,
⛄,xueren,
☄,huixing,
🔥,huoyan,huobao
💧,xiaoshuizhu,shuidi
🌊,bolang,botao，langhua
🎄,shengdanshu,
✨,shanguang,xingxing
🎋,qixishu,
🎍,songshuzhuangshi,
🍇,putao,tizi，hongti，shuiguo
🍈,tiangua,hamigua，xianggua，yilishabaigua，shuiguo
🍉,xigua,shuiguo
🍊,ganju,juzi，juzi，chengzi，qicheng，zhucheng，shuiguo
🍋,ningmeng,shuiguo
🍌,xiangjiao,shuiguo
🍍,boluo,fengli，shuiguo
🥭,mangguo,shuiguo
🍎,pingguo,shuiguo
🍏,qingpingguo,shuiguo
🍐,li,shuiguo
🍑,taozi,shuimitao，shuiguo
🍒,yingtao,chelizi，shuiguo
🍓,caomei,shiduopili，shuiguo
🥝,qiyiguo,mihoutao，shuiguo
🍅,xihongshi,fanqie，shuiguo，shucai
🥥,yezi,yerou，shuiguo
🥑,niuyouguo,eli，shuiguo
🍆,qiezi,shucai
🥔,tudou,shucai
🥕,huluobu,shucai
🌽,yumi,
🌶,lajiao,xiaomijiao，shucai
🥒,huanggua,shucai
🥬,lvyeshucai,qingcai，baicai，youmaicai
🥦,xilanhua,shucai
🧄,suan,dasuan
🧅,yangcong,
🍄,mogu,junlei
🥜,huasheng,
🌰,lizi,banli，tangchaolizi
🍞,mianbao,tusi，tusi
🥐,niujiaomianbao,yangjiaomianbao
🥖,fashichanggunmianbao,
🥨,jiaoyanjuanbing,
🥯,baijibing,
🥞,baojianbing,
🧇,huafubing,
🧀,nailao,
🍖,daigurou,tibang
🍗,jitui,yatui，etui
🥩,roupai,niupai，zhupai，yangpai
🥓,peigen,
🍔,hanbaobao,kuaican
🍟,shutiao,kuaican
🍕,pisa,kuaican
🌭,regou,kuaican
🥪,sanmingzhi,kuaican
🌮,moxigebaobingjuan,moxigejuan，kuaican
🌯,moxigejuanbing,kuaican
🥙,pitasanmingzhi,kuaican
🧆,falafei,kuaican
🥚,dan,yadan
🍳,jiandan,pengren
🥘,yiguoshiwu,baotang
🍲,yiguoshiwu,jitang
🥣,fangzheshaodewan,fanwan，wanshao，canju
🥗,lvseshala,shucaishala
🍿,baomihua,
🧈,huangyou,
🧂,yan,tiaoweipin，tiaoweiping
🥫,guantoushipin,
🍱,biandanghe,
🍘,mibing,
🍙,fantuan,
🍚,mifan,
🍛,galifan,
🍜,maoreqidewan,miantiao，yiwanmian
🍝,yidalimian,
🍠,kaodigua,hongshu，zishu
🍢,guandongzhu,chuanchuan
🍣,shousi,sanwenyushousi
🍤,tianfuluo,zhaxia
🍥,panraoshizhayubing,
🥮,yuebing,wuren
🍡,guandongzhu,chuanchuan，wanzi，tuanzi
🥟,jiaozi,huntun，bianshi
🥠,xingyunbinggan,
🥡,waimaihe,
🦪,muli,shenghao
🍦,bingjiling,tiantong
🍧,baobing,bingsha
🍨,bingjiling,
🍩,tiantianquan,tiandian
🍪,quqi,binggan
🎂,shengridangao,tiandian
🍰,dangao,tiandian
🧁,zhibeidangao,tiandian
🥧,xianbing,pingguopai，boluopai，tiandian
🍫,qiaokelibang,
🍬,tangguo,
🍭,bangbangtang,
🍮,buding,dannaigao
🍯,miguan,
🍼,naiping,
🥛,niunai,niunaibei
☕,kafei,kafeibei，reyin
🍵,chabei,
🍶,qingjiujiupinghebeizi,
🍾,pingsaitanchudexiangbinjiuping,
🍷,hongjiujiubei,
🍸,jiweijiujiubei,
🍹,redaiyinliao,jiubei
🍺,pijiujiubei,
🍻,ganbei,pengbei，pijiujiubei
🥂,pengbei,ganbei，xiangbinjiubei
🥃,weishijijiubei,pingdibei
🥤,waidaibeizi,yicixingyinliaobei
🧃,guozhihe,
🧉,madaicha,yinliao
🧊,bingkuai,
🥢,kuaizi,canju
🍽,pangbianfangyoudaochadepanzi,canju
🍴,daocha,canju
🥄,shaozi,tiaogeng，canju
🕴,fuzaidimianshangdexizhuangnan,xizhuang，piaofu
🧗,panyanzhe,panyan，jixianyundong，pandeng
🧗‍♂️,nanpanyanzhe,panyan，jixianyundong，pandeng
🧗‍♀️,nvpanyanzhe,panyan，jixianyundong，pandeng
🤺,jijianzhe,yundong，jijian，jingji，jijianyundongyuan
🏇,saimaqishi,saima，qima，mashu，yundongyuan
⛷,huaxuezhe,huaxue，shuangban
🏂,danbanhuaxue,huaxue，danban
🏌,gaoerfuqiushou,yundong，gaoerfu
🏌️‍♂️,nangaoerfuqiushou,yundong，gaoerfu
🏌️‍♀️,nvgaoerfuqiushou,yundong，gaoerfu
🏄,chonglangzhe,chonglang，jixianyundong，nongchaoer
🏄‍♂️,nanchonglangzhe,chonglang，jixianyundong，nongchaoer
🏄‍♀️,nvchonglangzhe,chonglang，jixianyundong，nongchaoer
🚣,huachuanderen,huachuan，xiaochuan
🚣‍♂️,huachuandenanren,huachuan，xiaochuan
🚣‍♀️,huachuandenvren,huachuan，xiaochuan
🏊,youyongzhe,youyong，ziyouyong
🏊‍♂️,nanyouyongzhe,youyong，ziyouyong
🏊‍♀️,nvyouyongzhe,youyong，ziyouyong
⛹,lanqiuyundongyuan,lanqiu，yunqiu，pao
⛹️‍♂️,nanlanqiuyundongyuan,lanqiu，yunqiu，pao
⛹️‍♀️,nvlanqiuyundongyuan,lanqiu，yunqiu，pao
🏋,juzhongzhe,juzhong，zhuaju
🏋️‍♂️,nanjuzhongzhe,juzhong，zhuaju
🏋️‍♀️,nvjuzhongzhe,juzhong，zhuaju
🚴,zixingcheqishou,zixingche，qixing，qishou
🚴‍♂️,nanzixingcheqishou,zixingche，qixing，qishou
🚴‍♀️,nvzixingcheqishou,zixingche，qixing，qishou
🚵,shandizixingcheqishou,shandizixingche，qixing，qishou，yueye
🚵‍♂️,nanshandizixingcheqishou,shandizixingche，qixing，qishou，yueye
🚵‍♀️,nvshandizixingcheqishou,shandizixingche，qixing，qishou，yueye
🤸,zuoceshoufanderen,ceshoufan，fangun
🤸‍♂️,zuoceshoufandenanren,ceshoufan，fangun
🤸‍♀️,zuoceshoufandenvren,ceshoufan，fangun
🤼,shuaijiaoderen,shuaijiao，shuaijiaoxuanshou
🤼‍♂️,shuaijiaodenanren,shuaijiao，shuaijiaoxuanshou
🤼‍♀️,shuaijiaodenvren,shuaijiao，shuaijiaoxuanshou
🤽,dashuiqiuderen,shuiqiu，shuishangzuqiu
🤽‍♂️,dashuiqiudenanren,shuiqiu，shuishangzuqiu
🤽‍♀️,dashuiqiudenvren,shuiqiu，shuishangzuqiu
🤾,dashouqiuderen,shouqiu
🤾‍♂️,dashouqiudenanren,shouqiu
🤾‍♀️,dashouqiudenvren,shouqiu
🤹,wanzashuaderen,zashua，zaji，biaoyan
🤹‍♂️,wanzashuadenanren,zashua，zaji，biaoyan
🤹‍♀️,wanzashuadenvren,zashua，zaji，biaoyan
🧘,lianhuazuoderen,lianhuazuo，pantuizuo，dazuo，yujia，mingxiang
🧘‍♂️,lianhuazuodenanren,lianhuazuo，pantuizuo，dazuo，yujia，mingxiang
🧘‍♀️,lianhuazuodenvren,lianhuazuo，pantuizuo，dazuo，yujia，mingxiang
🎪,maxituanzhangpeng,maxituan，maxi，zhangpeng
🛹,huaban,huaban，jixianyundong，shuangqiaohuaban
🛶,dumuzhou,dumuzhou，xiaochuan
🎗,huangsidai,sidai，sijin，zhuangshi，shipin
🎟,ruchangquan,ruchangquan，menpiao
🎫,menpiao,ruchangquan，menpiao，piaogen
🎖,jungongxunzhang,xunzhang，junzhang，jungongzhang，jiangzhang
🏆,jiangbei,jiangbei，jinshu，guanjun，huojiang
🏅,yundonghuijiangpai,yundonghui，jiangpai，huojiang，shengli
🥇,jinpai,diyiming，guanjun，jiangpai，shengli
🥈,yinpai,dierming，yajun，jiangpai，huosheng
🥉,tongpai,disanming，jijun，jiangpai，huosheng
⚽,zuqiu,zuqiu，tiqiu，cuju
⚾,bangqiu,
🥎,leiqiu,
🏀,lanqiu,daqiu
🏐,paiqiu,
🏈,meishiganlanqiu,ganlanqiu，meishizuqiu
🏉,ganlanqiu,
🎾,wangqiu,wangqiu，aowang，fawang，wenwang
🥏,feipan,feipan，jingji
🎳,baolingqiuhebaolingqiuping,baolingqiu，baolingqiuping，digunqiu，qiuleiyundong
🏏,banqiupaihebanqiu,banqiu，banqiupai，muqiu，qiuleiyundong
🏑,qugunqiugunhequgunqiu,qugunqiu，qugunqiugun，qiuleiyundong
🏒,bingqiuganhebingqiu,bingqiu，bingqiugan，bingshangyundong，qiuleiyundong，bingshangqugunqiu
🥍,changqugunqiubanghequgunqiu,changqugunqiubang，qugunqiu，qiuleiyundong
🏓,pingpangqiupaihepingpangqiu,pingpangqiu，pingpangqiupai，guoqiu，xiaoqiu，qiuleiyundong
🏸,yumaoqiupaiheyumaoqiu,yumaoqiupai，yumaoqiu，qiuleiyundong
🥊,quanjishoutao,quanji，quanjishoutao，gedou，jingji，gongji
🥋,wushufu,wushu，wushufu，fushi
🥅,qiumenwang,qiumenwang，qiumen
⛳,chazheqigandegaoerfuqiudong,qigan，gaoerfu，qiudong
⛸,liubingxie,liubingxie，xiexue，liubing，yundongzhuangbei
🎣,diaoganheyu,diaogan，diaoyu，chuidiao
🎽,yundongbeixin,yundongbeixin，fushi，yundong，yundongzhuangbei
🎿,huaxue,huaxue，yundongzhuangbei
🛷,xueqiao,xueqiao，yundongzhuangbei，qicai
🥌,binghushi,binghushi，yundongqicai，binghu
🎯,baxin,jianba，baxin，zhongba
🎱,taiqiu,taiqiu，qiuleiyundong，zhuoqiu，zhuangqiu
🎮,shipinyouxishoubing,youxi，shoubing，youxizhuangbei，youxiji
🎰,laohuji,laohuji，laba，fentiaoji，shuiguoji
🎲,youxitouzi,youxi，touzi，caidaxiao
🧩,pintukuai,pintu，suipian
♟,guojixiangqibing,guojixiangqi，xiyangqi
🎭,biaoyanyishu,biaoyan，mianju，yishu
🎨,meishutiaoseban,tiaoseban，meishu，huahua
🧵,xian,maoxian，zhenzhi
🧶,shaxian,masheng，maoyixian
🎼,yuepu,yuepu，yinyue，puqu，zuoqu
🎤,maikefeng,maikefeng，huatong，changge
🎧,erji,erji，toudaishierji
🎷,sakesiguan,sakesi，yueqi，yanzou
🎸,jita,jita，yueqi，yanzou
🎹,yinyuejianpan,gangqin，jianpan，yanzou
🎺,xiaohao,xiaohao，yueqi，yanzou
🎻,xiaotiqin,xiaotiqin，yueqi，yanzou
🥁,gu,gu，dagu，yueqi，yanzou
🎬,changjiban,changjiban，paishe
🏹,gonghejian,gong，jian，gongjian，shejian
🚣,huachuanderen,huachuan，chuan
🗾,ribenjianying,riben，nihongguo，daoguo，ribenditu
🏔,baixuefugaideshanmai,xueshan，shanmai
⛰,shanmai,shanmai，shanfeng
🌋,huoshan,huoshan
🗻,fushishan,fushishan，riben，shanfeng
🏕,luying,luying，yeying，zhangpeng
🏖,youtaiyangsandihaitan,taiyangsan，shatan，haitan，dujia
🏜,shamo,shamo
🏝,huangdao,huangdao，xiaodao，shatan
🏞,guojiagongyuan,guojiagongyuan，gongyuan，jingdian
🏟,tiyuchang,tiyuchang，bisai
🏛,gudianjianzhu,jianzhu，shenmiao
🏗,jianzhushigong,jianzhu，shigong，gongdi
🏘,fangwuqun,fangwu，bieshuqun
🏚,feiqidefangwu,feiqi，fangwu
🏠,zhuzhailou,zhuzhai，fangwu，jia，dudong
🏡,daihuayuandeloufang,fangwu，jia，huayuan，dudong
🏢,bangonglou,bangonglou，gongsi，dasha
🏣,ribenyouju,youju
🏤,ouzhouyouju,youju
🏥,yiyuan,yiyuan，kanbing
🏦,yinhang,yinhang
🏨,jiudian,jiudian，lvguan
🏩,aiqinglvguan,lvguan，yuehui
🏪,bianlishangdian,bianlidian，711
🏫,xuexiao,xuexiao，xiaoxue，zhongxue，daxue
🏬,baihuoshangdian,baihuodalou，shangchang
🏭,gongchang,gongchang，changjia
🏯,ribenchengbao,chengbao，gongdian
🏰,ouzhouchengbao,chengbao，gongdian
💒,hunli,hunli，hunlihuisuo，jiehun
🗼,dongjingta,dongjingta，dongjing，riben
🗽,ziyounvshenxiang,ziyounvshen，nvshen，diaosu
⛪,jiaotang,jiaotang，jiaohui，libai
🕌,qingzhensi,qingzhensi
🛕,yindumiao,yindumiao
🕍,youtaijiaohuitang,jiaohuitang，youtaijiaotang
⛩,shenshe,shenshe，ribenshenshe，riben
🕋,keerbai,keerbai，musilin，tianfang
⛲,penshuichi,penquan，shuichi
⛺,zhangpeng,zhangpeng，luying，yeying
🌁,wuqilongzhaodeqiao,qiao，wu
🌃,xingguangshanshandeyewan,yewan，xingguang，xingxing，yejing
🏙,chengshijingguan,chengshi，chengshifengguang，motiandalou
🌄,dashanrichu,richu，shanfeng
🌅,richu,richu，haishangrichu
🌆,musezhongdichengshijingguan,chengshi，chengshifengguang，motiandalou，riluo，huanghun，bangwan，xiyang
🌇,dashaxiyang,motiandalou，chengshifengguang，xiyang，riluo，huanghun，bangwan
🌉,yejiandedaqiao,yewan，qiao
🎠,xuanzhuanmuma,xuanzhuanmuma，youlechang
🎡,motianlun,motianlun，youlechang
🎢,guoshanche,guoshanche，youlechang
🚂,zhengqihuoche,huoche，zhengqi
🚃,guidaolieche,huoche，lieche，guidao
🚄,gaosulieche,gaotie，gaosu，lieche，hexiehao
🚅,gaosuzidantoulieche,hexiehao，fuxinghao，gaosu，zidantou，lieche
🚆,huoche,huoche，tielu
🚇,ditie,ditie
🚈,qingguidianche,qinggui，dianche
🚉,chezhan,chezhan
🚊,dianche,dianche
🚝,danguitielu,dangui，tielu
🚞,shanqutielu,shanqu，tielu，huoche
🚋,youguidianche,yougui，dianche
🚌,gongjiaoche,gongjiao，bashi
🚍,yingmianerlaidebashi,gongjiao，bashi，yingmianerlai
🚎,wuguidianche,wugui，dianche
🚐,mianbaoche,mianbaoche，wuling，jinbei
🚑,jiuhuche,jiuhuche
🚒,xiaofangche,xiaofangche，jiuhuoche
🚓,jingche,jingche
🚔,yingmianerlaidejingche,jingche，yingmianerlai
🚕,chuzuche,chuzuche，dishi，dadi
🚖,yingmianerlaidedishi,chuzuche，dishi，dadi，yingmianerlai
🚗,qiche,qiche，sijiache，jiaoche，xiaoqiche
🚘,yingmianerlaideqiche,qiche，sijiache，jiaoche，xiaoqiche，yingmianerlai
🚙,lanseche,qiche，sijiache，jiaoche，xiaoqiche
🚚,songhuoche,songhuoche，huoche，kache
🚛,tuoche,tuoche
🚜,tuolaji,tuolaji，tieniu
🏎,saiche,saiche，gonglusaiche
🏍,motuoche,motuoche，motuo
🛵,xiaoxingmotuoche,diandongche，xiaoxingmotuoche
🛺,duduche,duduche，dudu，daibuche
🚲,zixingche,zixingche，danche，jiaotache，yangche
🛴,huabanche,huabanche，daibuche
🚏,gongjiaochezhan,gongjiaochezhan，chezhan，zhanpai
🛣,gaosugonglu,gaosu，gaosugonglu，guodao，shengdao
🛤,tiegui,tiegui，tielu
⛽,ranliaobeng,ranliaobeng，ranliao
🚨,jingchexuanzhuandeng,xuanzhuandeng，honglanbaoshandeng，jingdeng
🚥,shuipingjiaotongxinhaodeng,xinhaodeng，shuipingxinhaodeng，jiaotongxinhaodeng，honglvdeng
🚦,chuizhijiaotongxinhaodeng,xinhaodeng，chuizhixinhaodeng，jiaotongxinhaodeng，honglvdeng
🚧,shigongfuhao,shigong，weilan
⚓,mao,mao，chuanmao
⛵,fanchuan,fanchuan，chuan
🚤,kuaiting,kuaiting
🛳,kelun,kelun，youlun，lunchuan
⛴,lundu,lundu，duchuan
🛥,motuoting,motuoting
🚢,chuan,chuan
✈,feiji,feiji，feixing，hangkong
🛩,xiaoxingfeiji,xiaoxingfeiji，sirenfeiji
🛫,feijiqifei,feiji，qifei，chufa
🛬,feijizhelu,feiji，luodi，daoda，jiangluo
🪂,jiangluosan,jiangluosan，jiangluo
💺,zuowei,zuowei，yizi，zuoyi
🚁,zhishengji,zhishengji
🚟,gaojiatielu,gaojia，tielu，huoche
🚠,gaoshansuodao,suodao，gaoshansuodao
🚡,kongzhonglanche,lanche，kongzhonglanche
🛰,weixing,weixing，guidaoweixing
🚀,huojian,huojian，shenzhou
🛸,UFO,UFO，bumingfeixingwu，waixingren
🪐,xingxing,xingxing，xingqiu，waixingqiu
🌠,liuxing,liuxing，xuyuan，liuxingyu
🌌,yinhexi,yinhangxi
⛱,shatansan,shatansan，zheyangsan
🎆,yanhuo,yanhuo，yanhua，huahuo
🎇,yanhuoyanhua,yanhuo，yanhua，huahuo
🎑,zhongqiushangyue,zhongqiu，shangyue，zhongqiujie
💴,riyuanchaopiao,riyuan，chaopiao
💵,meiyuanchaopiao,meiyuan，chaopiao
💶,ouyuanchaopiao,ouyuan
💷,yingbangchaopiao,yingbang
🗿,fuhuojiedaoshixiang,fuhuojiedao，shixiang
🛂,huzhaojianchachu,huzhao，jiancha，huzhaojiancha
🛃,haiguan,haiguan
🛄,xinglilingquchu,xinglilingqu，xingli
🛅,xinglijicunchu,xingli，jicun
💌,qingshu,xinfeng，aixin
🕳,dong,heidong，keng
💣,zhadan,shouliudan
🛀,xizaoderen,yugang
🛌,shuijiaoderen,chuang，shuijiao
🔪,dao,daoju，caidao，shuiguodao
🏺,shuangerping,taoci，ciqi
🗺,shijieditu,
🧭,zhinanzhen,zhibeizhen，sinan，luopan
🧱,zhuankuai,zhuantou，qiangzhuan
💈,lifadianzhaopai,sansedeng，falang，nihongdeng
🦽,shoudonglunyi,lunyi
🦼,diandonglunyi,lunyi
🛢,youtong,jinshutong，baiyoutong
🛎,fuwuling,anling，xiangling
🧳,xinglixiang,xingli，xiangzi，lvxingxiang，xiangbao
⌛,shalou,shazhong，shahu
⏳,zhuangleliushadeshalou,shalou，shazhong，shahu
⌚,shoubiao,zhongbiao
⏰,naozhong,naoling
⏱,miaobiao,jishiqi
⏲,dingshiqi,jishiqi
🕰,taizhong,zhongbiao
🌡,wenduji,
⛱,shatansan,zheyangsan
🧨,bianpao,baozhu，shuaipao，gaosheng
🎈,hongseqiqiu,qingqiqiu
🎉,paiduilibinhua,zhuhe，gongxi，hecai，hecai
🎊,wucaizhixieqiu,zhuhe，gongxi，hecai，hecai
🎎,ribenwawa,wanou
🎏,liyuqi,liyu
🎐,fengling,lingdang
🧧,hongbao,yasuiqian
🎀,sidai,hudiejie
🎁,liwu,jingxi，lihe，liwuhe，lipin，baozhuang
🤿,qianshuimianzhao,qianshuimianju
🪀,liuliuqiu,youyouqiu
🪁,fengzheng,zhiyuan
🔮,shuijingqiu,boliqiu，mofaqiu
🧿,emozhiyan,moguizhiyan，emoyanjing
🕹,caozonggan,lagan，yaogan
🧸,taidixiong,maorongwanju
🖼,daihuakuangdetupian,huakuang，tupian
🧵,xian,
🧶,shaxian,masheng，maoyixian
🛍,gouwudai,shoudai，zhidai，shoutidai
📿,nianzhu,shuzhu，shouchuan
💎,baoshi,zuanshi
📯,youzhenglaba,laba，youzheng
🎙,luyinshimaikefeng,maikefeng，luyin，huatong
🎚,dianpinghuakuai,huakuai
🎛,kongzhixuanniu,kongzhi
📻,shouyinji,wuxiandian
🪕,banzhuoqin,wuxianqin
📱,yidongdianhua,shouji，dianhua，iPhone
📲,daijiantoudedianhua,hujiao，boda，iPhone
☎,dianhua,dianhuaji，zuoji
📞,dianhuatingtong,tingtong
📟,chuanhuji,BBji、BPji
📠,chuanzhen,chuanzhenji
🔋,dianchi,nengliang，chongdian
🔌,dianchatou,chatou，shuangkongchatou
💻,bijibendiannao,bijiben，diannao，Macbook，jisuanji
🖥,taishidiannao,PC，jisuanji
🖨,dayinji,
⌨️,jianpan,
🖱,diannaoshubiao,shubiao，huashu
🖲,guijiqiu,shubiao
💽,miniguangpan,guangpan，guangdie，CD
💾,ruanpan,
💿,guangpan,guangpan，guangdie
📀,DVDguangpan,guangdie
🧮,suanpan,suanzhu
🎥,dianyingshexiangji,shexiangji，shexiang
🎞,dianyingjiaopian,jiaopian，dipian
📽,dianyingfangyingji,fangyingji，fangying
📺,dianshiji,dianshi，heibaidianshi
📷,xiangji,shumaxiangji，zhaoxiangji
📸,kaishanguangdengdexiangji,shanguangdeng，xiangji，paishe，zhaoxiangji
📹,shexiangji,shexiang，luyingji，sheyingji
📼,luxiangdai,luxiang，cidai
🔍,xiangzuozhidefangdajing,fangdajing
🔎,xiangyouzhidefangdajing,fangdajing
🕯,lazhu,
💡,dengpao,baichideng，linggan
🔦,shoudiantong,shoudian
🏮,jujiuwudenglong,jujiuwu，denglong，hongdenglong，hongse
🪔,youdeng,
📔,daizhuangshifengmiandibijiben,huangsebijiben，jishiben
📕,hongsejiaokeshu,hongseshuben
📖,dakaideshuben,yuedu，shuben
📗,lvsejiaokeshu,lvseshuben
📘,lansejiaokeshu,lanseshuben
📙,chengsejiaokeshu,chengseshuben
📚,tushu,shuben
📓,yingkebijiben,yingkeben，jishiben
📒,bijiben,huangsebijiben，jishiben
📃,daijuanbiandeyemian,zhizhang
📜,juanzhou,zhizhang
📄,chaoshangdeyemian,zhi，zhizhang
📰,baozhi,xinwen，baokan
🗞,juanqidebaozhi,baozhi，xinwen，baokan
📑,shuqianbiaoqian,shuqian，biaoqian
🔖,shuqian,
🏷,biaoqian,
💰,qiandai,qianbi，qian，caifu，jinqian
💴,riyuanchaopiao,riyuan，chaopiao
💵,meiyuanchaopiao,meiyuan，chaopiao
💶,ouyuanchaopiao,ouyuan，chaopiao
💷,yingbangchaopiao,yingbang，chaopiao
💸,changlechibangdejinqian,jinqian，feizoudeqian
💳,xinyongka,yinhangka，jiejika
🧾,shouju,piaoju，danju，fapiao
✉,xinfeng,xinjian
📧,dianziyoujian,youjian，xinjian
📨,laixin,shouxin
📩,daijiantoudexinfeng,laixin
📤,fajianxiangtuopan,shoujianxiang
📥,shoujianxiangtuopan,fajianxiang
📦,baoguo,kuaidi
📫,qibiaozhilideguanshangdeyouxiang,youxiang，xinxiang
📪,yiguanbiqieqibiaopingfangdeyouxiang,youxiang，xinxiang
📬,qibiaozhilidedakaideyouxiang,youxiang，xinxiang
📭,yidakaiqieqibiaopingfangdeyouxiang,youxiang，xinxiang
📮,youtong,xinxiang，jijianxiang
🗳,daixuanpiaodetoupiaoxiang,toupiaoxiang，toupiao，xuanpiao
✏,qianbi,
✒,gangbi,
🖋,gangbi,
🖊,yuanzhubi,
🖌,huabi,
🖍,labi,
📝,beiwanglu,zhibi，beiwang
📁,guanbidewenjianjia,wenjianjia
📂,dakaidewenjianjia,wenjianjia
🗂,kapiansuoyinfengeka,kapian，fengeka
📅,rili,wannianli，taili，nianli
📆,yisidiaoderili,rili，taili，nianli
🗒,xianquanbijiben,xianzhuangben，zhi
🗓,xianquanrili,xianzhuangrili，taili，nianli
📇,kapiansuoyin,
📈,qushixiangshangdetubiao,tubiao，qushi，zhexiantu
📉,qushixiangxiadetubiao,tubiao，qushi，zhexiantu
📊,tiaoxingtu,
📋,jiantieban,xieziban
📌,tuding,qinding
📍,yuantuding,tuding，qinding
📎,huixingzhen,qubiezhen
🖇,huixingzhen,qubiezhen
📏,zhichi,chizi
📐,sanjiaochi,chizi，sanjiaoban
✂,jiandao,jianzi
🗃,kapiancundanghe,cundanghe
🗄,wenjiangui,guizi，shounagui
🗑,feizhilou,lajitong
🔒,heshangdesuo,suoshang，shangsuo
🔓,dakaidesuo,suo，kaisuo，jiesuo
🔏,daimoshuibidesuo,bi，suo
🔐,yisuoshangdanguazheyaoshidesuo,yaoshi，suo
🔑,yaoshi,suo
🗝,gulaodeyaoshi,yaoshi
🔨,chuizi,tiechui，langtou，gongju
🪓,fuzi,tiefu，futou，kan，gongju
⛏,tiegao,qiao，gongju
⚒,chuizihetiegao,chuizi，tiegao，gongju
🛠,chuizihebanshou,chuizi，banshou，gongju
🗡,bishou,jian，duanjian，wuqi
⚔,jiaochafangzhidejian,shuangjian，jian，wuqi
🔫,shuiqiang,wanjuqiang
🛡,dunpai,dun，huju
🔧,banshou,gongju
🔩,luomujiluoshuan,luosi，luomu，luoshuan
⚙,chilun,chitiao，lianlun，gongju
🗜,jiaqian,qianzi，jiazi，gongju
⚖,tianping,tiancheng，gongping
🦯,baishouzhang,shouzhang
🔗,lianjiefuhao,lianjie
⛓,liantiao,tielian
🧰,gongjuxiang,gongju
🧲,citie,xitieshi，gongju
⚗,zhengliuqi,zhengliu
🧪,shiguan,shiji
🧫,peiyangmin,bolimin
🧬,tuoyanghetanghesuan,tuoyanghetanghesuan
🔬,xianweijing,
🔭,wangyuanjing,tianwenwangyuanjing
📡,weixingtianxian,tianxian，yuanpantianxian
💉,zhusheqi,dazhen，zhushe，zhentong，xie
🩸,xiedi,xueye，liuxue，xie
💊,yaowan,yao
🩹,chuangketie,okbeng，huchuangtie
🩺,tingzhenqi,
🚪,men,guanmen，jiaju
🛏,chuang,shuijiao，jiaju
🛋,shafahedeng,shafa，deng，luodideng，jiaju
🪑,yizi,zuoyi，yizi，jiaju
🚽,cesuo,matong，zuobianqi
🚿,linyu,xizao，muyu
🛁,yugang,xizao，paozao，muyu
🪒,tidao,guadao
🧴,ruyeping,ruye，fenzhuangping
🧷,anquanbiezhen,biezhen
🧹,saozhou,saoba
🧺,lanzi,zhulan
🧻,juanzhi,zhijin
🧼,feizao,xiangzao
🧽,haimian,zaojin
🧯,miehuoqi,miehuoqiping
🛒,gouwuche,tuiche
🚬,xiangyan,yantou，xiyan
⚰,guancai,shouguan，guanguo，guanjiu，guanmu，shoumu
⚱,guhuiguan,guhuiping
🗿,fuhuojiedaoshixiang,fuhuojiedao，shixiang
🚰,shuilongtou,longtou，dishui
💘,chuanjianaixin,aixin，hongxin，jiantou
💝,shiyisidaidexin,aixin，hongxin，sidai
💖,shanliangdexin,aixin，hongxin，faguang
💗,chengzhangdexin,aixin，hongxin
💓,xintiao,aixin，hongxin，tiaodong
💞,xuanzhuandexin,aixin，hongxin，zhuanquan
💕,liangkexin,aixin，hongxin，xinxiangyin
💟,xinxingzhuangshi,aixin，xinxing
❣,zuoweigantanhaodehongsexin,aixin，hongxin，gantanhao
💔,posuidexin,aixin，hongxin，shangxin，xinsui
❤,hongsedexin,aixin，hongxin，aini，xihuan
🧡,chengsexinxing,aixin，chengxin，aini，xihuan
💛,huangsedexin,aixin，huangxin，aini，xihuan
💚,lvsedexin,aixin，lvxin，aini，xihuan
💙,lansedexin,aixin，lanxin，aini，xihuan
💜,zisedexin,aixin，zixin，aini，xihuan
🤎,zongsedexin,aixin，zongxin，aini，xihuan
🖤,heisedexin,aixin，heixin
🤍,baisedexin,aixin，baixin
💯,100fenfuhao,manfen，100fen
💢,shengqifuhao,shengqi，naonu，fennu
💬,duihuaqipao,liaotian
👁️‍🗨️,woshizhengren,zhengren
🗨,chaozuodeduihuaqipao,liaotian
🗯,biaoshifennudeduihuaqipao,liaotian，shengqi
💭,sikao,sisuo
💤,shuimian,shuijiao，wanan，shuile
💮,baisedehua,baihua
♨,wenquan,paotang，hanzheng
💈,lifadianzhaopai,sansedeng，falang
🛑,babianxingfuhao,
🕛,shierdianzhong,0dian，lingdian，lingchen，wushi，zishi
🕧,liudiansanshi,maoshi，youshi
🕐,yidianzhong,choushi，weishi
🕜,yidiansanshi,zishi，weishi
🕑,liangdianzhong,choushi，weishi
🕝,liangdiansanshi,choushi，weishi
🕒,sandianzhong,yinshi，shenshi
🕞,sandianban,yinshi，shenshi
🕓,sidianzhong,yinshi，shenshi
🕟,sidianban,yinshi，shenshi
🕔,wudianzhong,maoshi，youshi
🕠,wudiansanshi,maoshi，youshi
🕕,liudianzhong,maoshi，youshi
🕡,liudiansanshi,maoshi，youshi
🕖,qidianzhong,chenshi，xushi
🕢,qidiansanshi,chenshi，xushi
🕗,badianzhong,chenshi，xushi
🕣,badiansanshi,chenshi，xushi
🕘,jiudianzhong,sishi，haishi
🕤,jiudiansanshi,sishi，haishi
🕙,shidianzhong,sishi，haishi
🕥,shidiansanshi,sishi，haishi
🕚,shiyidianzhong,wushi，zishi
🕦,shiyidiansanshi,wushi，zishi
🌀,longjuanfeng,xuanwo
♠,heitao,
♥,hongtao,hongxin
♦,fangkuai,fangpian
♣,meihua,
🃏,xiaochoupukepai,daiwang，xiaowang
🀄,majiangpaihongzhong,
🎴,huapukepai,
🔇,yijingyindeyangshengqi,wusheng
🔈,yangshengqi,laba，shengyin
🔉,zhongdengyinliangdeyangshengqi,zhongyinliang
🔊,gaoyinliangdeyangshengqi,gaoyinliang
📢,gonggongguangbokuoyinlaba,guangbo
📣,labatong,jinlaba
📯,youzhenglaba,
🔔,lingdang,xiangling
🔕,yijingyindexiangling,wusheng
🎵,yinfu,yinyue
🎶,yinfu,yinyue
💹,qushixiangshangqiedaiyourenminbifuhaodetubiao,zoushitu
🏧,ATMzidongqukuanji,tikuanji
🚮,lajirulou,aihuhuanjing
🚰,shuilongtou,jieshui，liushui
♿,lunyifuhao,canjiren
🚹,nanshifuhao,nanren
🚺,nvshifuhao,nvren
🚻,weishengjian,xishoujian，guanxishi，cesuo
🚼,yingerfuhao,Baby，baobao，xiaohai，ertong
🚾,WCcesuo,xishoujian，guanxishi，weishengjian
⚠,jinggao,weixian
🚸,xuetongguojie,xuexiao
⛔,jinzhirunei,jinxing
🚫,jinzhi,bukeyi
🚳,jinzhiqiche,
🚭,jinzhixiyan,jinyan，wuyanqu
🚯,wurenglaji,baohuhuanjing
🚱,feiyinyongshui,bukeyinyong
🚷,jinzhixingren,jinxing，buketongxing
📵,jinzhishiyongshouji,jinyongshouji
🔞,budexiaoyu18sui,chengren，weichengnianren
☢,fangshexing,youhai，weixian
☣,shengwuweihai,youhai，weixian
⬆,shangjiantou,xiangshang，shangbian
↗,zhixiangyoushangjiaodejiantou,youshangfang
➡,youjiantou,xiangyou，youbian，youzhuan
↘,xiangyouxiajiaozhidejiantou,youxiafang
⬇,xiajiantou,xiangxia，xiabian
↙,xiangzuoxiajiaozhidejiantou,zuoxiafang
⬅,zuojiantou,xiangzuo，zuobian，zuozhuan
↖,zhixiangzuoshangjiaodejiantou,zuoshangfang
↕,shangxiajiantou,
↔,zuoyoujiantou,
↩,xiangzuowanqudeyoujiantou,zuozhuan
↪,xiangyouwanqudezuojiantou,youzhuan
⤴,xiangshangwanqudeyoujiantou,
⤵,xiangxiawanqudeyoujiantou,
🔃,shunshizhenchuizhijiantou,xuanzhuan，fanzhuan
🔄,nishizhenjiantou,xuanzhuan，fanzhuan
🔙,fanhuijiantou,huitui，chehui
🔚,jieshujiantou,
🔛,onjiantou,
🔜,soonjiantou,
🔝,xiangshangjiantou,
🛐,libaitang,
⚛,yuanzifuhao,weiguan
🕉,aomufuhao,
✡,daweizhixing,liumangxing，daweixing、youtaixing，liujiaoxing
☸,falun,
☯,yinyang,taiji，liangji
✝,ladingshishizijia,
☦,dongzhengjiaoshizijia,
☪,xingyue,
☮,hepingfuhao,
🕎,youtaijiaozhutai,
🔯,liumangxing,daweizhixing，daweixing、youtaixing，liujiaoxing
♈,baiyangzuo,3yue，4yue
♉,jinniuzuo,4yue，5yue
♊,shuangzizuo,5yue，6yue
♋,juxiezuo,6yue，7yue
♌,shizizuo,7yue，8yue
♍,chunvzuo,8yue，9yue
♎,tianchengzuo,9yue，10yue
♏,tianxiezuo,10yue，11yue
♐,sheshouzuo,11yue，12yue
♑,mojiezuo,12yue，1yue
♒,shuipingzuo,1yue，2yue
♓,shuangyuzuo,2yue，3yue
⛎,shefuzuo,
🔀,suijibofangyinguifuhao,wuguilv
🔁,chongfufuhao,xunhuan
🔂,chongfudangeyinguifuhao,danquxunhuan
⏮,shangyishou,shangyige
⏭,xiayishou,xiayige
⏯,zanting,tingzhi
⏸,zanting,tingzhi
♂,nanxing,nanxing
♀,nvxing,nvxing
▶,xiangyouzhidesanjiaoxing,bofang
⏩,kuaijinfuhao,jiasu
◀,xiangzuozhidesanjiaoxing,shangyige，shangyishou
⏪,daohuifuhao,huitui
🔼,xiangshangzhidesanjiaoxing,
⏫,xiangshangzhideshuangsanjiaoxing,
🔽,xiangxiazhidesanjiaoxing,
⏬,xiangxiazhideshuangsanjiaoxing,
⏺,tingzhifuhao,zanting
⏹,tingzhifuhao,zanting
⏏,tuichufuhao,dakai
🎦,dianyingyuanfuhao,yingyuan，fangyingting
🔅,diliangdufuhao,
🔆,gaoliangdufuhao,
📶,shoujixinhaotiao,mange
📳,zhendongmoshi,
📴,yidongdianhuaguanji,
✖,chenghao,chengyi，beishu
➕,jiahao,jiazong，xiangjia
➖,jianhao,xiangjian，qudiao
➗,chuhao,chuyi
♾,wuqiongda,wujixian
‼,hongseshuanggantanhao,gankai，gantan，zhenjing
⁉,hongsegantanhaojiawenhao,en？，shenme？！
❓,hongsewenhao,yiwen
❔,baisewenhao,yiwen
❕,baisegantanhao,gankai，gantan，zhenjing
❗,hongsegantanhao,gankai，gantan，zhenjing
〰,bolangxingpozhehao,keai
💱,huobiduihuan,huanwaihui
💲,meiyuanfuhao,
⚕,yiliaobiaozhi,jiuyuan
♻,huishoubiaozhi,kehuishou，huanbao
⚜,yuanwei,
🔱,sanchajibiaozhi,haishen
📛,xingmingpai,gongpai
🔰,biaomingshichuxuezhederiwenfuhao,chuji，xiaobai
⭕,yuanxingbiaoji,yuanquan
✅,gouhao,duigou，zhengque，wancheng
☑,dagoufangge,duigou，zhengque，wancheng
✔,gouhao,duigou，zhengque，wancheng
❌,shizibiaozhi,cuowu，weiwancheng，chahao
❎,chahao,cuowu，weiwancheng
➰,juanquhuan,wanqu
➿,shuangjuanquhuan,wanqu
〽,geyaokaishijihao,
✳,youbagenzhoudexinghao,duojiaoxing
✴,bajiaoxing,
❇,shanliangde,sijiaoxing，shanguang
©,banquanfuhao,
®,zhucebiaoji,
™,shangbiaofuhao,
#️⃣,shuzifuhao,
*️⃣,xinghao,
0️⃣,jianmaoshuzi0,ling
1️⃣,jianmaoshuzi1,yi
2️⃣,jianmaoshuzi2,er
3️⃣,jianmaoshuzi3,san
4️⃣,jianmaoshuzi4,si
5️⃣,jianmaoshuzi5,wu
6️⃣,jianmaoshuzi6,lu
7️⃣,jianmaoshuzi7,qi
8️⃣,jianmaoshuzi8,ba
9️⃣,jianmaoshuzi9,jiu
🔟,jianmaoshuzi10,shi
🔠,daxiezimudeshurufuhao,
🔡,xiaoxiezimudeshurufuhao,
🔢,shuzideshurufuhao,
🔣,fuhaodeshurufuhao,
🔤,zimudeshurufuhao,yingwen
🅰,Axingxie,
🆎,ABxingxie,
🅱,Bxingxie,
🆑,CLfuhao,
🆒,coolfuhao,ku，shuai，zan
🆓,mianfeifuhao,
ℹ,xinxiyuan,
🆔,shibiefuhao,shenfen
Ⓜ,yuanquanbaoweide,
🆕,newfuhao,
🆖,NGfuhao,nake
🅾,Oxingxie,
🆗,OKfuhao,haode
🅿,tingchechangfuhao,
🆘,SOSfuhao,jiuming，qiujiu
🆙,upfuhao,
🆚,fangxingVSbiaozhi,duizhan，bisai
🈁,riwenzimufuhao，biaoshi“zheli”,
🈂,riwenfuhao，biaoshi“fuwu”huo“fuwufei”,xiaofei
🈷,riwenfuhao，biaoshi“yuezongliang”,
🈶,riwenfuhao，biaoshi“shoufei”,youchang
🈯,yuliu,
🉐,riwenfuhao，biaoshi“yijia”,taojiahuanjia，jiangjia
🈹,riwenfuhao，biaoshi“dazhe”,youhui
🈚,riwenfuhao，biaoshi“mianfei”,
🈲,riwenfuhao，biaoshi“jinzhi”,
🉑,riwenfuhao，biaoshi“kejieshou”,
🈸,riwenfuhao，biaoshi“shenqing”,
🈴,riwenfuhao，biaoshi“hege”,
🈳,biaoshi“youkongwei”,kongdang，kongzhe
㊗,riwenfuhao，biaoshi“qingzhu”,gongxi，zhuhe
㊙,riwenfuhao，biaoshi“baomi”,mimi，jimi
🈺,riwenfuhao，biaoshi“kaishiyingye”,yingyezhong
🈵,riwenfuhao，biaoshi“yiman“meiyoukongwei,
🔴,hongseyuanquan,
🟠,chengseyuanquan,
🟡,huangseyuanquan,
🟢,lvseyuanquan,
🔵,lanseyuanquan,
🟣,ziseyuanquan,
🟤,zongseyuanquan,
⚫,heiseyuanquan,
⚪,baiseyuanquan,
🟥,hongsefangkuang,
🟧,chengsefangkuang,
🟨,huangsefangkuang,
🟩,lvsefangkuang,
🟦,lansefangkuang,
🟪,zisefangkuang,
🟫,zongsefangkuang,
⬛,heixiandafangkuang,
⬜,baixiandafangkuang,
◼,zhongdengdaxiaodeheixianfangkuang,
◻,zhongdengdaxiaodebaixianfangkuang,
◾,zhongxiaoxingheixianfangkuang,
◽,zhongxiaoxingbaixianfangkuang,
▪,heixianxiaofangkuang,
▫,baixianxiaofangkuang,
🔶,chengsedalingxing,
🔷,lansedalingxing,
🔸,chengsexiaolingxing,
🔹,lansexiaolingxing,
🔺,xiangshangzhidehongsesanjiaoxing,
🔻,xiangxiazhidehongsesanjiaoxing,
💠,neihanyigeyuandiandezuanshixingzhuang,
🔘,danxuananniu,
🔳,baisefangxinganniu,
🔲,heisefangxinganniu,
🏁,geziqi,qizhi
🚩,qiganshangdesanjiaoqi,qizhi
🎌,jiaochafangzhideqizhi,qizhi
🏴,heiqi,qizhi
🏳,baiqi,qizhi
🏳️‍🌈,caihongqi,qizhi
🇦🇨,asensongdao,qizhi
🇦🇩,andaoer,qizhi
🇦🇪,alabolianheqiuzhangguo,qizhi
🇦🇫,afuhan,qizhi
🇦🇬,antiguahebabuda,qizhi
🇦🇮,anguila,qizhi
🇦🇱,aerbaniya,qizhi
🇦🇲,yameiniya,qizhi
🇦🇴,angela,qizhi
🇦🇶,nanjizhou,qizhi
🇦🇷,agenting,qizhi
🇦🇸,meishusamoya,qizhi
🇦🇹,aodili,qizhi
🇦🇺,aodaliya,qizhi
🇦🇼,aluba,qizhi
🇦🇽,aolanqundao,qizhi
🇦🇿,asaibaijiang,qizhi
🇧🇦,bosiniyaheheisaigeweina,qizhi，bohei
🇧🇧,babaduosi,qizhi
🇧🇩,mengjialaguo,qizhi
🇧🇪,bilishi,qizhi
🇧🇫,bujinafasuo,qizhi
🇧🇬,baojialiya,qizhi
🇧🇭,balin,qizhi
🇧🇮,bulongdi,qizhi
🇧🇯,beining,qizhi
🇧🇱,shengbatailemi,qizhi
🇧🇲,baimuda,qizhi
🇧🇳,wenlai,qizhi
🇧🇴,boliweiya,qizhi
🇧🇶,helanjialebidiqu,qizhi
🇧🇷,baxi,qizhi
🇧🇸,bahama,qizhi
🇧🇹,budan,qizhi
🇧🇻,buweidao,qizhi
🇧🇼,bociwana,qizhi
🇧🇾,baieluosi,qizhi
🇧🇿,bolizi,qizhi
🇨🇦,jianada,qizhi
🇨🇨,kekesi（jilin）qundao,qizhi
🇨🇩,gangguo-jinshasa,qizhi
🇨🇫,zhongfeigongheguo,qizhi
🇨🇬,gangguo-bulachaiweier,qizhi
🇨🇭,ruishi,qizhi
🇨🇮,ketediwa,qizhi
🇨🇰,kukequndao,qizhi
🇨🇱,zhili,qizhi
🇨🇲,kamailong,qizhi
🇨🇳,zhongguo,qizhi，shenzhou，jiuzhou，huaxia，zhonghua
🇨🇴,gelunbiya,qizhi
🇨🇵,kelibodundao,qizhi
🇨🇷,gesidalijia,qizhi
🇨🇺,guba,qizhi
🇨🇻,fodejiao,qizhi
🇨🇼,kulasuodao,qizhi
🇨🇽,shengdandao,qizhi
🇨🇾,saipulusi,qizhi
🇨🇿,jieke,qizhi
🇩🇪,deguo,qizhi
🇩🇬,digejiaxiyadao,qizhi
🇩🇯,jibuti,qizhi
🇩🇰,danmai,qizhi
🇩🇲,duominike,qizhi
🇩🇴,duominijiagongheguo,qizhi
🇩🇿,aerjiliya,qizhi
🇪🇦,xiudahemeililiya,qizhi
🇪🇨,eguaduoer,qizhi
🇪🇪,aishaniya,qizhi
🇪🇬,aiji,qizhi
🇪🇭,xisahala,qizhi
🇪🇷,eliteliya,qizhi
🇪🇸,xibanya,qizhi
🇪🇹,aisaiebiya,qizhi
🇪🇺,oumei,qizhi
🇫🇮,fenlan,qizhi
🇫🇯,feiji,qizhi
🇫🇰,fukelanqundao,qizhi
🇫🇲,mikeluonixiya,���zhi
🇫🇴,faluoqundao,qizhi
🇫🇷,faguo,qizhi
🇬🇦,jiapeng,qizhi
🇬🇧,yingguo,qizhi，lianhewangguo
🇬🇩,gelinnada,qizhi
🇬🇪,gelujiya,qizhi
🇬🇫,fashuguiyana,qizhi
🇬🇬,engexidao,qizhi
🇬🇭,jiana,qizhi
🇬🇮,zhibuluotuo,qizhi
🇬🇱,gelinglan,qizhi
🇬🇲,gangbiya,qizhi
🇬🇳,jineiya,qizhi
🇬🇵,guadeluopudao,qizhi
🇬🇶,chidaojineiya,qizhi
🇬🇷,xila,qizhi
🇬🇸,nanqiaozhiyadaohenansangweiqiqundao,qizhi
🇬🇹,weidimala,qizhi
🇬🇺,guandao,qizhi
🇬🇼,jineiyabishao,qizhi
🇬🇾,guiyana,qizhi
🇭🇰,zhongguoxianggangtebiexingzhengqu,qizhi
🇭🇲,hedehemaiketangnaqundao,qizhi
🇭🇳,hongdulasi,qizhi
🇭🇷,keluodiya,qizhi
🇭🇹,haidi,qizhi
🇭🇺,xiongyali,qizhi
🇮🇨,jianaliqundao,qizhi
🇮🇩,yindunixiya,qizhi
🇮🇪,aierlan,qizhi
🇮🇱,yiselie,qizhi
🇮🇲,maendao,qizhi
🇮🇳,yindu,qizhi，poluoduo
🇮🇴,yingshuyinduyanglingtu,qizhi
🇮🇶,yilake,qizhi
🇮🇷,yilang,qizhi
🇮🇸,bingdao,qizhi
🇮🇹,yidali,qizhi
🇯🇪,zexidao,qizhi
🇯🇲,yamaijia,qizhi
🇯🇴,qiaodan,qizhi
🇯🇵,riben,qizhi，yinghuazhiguo，dongying，fusang
🇰🇪,kenniya,qizhi
🇰🇬,jierjisisitan,qizhi
🇰🇭,jianpuzhai,qizhi
🇰🇮,jilibasi,qizhi
🇰🇲,kemoluo,qizhi
🇰🇳,shengjiciheniweisi,qizhi
🇰🇵,chaoxian,qizhi，beihan
🇰🇷,hanguo,qizhi，nanhan
🇰🇼,keweite,qizhi
🇰🇾,kaimanqundao,qizhi
🇰🇿,hasakesitan,qizhi
🇱🇦,laowo,qizhi
🇱🇧,libanen,qizhi
🇱🇨,shengluxiya,qizhi
🇱🇮,liezhidunshideng,qizhi
🇱🇰,sililanka,qizhi
🇱🇷,libiliya,qizhi
🇱🇸,laisuotuo,qizhi
🇱🇹,litaowan,qizhi
🇱🇺,lusenbao,qizhi
🇱🇻,latuoweiya,qizhi
🇱🇾,libiya,qizhi
🇲🇦,moluoge,qizhi
🇲🇨,monage,qizhi
🇲🇩,moerduowa,qizhi
🇲🇪,heishan,qizhi
🇲🇫,shengmading,qizhi
🇲🇬,madajiasijia,qizhi
🇲🇭,mashaoerqundao,qizhi
🇲🇰,beimaqidun,qizhi
🇲🇱,mali,qizhi
🇲🇲,miandian,qizhi
🇲🇳,menggu,qizhi
🇲🇴,zhongguoaomentebiexingzhengqu,qizhi
🇲🇵,beimaliyanaqundao,qizhi
🇲🇶,matinikedao,qizhi
🇲🇷,maolitaniya,qizhi
🇲🇸,mengtesailate,qizhi
🇲🇹,maerta,qizhi
🇲🇺,maoliqiusi,qizhi
🇲🇻,maerdaifu,qizhi
🇲🇼,malawei,qizhi
🇲🇽,moxige,qizhi
🇲🇾,malaixiya,qizhi
🇲🇿,mosangbike,qizhi
🇳🇦,namibiya,qizhi
🇳🇨,xinkaliduoniya,qizhi
🇳🇪,nirier,qizhi
🇳🇫,nuofukedao,qizhi
🇳🇬,niriliya,qizhi
🇳🇮,nijialagua,qizhi
🇳🇱,helan,qizhi，fengchezhiguo
🇳🇴,nuowei,qizhi
🇳🇵,niboer,qizhi
🇳🇷,naolu,qizhi
🇳🇺,niuai,qizhi
🇳🇿,xinxilan,qizhi，niuxilan
🇴🇲,aman,qizhi
🇵🇦,banama,qizhi
🇵🇪,bilu,qizhi
🇵🇫,fashubolinixiya,qizhi
🇵🇬,babuyaxinjineiya,qizhi
🇵🇭,feilvbin,qizhi
🇵🇰,bajisitan,qizhi
🇵🇱,bolan,qizhi
🇵🇲,shengpiaierhemikelongqundao,qizhi
🇵🇳,pitekaienqundao,qizhi
🇵🇷,boduolige,qizhi
🇵🇸,balesitanlingtu,qizhi
🇵🇹,putaoya,qizhi
🇵🇼,palao,qizhi
🇵🇾,balagui,qizhi
🇶🇦,kataer,qizhi
🇷🇪,liuniwang,qizhi
🇷🇴,luomaniya,qizhi
🇷🇸,saierweiya,qizhi
🇷🇺,eluosi,qizhi
🇷🇼,luwangda,qizhi
🇸🇦,shatealabo,qizhi
🇸🇧,suoluomenqundao,qizhi
🇸🇨,saisheer,qizhi
🇸🇩,sudan,qizhi
🇸🇪,ruidian,qizhi
🇸🇬,xinjiapo,qizhi
🇸🇭,shengheleinadao,qizhi
🇸🇮,siluowenniya,qizhi
🇸🇯,siwabaheyangmayan,qizhi
🇸🇰,siluofake,qizhi
🇸🇱,sailaliang,qizhi
🇸🇲,shengmalinuo,qizhi
🇸🇳,saineijiaer,qizhi
🇸🇴,suomali,qizhi
🇸🇷,sulinan,qizhi
🇸🇸,nansudan,qizhi
🇸🇹,shengduomeihepulinxibi,qizhi
🇸🇻,saerwaduo,qizhi
🇸🇽,shengmadingdao,qizhi
🇸🇾,xuliya,qizhi
🇸🇿,siweishilan,qizhi
🇹🇦,telisitan-dakuniya,qizhi
🇹🇨,tekesihekaikesiqundao,qizhi
🇹🇩,zhade,qizhi
🇹🇫,fashunanfanglingtu,qizhi
🇹🇬,duoge,qizhi
🇹🇭,taiguo,qizhi
🇹🇯,tajikesitan,qizhi
🇹🇰,tuokelao,qizhi
🇹🇱,dongdiwen,qizhi
🇹🇲,tukumansitan,qizhi
🇹🇳,tunisi,qizhi
🇹🇴,tangjia,qizhi
🇹🇷,tuerqi,qizhi
🇹🇹,telinidaheduobage,qizhi
🇹🇻,tuwalu,qizhi
🇹🇿,tansangniya,qizhi
🇺🇦,wukelan,qizhi
🇺🇬,wuganda,qizhi
🇺🇲,meiguolidao,qizhi
🇺🇳,lianheguo,qizhi
🇺🇸,meiguo,qizhi，meilijianhezhongguo，shanmudashu
🇺🇾,wulagui,qizhi
🇺🇿,wuzibiekesitan,qizhi
🇻🇦,fandigangcheng,qizhi
🇻🇨,shengwensentehegelinnadingsi,qizhi
🇻🇪,weineiruila,qizhi
🇻🇬,yingshuweierjingqundao,qizhi
🇻🇮,meishuweierjingqundao,qizhi
🇻🇳,yuenan,qizhi
🇻🇺,wanuatu,qizhi
🇼🇫,walisihefutunaqundao,qizhi
🇼🇸,samoya,qizhi
🇽🇰,kesuowo,qizhi
🇾🇪,yemen,qizhi
🇾🇹,mayuetedao,qizhi
🇿🇦,nanfei,qizhi
🇿🇲,zanbiya,qizhi
🇿🇼,jinbabuwei,qizhi
🏴󠁧󠁢󠁥󠁮󠁧󠁿,yinggelan,qizhi
🏴󠁧󠁢󠁳󠁣󠁴󠁿,sugelan,qizhi
🏴󠁧󠁢󠁷󠁬󠁳󠁿,weiershi,qizhi
🏴󠁵󠁳󠁴󠁸󠁿,meiguodezhou
